### ISSUE TITLE
Add LICENSE.txt for all modules

### ISSUE THREAD

**Issue by Emily-Jiang** [eclipse/microprofile-config#105]
Need to add Apache License.txt in all of the binaries shipped by config.

**Comment by struberg** [comment]
+1 good catch!

**Comment by keilw** [comment]
You mean every Maven module like api, tck, etc.? Don't they inherit relevant information from the parent POM?

**Comment by Emily-Jiang** [comment]
They can inherit from the parent pom, but the LICENSE.txt needs to end up in the archive.

**Comment by keilw** [comment]
Most Apache projects (maybe all if the Maven settings from the Parent POM are set to do it) end up having it in the META-INF of those archives.

**Comment by keilw** [comment]
It could be a second step, but regardless if MP ends up having a central BOM it should probably get a parent POM for those kinds of things ;-)
