### ISSUE TITLE
Try to get .editorconfig and .gitattributes like in the samples app

### ISSUE THREAD

**Issue by keilw** [eclipse/microprofile-config#111]
A collaborator to another GitHub project just pointed out the value of .gitattributes or .editorconfig files to avoid inconsistencies like CR vs. CRLF etc. or problems when one developer runs on Linux or Mac and another one on Windows. 
Check https://github.com/eclipse/microprofile-samples both of these files look pretty sound and do the job there.

**Comment by OndrejM** [comment]
Done with the commit https://github.com/eclipse/microprofile-config/commit/733f5a2643c79c246cffd5f3a1856d366079f23e

**Comment by OndrejM** [comment]
Also added .editorconfig from the samples project.
But mind that for it to work, it requires a plugin in most IDEs (Eclipse, Netbeans), see http://editorconfig.org/#download
Idea supports it out of the box.
