### ISSUE TITLE
Make Snapshots available to Snapshot repositories

### ISSUE THREAD

**Issue by keilw** [eclipse/microprofile-config#112]
Now that first steps are made to publish the BOM also to SonaType/Mavencentral, the infrastructure should allow other projects to not only deploy releases, but ideally from a CI server (or manually) also do Snapshot deployments.

https://repository.apache.org/content/groups/snapshots/org/apache/deltaspike/core/deltaspike-core-api/
shows DeltaSpike just did this today, so those involved should easily do the same here. Allowing implementors and interested vendors to get their hands on the API and finally start implement it. That won't happen soon or "Agile" if they need to wait till 1.1 is out and approved by Eclipse Foundation.

I trust it works with Sonatype Snapshots, but if JFrog OSS repos were also desired, let me know if you need help.

**Comment by Emily-Jiang** [comment]
We need to finalise the build tool for MicroProfile projects. Will it be Jenkins?

**Comment by OndrejM** [comment]
Yes, we can use Jenkins: https://ci.eclipse.org/microprofile/

**Comment by OndrejM** [comment]
We also need to add the NOTICE file into the distributed packages. Details: https://groups.google.com/d/msg/microprofile/sRqsnPTkkKE/V657wvPWAgAJ

**Comment by struberg** [comment]
That should be done already. Just check the jars. It's more complicated though for the spec PDF.

**Comment by OndrejM** [comment]
I checked only sources and it seems that there is a copy of the NOTICE file in resources dir - this is however out of sync with the main NOTICE file. I believe we don't need to have a separate NOTICE file per each artifact and a single NOTICE file in the repo root would do, or not? I know this would be much more complex to setup in maven.

**Comment by OndrejM** [comment]
Based on chat today: @struberg will figure out which repository we can deploy snapshots, I will try to create a Jenkins job to deploy artifacts.

**Comment by keilw** [comment]
Sounds good. Thanks for working on a solution.

**Comment by OndrejM** [comment]
Jenkins job created: https://ci.eclipse.org/microprofile/job/CONFIG-maven-snapshots/
 - it's scheduled to run every day at 3am
 - it builds Parent POM, API and TCK artifacts from the master branch from scratch (in a clean working dir) and deploys them to a snapshot repo

To do once we have a snapshot repo available;
 - update the Repository URL (in the Deploy Artifacts post-build action) 
 - request Eclipse to add the credentials to the snapshot repo to global settings.xml file, under the server id "deployment-snapshot" (we don't have admin rights to the Jenkins instance)

**Comment by OndrejM** [comment]
@struberg I think that to get access to the Eclipse nexus to publish snapshots, we should create a bug to the Nexus component: https://bugs.eclipse.org/bugs/enter_bug.cgi?product=Community&component=Nexus

Similarly, to modify Jenkins config (the settings.xml), we would need to create a bug to the Hudson component afterward.

**Comment by OndrejM** [comment]
We may always ask on the Common-build Developers ML if unsure: https://dev.eclipse.org/mailman/listinfo/cbi-dev

**Comment by OndrejM** [comment]
According to https://wiki.eclipse.org/Services/Nexus, we should ask for creation of microprofile repos for read-write, which would be aggregate into the top-level read-only eclipse repo.

The name of the repo should be microprofile-releases and microprofile-snapshots.
I already updated the Jenkins job with the correct URL to microprofile-snapshots. The credentials should already be set in the global settings.xml by the wemasters automatically. 

We need to ask for the repo creation by issuing a bug: https://bugs.eclipse.org/bugs/enter_bug.cgi?product=Community&component=Nexus  @struberg Will you do that?

Once repos are created, the Jenkins job should hopefully deploy snapshot artifacts nightly.

**Comment by OndrejM** [comment]
I raised the request to create the Eclipse repository here: https://bugs.eclipse.org/bugs/show_bug.cgi?id=515426

**Comment by OndrejM** [comment]
Eclipse webmasters resolved the bug and we now have maven repositories in Eclipse. The Jenkins job is already publishing artifacts. See my email for more details: https://groups.google.com/d/msg/microprofile/OdNgCg5tp6c/AYVZdPe5AgAJ

**Comment by struberg** [comment]
Thank you so much, Ondrej! Owe you a beer for this ;)

**Comment by keilw** [comment]
@struberg Not sure, if @OndrejM prefers Austrian to Czech beer? ;-)
