### ISSUE TITLE
Clarify usage of discovered resources

### ISSUE THREAD

**Issue by jmesnil** [eclipse/microprofile-config#131]
While looking at adding tests for custom converters (in https://github.com/eclipse/microprofile-config/pull/130), I found out that the API was lacking a way to mandate converter discovery using the ServiceLoader pattern and the TCK was contradicting the API and spec.

With my PR, custom converters can be loaded using the ServiceLoader. However, the API implies that they are not loaded by default in https://github.com/eclipse/microprofile-config/blob/master/api/src/main/java/org/eclipse/microprofile/config/spi/ConfigProviderResolver.java#L62

I proposed to add a ConfigBuilder#addDiscoveredConverters() to discover them (in a similar way to discovered config sources).

The TCK assumes that Converters (and ConfigSources) that are added using the ServiceLoader are available from the created Config.
But the spec and the API states the opposite. If addDiscoveredConverters() and addDiscoveredSources() are not called, the resulting Config must not have any discovered resources.

I propose to clarify the spec and the the tck to remove any ambiguity.

1. Config returned by ConfigProvider and Injected Config have:
  * default config sources
  * discovered config sources
  * config sources from discovered config source providers
  * default converters
  * discovered converters

2. Config created by ConfigBuilder have:
  * default converters

To add default config sources / discovered config sources / discovered converters, the user would have to explicitly call ConfigBuilder's addDefaultSources / addDiscoveredSources / addDiscoveredConverters.
To be consistent, we should also add a addDiscoveredSourceProviders too.

Use case #1 will likely be the most used and it seems better to have "everything" available from the Config.
Use case #2 will allow to cover the rest of the use cases when users want to restrict what to do with config.
With this clarification, the TCK can remain as it is.

what do you think?

**Comment by struberg** [comment]
Hi Jeff!

I don't think the JavaDoc and TCK contradict each other, but I could be wrong ofc.

Here is why I think we are fine so far:
The JavaDoc for ConfigProviderResolver#getBuilder() only describes the case if you use the ConfigBuilder to create a manually built Config. This step is purely optional. If you don't use the Builder manually then the auto-discovery will be triggered. And this of course will pick up all Converters, ConfigSources, etc.
So to be more clear: A user does _not_ have to invoke getBuilder()! This is purely optional IF someone likes to manually forge a Config instance.

Was this the hint you were looking for or is there still something not clear?

Please read the JavaDoc in
https://github.com/eclipse/microprofile-config/blob/master/api/src/main/java/org/eclipse/microprofile/config/ConfigProvider.java#L37

And the Spec PDF might probably contain the most comprehensive explanation:
https://github.com/eclipse/microprofile-config/blob/master/spec/src/main/asciidoc/configprovider.asciidoc

Do you think this should be made even clearer?

We of course still miss a few TCK tests it seems.
We miss tests for a few converter types which should be provided by default. And we also miss injection for custom types, and Optional and Provider for types with a custom converter. 

txs and LieGrue,
strub

**Comment by Emily-Jiang** [comment]
I think this is solved as the addDiscoveredConverters were added and the ticket can be closed.
