### ISSUE TITLE
Update groupid and artifact id based on the mailing list discussion

### ISSUE THREAD

**Issue by Emily-Jiang** [eclipse/microprofile-config#132]
Based on the [discussion ](https://groups.google.com/forum/#!topic/microprofile/iWAimG6CtAM)on the groupid/artificatid, all specs needs to use the following convention.
Option D) 
  groupId: org.eclipse.microprofile.<subproject>
  artifactId: microprofile-<subproject>-<submodule>

Examples:
    org.eclipse.microprofile.config : microprofile-config-api  - for the Config API
    org.eclipse.microprofile.config : microprofile-config-tck - for the Config TCK

    org.eclipse.microprofile.conference : microprofile-conference - for Conference Demo app
    org.eclipse.microprofile.
conference : microprofile-conference-session - for the session module of the Conference app

**Comment by struberg** [comment]
tck, etc still point to the old groupId.

To prevent such errors in the future please rm -rf ~/.m2/repository/org/eclipse/microprofile and do a clean offline build

gonna commit the fix in a few minutes.
