### ISSUE TITLE
Remove "Prototype" from the repository description

### ISSUE THREAD

**Issue by keilw** [eclipse/microprofile-config#138]
This cannot be done via PR, so please somebody who can at least remove the word "Prototype" from
"Prototype Java EE configure APIs" in the description field.

**Comment by OndrejM** [comment]
I think only Eclipse webmasters can do this, after we issue a big in Eclipse's bugzilla.

**Comment by johnament** [comment]
@Emily-Jiang @OndrejM @struberg  what would be a good name for this?  The current name is `Prototype Java EE configure APIs` so I'm thinking `Microprofile Configuration API/Spec/TCK`

**Comment by Emily-Jiang** [comment]
something along the same line. Maybe just MicroProfile Config?

**Comment by OndrejM** [comment]
It's now changed to "MicroProfile Configuration Feature" after I raised the [bug with eclipse](https://bugs.eclipse.org/bugs/show_bug.cgi?id=519218).
