### ISSUE TITLE
Differentiate the non existing property and empty property

### ISSUE THREAD

**Issue by Emily-Jiang** [eclipse/microprofile-config#139]
Currently in the config spec, we stated that we cannot differentiate the property with value of "" and non existing property. I would like the javadoc relax about this. We should allow the implementation to differentiate if they can. We should not spec the limitation. Or we should fix this. I think we can differentiate it by calling getConfigNames().

**Comment by OndrejM** [comment]
I agree that any spec shouldn't limit what impl can do, only if it really makes sense to limit. I'd mention in the javadoc that the behavior for an empty value is undefined, in case of an empty value it's recommended that it's treated as non-existent value but empty values should be avoided to maintain portable behavior.

**Comment by Emily-Jiang** [comment]
I'll remove the tck that asserts the limitation and modify the javadoc accordingly.

**Comment by struberg** [comment]
Can you please first write up the use cases where such a "" vs null might happen?
Then it's more visible what you like to change.

**Comment by Emily-Jiang** [comment]
ConfigsourceA:
allergy = ""

On reading this property, I would like to know the value is "", which is different from the property does not exist.
