### ISSUE TITLE
getBuilder() should not contain the autodiscovered converters 

### ISSUE THREAD

**Issue by Emily-Jiang** [eclipse/microprofile-config#140]
The recent pr #130 changed the getBuilder() behaviour by adding the auto discovered converters. The getBuilder() is for an advanced users, who would like an empty builder. The discovered converters can be added whenever necessary, but it is best not to prepopulate this. The change in #130 needs to be reverted.

**Comment by Emily-Jiang** [comment]
The best solution is to add one more method addDiscoveredConverters() instead.

**Comment by OndrejM** [comment]
+1 on adding addDiscoveredConverters() and reverting adding the discovered converters automatically.

**Comment by struberg** [comment]
As explained in the original PR, this does not change the behaviour. We've discussed this in the past and all Converters always got automatically picked up!
There is also no reason to _not_ pick them up. You can always overload them with manually registered ones. 

We might probably define that any manually set overwrites any discovered Converters.

Go through the use cases and you'll see what I mean.

**Comment by OndrejM** [comment]
I understand, @struberg . But what Emily suggested is more in line with how config sources are treated by the builder. This should only affect builder and it shouldn't be a problem to add a one more call to the additional method when building a config.

**Comment by Emily-Jiang** [comment]
+1 @OndrejM ! We discussed this in the past. Originally, we had all discovered config sources and converters added. After discussing with various people, we settled on the empty builder with just the default converters in.
