### ISSUE TITLE
Tck: MissingValueOnInstanceInjectionTest wrong @ShouldThrowException(DeploymentException.class) 

### ISSUE THREAD

**Issue by hutchig** [eclipse/microprofile-config#143]
As at commit baf95... then the test
[MissingValueOnInstanceInjectionTest](https://github.com/eclipse/microprofile-config/blob/master/tck/src/main/java/org/eclipse/microprofile/config/tck/broken/MissingValueOnInstanceInjectionTest.java)
is written to expect a deployment exception:
```java
@ShouldThrowException(DeploymentException.class)
@Deployment
public static WebArchive deploy() {
```
This is because a  request scoped bean 'MissingValueOwner' has an Integer attribute
injected from a non-existing property:
```java
@RequestScoped
    public static class MissingValueOwner {
        @Inject
        @ConfigProperty(name="not.existing.value")
        private Long configValue;
}
```
However, there is no instance of MissingValueOwner that is used or created by
the testcase, so no instance is created (including at deployment) so there should be no
exception at deployment time.

**Comment by struberg** [comment]
Doesn't matter imo. That MissingValueOwner could be resolved via Instance<T> or BeanManager directly at runtime. 
The current behaviour follows the same logic than the CDI built-in validations.

**Comment by hutchig** [comment]
OK I will close this - thanks a lot for taking the time to discuss it.
I was a bit worried that this behaviour would mean that config sources
would need to be operational (successfully deployed) before anything that 
used them could deploy and this was a new possible form of circular dependency
but I guess that:
a) this is not a new type of problem
b) one can always use default values
c) it may be exactly the behaviour some people want in order to ensure correct configuration
d) if all the config values have to be present or defaulted it can provide a base for a future MPConfig feature that does configuration verification (using user supplied constraint code) at deploy time.

**Comment by hutchig** [comment]
Will transfer this to our local system and make our implementation pass the test.
