### ISSUE TITLE
Tck:WrongConverterOnInstanceInjectionTest wrong @ShouldThrowException(DeploymentException.class) 

### ISSUE THREAD

**Issue by hutchig** [eclipse/microprofile-config#144]
As at commit baf95... then the test
[WrongConverterOnInstanceInjectionTest](https://github.com/eclipse/microprofile-config/blob/master/tck/src/main/java/org/eclipse/microprofile/config/tck/broken/WrongConverterOnInstanceInjectionTest.java)
is written to expect a deployment exception:
```java
@ShouldThrowException(DeploymentException.class)
@Deployment
public static WebArchive deploy() {
```
This is because a  request scoped bean 'ConfigOwner' has an Integer attribute
injected from a property with no suitable converter: 
```java


                .addAsManifestResource(new StringAsset("my.long.value=xxxxx"), "microprofile-config.properties")
...
    @RequestScoped
    public static class ConfigOwner {
        @Inject
        @ConfigProperty(name="my.long.value")
        private Long configValue;
    }
```
However, there is no instance of the bean that is used or created by
the testcase, so no instance is created (including at deployment) so there should be no
exception at deployment time.

**Comment by struberg** [comment]
Same like #143.
Makes no difference since the ConfigOwner could be resolved dynamically at runtime.
The current behaviour follows the same logic than the CDI built-in validations.

**Comment by hutchig** [comment]
Understand what you are saying. When I run this test under WebSphere Liberty config beta implementation and Weld there is no deployment exception, as the test expects, so the test fails. I will confer on the way forward :-)

**Comment by struberg** [comment]
Oki, do you see the ProcessInjectionPoint, ProcessAnnotatedType etc for it getting fired?
If so, then probably there's just the check missing in the impl.

**Comment by hutchig** [comment]
Just as you said, I will transfer to our local system.
