### ISSUE TITLE
Tck: CDIPlainInjectionTest war missing classes TestSetup, AdditionalMatchers

### ISSUE THREAD

**Issue by hutchig** [eclipse/microprofile-config#146]
In [CDIPlainInjectionTest](https://github.com/eclipse/microprofile-config/blob/master/tck/src/main/java/org/eclipse/microprofile/config/tck/CDIPlainInjectionTest.java)
We see
```
@Test
    public void can_inject_dynamic_values_via_CDI_provider() {
...        
   ensure_all_property_values_are_defined();
...
   private void ensure_all_property_values_are_defined() {
        TestSetup.ensurePropertyDefined("my.string.property", "text");
```
but TestSetup is not in the jar, so one gets: 
```
can_inject_dynamic_values_via_CDI_provider(org.eclipse.microprofile.config.tck.CDIPlainInjectionTest)  Time elapsed: 0.153 sec  <<< FAILURE!
java.lang.NoClassDefFoundError: org/eclipse/microprofile/config/tck/testsupport/TestSetup
```
The test case needs: 
.addClasses(TestSetup.class, AdditionalMatchers.class)
added to the war creation ~line:60

**Comment by Emily-Jiang** [comment]
Thanks @hutchig ! Please check whether the latest code fix is ok. I tried to fix it but Mark raced and committed first. If the fix is ok, please close the issue.

**Comment by hutchig** [comment]
We did get AdditionMatchers.class in Mark's change but we have still not got the required
"TestSetup.class" that is in Emily's commit. So one more change needs to get to the branch.

**Comment by Emily-Jiang** [comment]
@hutchig Mark deleted the TestSetup.java in his commit.

**Comment by struberg** [comment]
yes sorry, did a git-pull but got no changes, no sure what happened.

The TestSetup.java was just used in one test, so instead of adding the class I just pulled the one method which got used over to this one test.

@Emily-Jiang do you want to fix it or should I?

**Comment by hutchig** [comment]
Working now.
