### ISSUE TITLE
Tck: CustomConfigSourceTest missing deployment of CustomDbConfigSource.class 

### ISSUE THREAD

**Issue by hutchig** [eclipse/microprofile-config#147]
The Tck test [CustomConfigSourceTest](https://github.com/eclipse/microprofile-config/blob/master/tck/src/main/java/org/eclipse/microprofile/config/tck/CustomConfigSourceTest.java)
has
```
.addAsServiceProvider(ConfigSource.class, CustomDbConfigSource.class)
.addAsServiceProvider(ConfigSourceProvider.class, CustomConfigSourceProvider.class)
```
but neither class is added to the archives explicitly. 
One can see the javadoc for addAsServiceProvider has ` Warning: this method does not add the specified classes to the archive.` :

```
/**
     * Adds a META-INF/services/ServiceInterfaceName {@link Asset} representing this service.
     *
     * Warning: this method does not add the specified classes to the archive.
     *
     * @param serviceInterface
     *            The Service Interface class
     * @param serviceImpls
     *            The Service Interface Implementations
     * @return This virtual archive
     * @throws IllegalArgumentException
     *             if serviceInterface is null
     * @throws IllegalArgumentException
     *             if serviceImpls is null or contain null values
     */
    /*
     * TODO: The interface should have been like this: <X> T addServiceProvider(Class<X> serviceInterface, Class<?
     * extends X>... serviceImpls) throws IllegalArgumentException; But due to how java generic works, this will cause a
     * unsafe warning for the user.
     */
    T addAsServiceProvider(Class<?> serviceInterface, Class<?>... serviceImpls) throws IllegalArgumentException;
```
...and indeed the test fails with
com.ibm.ws.microprofile.config.interfaces.ConfigException: CWMCG0011E: Unable to discover ConfigSourceProviders. The exception is: java.util.ServiceConfigurationError: org.eclipse.microprofile.config.spi.ConfigSourceProvider: Provider org.eclipse.microprofile.config.tck.configsources.<CustomDbConfigSource or>CustomConfigSourceProvider not found.

 without the additional line:
```
  .addClasses(CustomDbConfigSource.class, CustomConfigSourceProvider.class)
```
around line 54.

**Comment by struberg** [comment]
Good catch! 

Just to explain why I did not see those and why all seem to work in my impl.
I only test against an in-process Arquillian connector. In the end it doesn't matter whether this be OpenWebBeans or Weld. Both behave the same in that they just start the cdi container on the same JVM and ClassPath as the test which runs. So they also see the classes from the test classpath.

Other containers (e.g. wildfly-managed and tomee-build-managed) use a separate JVM and thus also will not see those classes. 
I'll work through the tests and try to add the missing classes.
