### ISSUE TITLE
Should we not to automatically convert to the old style Date

### ISSUE THREAD

**Issue by Emily-Jiang** [eclipse/microprofile-config#151]
In Converter javadoc, we ask the default converter Date to be provided
<li>{@code Date} in various ISO-8601 formats.
 *          'yyyy-MM-dd', 'yyyy-MM-ddThh:mm:ss' (timezone from current Locale), 'yyyy-MM-ddThh:mm:ssZ',
 *          'yyyy-MM-ddThh:mm:ss±hh:mm' (time zone designator)
 *          missing information is set to 0.</li>

I am wondering whether we should not support Date as a default, as there are so many variants of the format. In Java8, all java.time. classes should replace the java.util.Date. Shall we not support the old fashioned Date by default as we want to encourage the developers to use the new types instead?

**Comment by Emily-Jiang** [comment]
@struberg @OndrejM please comment.

**Comment by OndrejM** [comment]
Makes sense to me to drop converters for old Date types. it seems to add a lot of work for implementors and also is hard to specify clearly and cover with TCK tests. 

it should be easy to provide a custom converter for specific usecases. Implementations may even optionally provide such converters, but it doesn't have to be specified.

**Comment by struberg** [comment]
I'd keep them. Doesn't cost much and there is still a lot of usage.
If we would drop them then people would still use em and the format would end up non-portable.

**Comment by Emily-Jiang** [comment]
It does cost. The implementor needs to guess the format. The Date is supposed to be superseded by the new type. We should encourage to use the new style. If anyone wants to use the Date, the converter should be provided by the app and it is portable.
