### ISSUE TITLE
Scope of where config_ordinal applies

### ISSUE THREAD

**Issue by johnament** [eclipse/microprofile-config#159]
`configsources` mentions the following:

> The ordinal for property file based <<ConfigSource,ConfigSources>> can be configured using the key `config_ordinal` inside the property file.

However, the only property file mentioned is `META-INF/microprofile-config.properties` so does this only apply to this property file?

**Comment by struberg** [comment]
Yes, good point. The described behaviour is actually only valid for all built-in ConfigSources.
A custom ConfigSource _might_ leverage this mechanism - but it also might return a hardcoded number!

Do you mind to provide a wording tweak to reflect this?

txs and LieGrue,
strub

**Comment by Emily-Jiang** [comment]
@struberg config_ordinal should not be restricted for the default config sources. The implementation of custom config sources are free to put the ordinal in the source and then in the implementation they can directly read from the source. In this way, they are freely reorder the config sources without updating their application. I'll make sure this spelled out in the spec.

**Comment by johnament** [comment]
Raised a PR

**Comment by Emily-Jiang** [comment]
@johnament please refer to my earlier comments. I think the config_ordinal is also valid in custom config sources.

**Comment by OndrejM** [comment]
I agree with @Emily-Jiang - it should be possible to override ordering of a custom config source using config_ordinal in it.
Although this requires checking this property for every custom config source which adds performance penalty, it shouldn't matter much because it's only a single property access compared to many other properties that an application would access from config sources.

**Comment by OndrejM** [comment]
I even think that `config_ordinal` should be allowed for system property and env var config sources to override their ordinal.

**Comment by Emily-Jiang** [comment]
Yes, Ondrej. I think that is intended behaviour. I think we are in sync. It is designed for all config sources regardless what they are.
