### ISSUE TITLE
The Internet of Things

### ISSUE THREAD

**Issue by johnament** [eclipse/microprofile-config#162]
`configprovider` makes reference that `getBuilder` is meant to be used with IoT devices/gateways, which seems to be a weird base requirement.

> This method is intended be used if a IoT container or any other external Factory can be used to give access to a manually created shared `Config`.

**Comment by struberg** [comment]
IoT etc was just intended as an example. It appears the wording is a bit square ;)

What I tried to express was that IF you don't want the auto-discovery, then use the Builder - and give a few examples.

I'd be happy if you could tweak the wording and make it more expressive.

txs and LieGrue,
strub

**Comment by OndrejM** [comment]
I believe it should be "IoC" container, not IoT :)
 
I fixed it already with https://github.com/eclipse/microprofile-config/commit/5f2141de18fabbc57d43843c6d2efded16df1d45
