### ISSUE TITLE
Time based built in converters

### ISSUE THREAD

**Issue by johnament** [eclipse/microprofile-config#163]
The following time based converters are registered automatically:

* `Duration`
* `LocalTime`
* `LocalDate`
* `LocalDateTime`
* `OffsetDateTime`
* `OffsetTime`
* `Instant`

However, there is no mention on what formats they should look like in properties.

**Comment by struberg** [comment]
Hi John!

It should be all there in the API:
https://github.com/eclipse/microprofile-config/blob/master/api/src/main/java/org/eclipse/microprofile/config/spi/Converter.java#L37

LieGrue,
strub
