### ISSUE TITLE
Need ability to pass in default value string or access to Converters 

### ISSUE THREAD

**Issue by starksm64** [eclipse/microprofile-config#169]
So I have created a Java SE prototype of the config using Weld, and one issue I'm seeing is that there is no api to handle the conversion of the default value one may have specified on a @ConfigProperty, for example:

    @Inject
    @ConfigProperty(defaultValue = "3.14")
    private float floatValue;

When I'm in the producer method, and say I have access to the application Config object, I have no way to convert the "3.14" string value into the InjectionPoint type. 

I'll create a discussion thread to talk about what API extensions might be appropriate.

**Comment by struberg** [comment]
Hi Scott!

The default values are also handled via the Converter SPI.
Do you mind sharing your exact goal and scenario?

**Comment by starksm64** [comment]
The context is this discussion thread:
https://groups.google.com/forum/#!topic/microprofile/dN6baKHCB-g

**Comment by Emily-Jiang** [comment]
I don't quite understand the problem. You can convert the default value same as other values. What is the special about it?

**Comment by starksm64** [comment]
The issue I was having is that I have a produce method like this:

    @Produces
    @ConfigProperty
    @Dependent
    Double produceDoubleConfigProperty(InjectionPoint injectionPoint) {
        System.out.printf("produceIntegerConfigProperty: %s\n", injectionPoint);
        return getValue(injectionPoint, Double.class, true);
    }

that calls a helper method like:

    private <T> T getValue(InjectionPoint injectionPoint, Class<T> target, boolean failIfMissing) {
        String name = getName(injectionPoint);
        if (name == null || name.isEmpty() || this.config == null) {
            return null;
        }

        Optional<T> configValue = this.config.getOptionalValue(name, target);
        if(!configValue.isPresent()) {
            // Check for a default value
            String defaultValue = getDefaultValue(injectionPoint);
            if(defaultValue != null && !defaultValue.contentEquals(ConfigProperty.UNCONFIGURED_VALUE)) {
                configValue = this.config.tryConvertValue(defaultValue, target);
            }
        }
        if(failIfMissing && !configValue.isPresent()) {
            System.err.printf("Failed to find ConfigProperty for: %s\n", injectionPoint);
            throw new DeploymentException(String.format("%s has no configured value", name));
        }
        return configValue.orElse(null);
    }

In my current iteration of the implementation, I had the Converters associated with the Config implementation. That is why I was thinking this should be available via the public api. However, now that I have gotten to custom converters, I see that I probably need to keep track of the non-standard conversions in order to create producer methods for them.

**Comment by struberg** [comment]
Why would one create a producer method for a @ConfigProperty manually?
This is intended by the spec to work out of the box for any custom type where a Converter exists.
No need to have any custom converter.

Here is how I implemented it:
https://svn.apache.org/repos/asf/geronimo/components/config/trunk/impl/src/main/java/org/apache/geronimo/config/cdi/ConfigExtension.java

**Comment by starksm64** [comment]
I was first just looking to support the required types, but then decided it should be general, so as I got into that I did see a better way was needed. Most likely this is now a non-issue which I'll close once I get a better implementation pass.

**Comment by starksm64** [comment]
So I have the generic implementation working, and I am still using the implementation specific conversion methods on the Config instance. I see that your implementation is doing the same:

https://svn.apache.org/repos/asf/geronimo/components/config/trunk/impl/src/main/java/org/apache/geronimo/config/cdi/ConfigInjectionBean.java:
                Config config = getConfig();
                return (T) config.getOptionalValue(key, clazz)
                        .orElse((**(ConfigImpl) config).convert(defaultValue, clazz)**);

What I was thinking when I created this issue is that one could potentially write CDI extension/producers to override behavior from that shipped with the Config implementation. I could see this API being generally useful, and it seems simple to implement, so I'll leave this open as a potential feature request.

The API addition I am suggesting is something along the lines of:

```
    /**
     * Use the {@link Converter}s registered with the config to convert a String value to a target property type.
     * @param svalue - the string value representation of the property
     * @param propertyType - the desired Java type of the property
     * @return the converted value
     * @throws TypeNotPresentException if there is no registered Converter
     */
    public <T> T convertValue(String svalue, Class<T> propertyType);
```

The TypeNotPresentException is not that important, I was just looking to avoid adding another exception type if there was one that made sense.

**Comment by Emily-Jiang** [comment]
Talked to @jmesnil  on config hangout. It is out of scope for API and it is implementation specific. close this. Please reopen if we understood you incorrectly.
