### ISSUE TITLE
Need 3rd Party Clearance for dependencies

### ISSUE THREAD

**Issue by kwsutter** [eclipse/microprofile-config#170]
Per the Initial Contribution Questionnaire process, we need to file Contribution Questionnaires for all of the 3rd party software that we are dependent on.
https://dev.eclipse.org/ipzilla/show_bug.cgi?id=12628

The Process is documented here:
https://www.eclipse.org/projects/handbook/#ip-third-party

I grepped the pom.xml files for this component and found the following dependencies...  We will need to get these filed before we could release config-1.0.

````
<dependency>
    <groupId>javax.enterprise</groupId>
    <artifactId>cdi-api</artifactId>
    <version>1.2</version>
</dependency>
<dependency>
    <groupId>org.jboss.arquillian</groupId>
    <artifactId>arquillian-bom</artifactId>
    <version>1.1.12.Final</version>
    <scope>import</scope>
    <type>pom</type>
</dependency>

<dependency>
    <groupId>org.asciidoctor</groupId>
    <artifactId>asciidoctorj-pdf</artifactId>
    <version>${asciidoctorj-pdf.version}</version>
</dependency>

<dependency>
    <!-- actually only referenced in JavaDoc -->
    <groupId>org.apache.geronimo.specs</groupId>
    <artifactId>geronimo-annotation_1.2_spec</artifactId>
    <version>1.0</version>
    <scope>provided</scope>
    <optional>true</optional>
</dependency>

<dependency>
    <groupId>org.apache.geronimo.specs</groupId>
    <artifactId>geronimo-atinject_1.0_spec</artifactId>
    <version>1.0</version>
    <scope>provided</scope>
</dependency>

<dependency>
    <groupId>org.testng</groupId>
    <artifactId>testng</artifactId>
    <version>6.9.9</version>
    <scope>compile</scope>
</dependency>
<dependency>
    <groupId>org.jboss.arquillian.testng</groupId>
    <artifactId>arquillian-testng-container</artifactId>
    <version>${arquillian.version}</version>
</dependency>

<dependency>
    <groupId>org.hamcrest</groupId>
    <artifactId>hamcrest-all</artifactId>
    <version>1.3</version>
    <scope>compile</scope>
</dependency>

<dependency>
    <groupId>org.jboss.shrinkwrap</groupId>
    <artifactId>shrinkwrap-api</artifactId>
    <scope>compile</scope>
</dependency>
````

**Comment by kwsutter** [comment]
I submitted the CQ for cdi-api 1.2 for the MP 1.1 effort:
https://dev.eclipse.org/ipzilla/show_bug.cgi?id=13740

I'll start on the other ones here...  But, why is geronimo-atinject_1.0_spec referenced?  Shouldn't that already be covered by the CDI API?

I may need some assistance with the jboss-specific references, but I'll get the ball rolling since we're running out of time...  I'll post back here when I get these CQs created...

**Comment by struberg** [comment]
atinject is JSR-330 which is separate from 299. CDI does _not_ include @javax.inject.Inject, Qualifier, Producer etc. Those are contained in the atinject api.

Want to do a hangout to go through the missing pieces?

**Comment by kwsutter** [comment]
Discussed this process with Mark via Slack (Thanks, Mark!).  I believe all of the 3rd Party CQs have now been submitted for Config 1.0.  Here's the full list of the CQ bug trackers for this component (that I know of)...

https://dev.eclipse.org/ipzilla/show_bug.cgi?id=13750
https://dev.eclipse.org/ipzilla/show_bug.cgi?id=13745
https://dev.eclipse.org/ipzilla/show_bug.cgi?id=13747
https://dev.eclipse.org/ipzilla/show_bug.cgi?id=13749
https://dev.eclipse.org/ipzilla/show_bug.cgi?id=13744
https://dev.eclipse.org/ipzilla/show_bug.cgi?id=13751
https://dev.eclipse.org/ipzilla/show_bug.cgi?id=13746
https://dev.eclipse.org/ipzilla/show_bug.cgi?id=13748

**Comment by kwsutter** [comment]
Simplified this a tad...  Turns out we can combine our build and test dependencies into a single CQ.  So, I am now tracking the following CQs for Config:

https://dev.eclipse.org/ipzilla/show_bug.cgi?id=13740
https://dev.eclipse.org/ipzilla/show_bug.cgi?id=13750
https://dev.eclipse.org/ipzilla/show_bug.cgi?id=13747
https://dev.eclipse.org/ipzilla/show_bug.cgi?id=13746
https://dev.eclipse.org/ipzilla/show_bug.cgi?id=13755

**Comment by Emily-Jiang** [comment]
Thanks @struberg @kwsutter !

**Comment by kwsutter** [comment]
All associated CQs are now complete.  Will need to re-submit CQs for any updates to our dependencies (runtime or build/test).
