### ISSUE TITLE
ConfigSource should have getPropertyNames method

### ISSUE THREAD

**Issue by smillidge** [eclipse/microprofile-config#178]
I'm in the middle of implementing the Config api for Payara Micro. 

While implementing the Config api I have to implement the method; ```public Iterable<String> getPropertyNames()```. 

The obvious implementation is to iterate over all the ConfigSource objects associated with the Config and call the corresponding ```public Iterable<String> getPropertyNames()``` method. 

However there is no corresponding method only ```Map<String, String> getProperties();``` this could be problematic for many config sources as it may be expensive to retrieve all the values as well as the keys.

I propose adding the ```getPropertyNames``` method to ConfigSource.

**Comment by Emily-Jiang** [comment]
getProperties().keySet() should give your the iterable for the property names. Is this not what you are thinking?

**Comment by smillidge** [comment]
That's how I have currently implemented it. 

However if you write a custom ConfigSource you have to implement getProperties which means you have to retrieve all names and ALL the values. Retrieving all the values may be expensive depending on the nature of the ConfigSource. For example it could be a roundtrip to Apache Zookeeper or something like that.

I actually don't like the getProperties method on the ConfigSource as it may be very expensive or impossible to implement, depending on the ConfigSource.

**Comment by Emily-Jiang** [comment]
We can discussing the performance issue in the MP1.1.
