### ISSUE TITLE
It is not clear in the spec when to use Custom ConfigSourceProvider

### ISSUE THREAD

**Issue by smillidge** [eclipse/microprofile-config#182]
https://github.com/eclipse/microprofile-config/blob/master/spec/src/main/asciidoc/configsources.asciidoc talks about registering Custom ```ConfigSourceProvider```s via the ```ServiceLoader``` mechanism. However there is no mention of discovered ```ConfigSourceProvider``` in the documentation on how a ```Config``` is built see https://github.com/eclipse/microprofile-config/blob/master/spec/src/main/asciidoc/configprovider.asciidoc 

Is the ```ConfigProvider.getConfig``` supposed to add all builtins, then add all discovered ```ConfigSource``` types and then add all ```ConfigSource```s via discovered ```ConfigSourceProvider``` classes. Which would somewhat defeat the dynamic nature of ConfigSourceProvider given the caching of the Config?

**Comment by OndrejM** [comment]
You are right, @smillidge, this isn't covered by the spec explicitly. Therefore it can be implemented in a more dynamic and less dynamic way - either use a custom ConfigSourceProvider at boot/deployment time once to retrieve the config sources and reuse them later, or ask ConfigSourceProvider to rebuild the config sources each time a config value is requested. The latter would introduce a serious performance penalty though.

For portable applications, it's safer to assume that dynamic config sources will be built at deploy time and after the app is started, the list of config sources stays static. We probably should make this explicit in the next version of the config feature. It's also the behavior of the Geronimo implementation (see the [DefaultConfigBuilder.build()](https://svn.apache.org/repos/asf/geronimo/components/config/trunk/impl/src/main/java/org/apache/geronimo/config/DefaultConfigBuilder.java) method).

If an application needs truly dynamic list of config sources, it can register new Config at any time using `ConfigProvider#registerConfig`. This wouldn't work with CDI though, as the spec doesn't say whether this also has any effoct on injected `Config` proxies (no CDI scope is defined for them, nor that a value from `ConfigProvider.getConfig` must be injected). Again, as an example, the Geronimo implementation calls `ConfigProvider.getConfig` to inject `Config`, but it creates an appliction scoped bean, therefore it's not affected by subsequent calls to `ConfigProvider#registerConfig` and the list of config sources it provides remains static.

We should cover this in the next version of the Config feature and specify whether the list of ConfigSources can be updated during runtime and how, and also specify any relation between the injected `Config` instance and the one retrieved from `ConfigProvider.getConfig` if it makes sense.

**Comment by struberg** [comment]
> Which would somewhat defeat the dynamic nature of ConfigSourceProvider given the caching of the Config?

I don't get this sentence. Could you elaborate what you mean?

To give you an example what the ConfigSourceProvider is intended for:

Think about writing support for config files written in yaml. Say you want to pick up all the information in ALL the myproject.yaml files on the classpath. 
They could all define a different ordinal, e.g. with the config_ordinal trick (a simple int value inside the config file). And thus each myproject.yaml file found on the classpath gets served as separate ConfigSource. Makes sense?

**Comment by smillidge** [comment]
That's just one time creation of multiple individual ConfigSources from the provider which makes sense. 

The spec wording is ```This is useful if you need to dynamically pick up multiple ConfigSources```  the word dynamic implies constant change which this isn't.  Hence the question of when should I call the ConfigSourceProvider once when the Config is created and associated with the application or every time a Config is requested by the application.
