### ISSUE TITLE
Scope of ServiceProvider registered ConfigSources

### ISSUE THREAD

**Issue by johnament** [eclipse/microprofile-config#185]
The TCK makes a few archives that look like this:

```java
    @Deployment
    public static Archive deployment() {
        return ShrinkWrap.create(WebArchive.class)
                .addClasses(CDIPlainInjectionTest.class, SimpleValuesBean.class, DynamicValuesBean.class, 
                        AdditionalMatchers.class, TestConfigSource.class)
                .addAsServiceProvider(ConfigSource.class, TestConfigSource.class)
                .addAsWebInfResource(EmptyAsset.INSTANCE, "beans.xml");
    }
```

This one makes sense, since the config source is added as a service provider to the entire WAR file.

However, we also have this archive:

```java
    @Deployment
    public static WebArchive deploy() {
        JavaArchive testJar = ShrinkWrap
                .create(JavaArchive.class, "cdiOptionalInjectionTest.jar")
                .addClasses(CdiOptionalInjectionTest.class, OptionalValuesBean.class)
                .addAsManifestResource(new StringAsset("my.optional.int.property=1234\nmy.optional.string.property=hello"),
                        "microprofile-config.properties")
                .addAsManifestResource(EmptyAsset.INSTANCE, "beans.xml")
                .as(JavaArchive.class);

        WebArchive war = ShrinkWrap
                .create(WebArchive.class, "cdiOptionalInjectionTest.war")
                .addAsLibrary(testJar);
        return war;
    }
```

By typical java semantics, this would mean that the `microprofile-config.properties` would only apply to the JAR within the WAR.  Likewise in this example

```java
    @Deployment
    public static WebArchive deploy() {
        JavaArchive testJar = ShrinkWrap
                .create(JavaArchive.class, "customConfigSourceTest.jar")
                .addClasses(AutoDiscoveredConfigSourceTest.class, CustomDbConfigSource.class, Pizza.class, PizzaConverter.class)                
                .addAsManifestResource(EmptyAsset.INSTANCE, "beans.xml")
                .addAsServiceProvider(ConfigSource.class, CustomDbConfigSource.class)
                .addAsServiceProvider(Converter.class, PizzaConverter.class)
                .as(JavaArchive.class); 

        WebArchive war = ShrinkWrap
                .create(WebArchive.class, "customConfigSourceTest.war")
                .addAsLibrary(testJar);
        return war;
    }
```

This would mean the `ConfigSource` only applies to this JAR, and the `Converter` is only within this JAR.

**Comment by Emily-Jiang** [comment]
@johnament The property's visibility is controlled via classloading visibility. In your example of jar inside the war, the property file will be loaded by the war classloader and it is available to all classes loaded by the same classloader.

**Comment by OndrejM** [comment]
I have no issue with that - as Emily explained, the config source will be visible to the whole WAR. We didn't specify any rules for CDI though - should we clarify how CDI produces the Config instance? The Geronimo implementation just calls `ConfigProvider.getConfig()` in the producer, which returns an application scoped bean. Is it specified somewhere? I think it should be specified, what do you think, @struberg ?

**Comment by struberg** [comment]
> By typical java semantics, this would mean that the microprofile-config.properties would only apply to the JAR within the WAR. Likewise in this example

Nope, in a WAR you have a flat ClassLoader. A class in a WEB-INF/lib/bla.jar is treated exactly the same like a class in WEB-INF/classes.

So +1 to the explanation from @Emily-Jiang

Think about a resource bundle which is somewhere in some random jar in the class path of a WAR - or even in WEB-INF/classes. It makes absolutely no difference where it is.

I guess your thinking comes from the 'strict' CDI BDA interpretation. But this is actually total unnatural and contradicts the whole Servlets spec as well...

**Comment by johnament** [comment]
Ok, so then it would be correct to say that the scope of a config source is to the application it is a part of, and that is all?

**Comment by struberg** [comment]
Yes, but be careful with the term 'Application' in JavaEE. There are different specs where 'Application' means something different. And the EE umbrella spec even mixes the term for WAR, EAR, RAR, etc. So it's essentially not clear what 'Application' means if you ship a WAR inside an EAR... 
This leads to ugly things like https://issues.jboss.org/browse/CDI-129

**Comment by Emily-Jiang** [comment]
+1 on Mark! I would say the scope of a config source is based on classloading visibility or something along the line. The word 'Application' is overused and it means different thing in different environments as explained by Mark.

**Comment by johnament** [comment]
Are we in fact saying its limited by classloader?  E.g. if I create a child classloader and that loads a config source, that config source is only accessible in classes within that class loader?

**Comment by smillidge** [comment]
Not in our implementation as we are storing the config properties as transient metadata at the application level. As I took the word Application literally as we already have the concept of an Application in Payara internals.

**Comment by johnament** [comment]
@smillidge so if I have an ear w/ two war files, are those two different configs or one config?

**Comment by smillidge** [comment]
tricky I would have to test it as it will depend on resolving the TCCL to application in our code. 
As microprofile doesn't spec an ear I suppose it is undefined.

**Comment by struberg** [comment]
Well, we explicitly went the CL route and immutable ConfigSources as the 'scope' of 'Application' is very different in various containers when it comes to EARs.

Another point is that we explicitly have the ClassLoader param. 

Consider you have an ejb @Singleton in a shared EAR lib. This uses a Config.
Should this also include the ConfigSources from a WAR? Or not?

The answer is: it *totally* depends! 
If you build some container like lib like some JSF or CDI extension, then you explicitly want to pick up config you find via the TCCL. And of course you then have to re-evaluate the config for every request!.
Otoh if you have a shared business service, then you want to only pick up the config which is available (means: can be seen) in your ear-lib - and explicitly ignore anything from the WARs.

Let's agree that EARs are bloody unportable when it comes to real life apps. Way too many corner cases and unspecified behaviour all around. 
But with our current Config approach to resolve only via CL, it's at least theoretically possible to make this part really portable.

**Comment by smillidge** [comment]
We map CL to an Application which is a deployment. Simply because I really don't want to store ClassLoaders anywhere else in the server internals other than in the application even via Weak References. Having classloaders hanging around longer than you need them causes havoc on redeployments in the application server. Especially in platforms like Windows due to file locking.

**Comment by Emily-Jiang** [comment]
The Application means the module in Mark's world. I would say "map CL to an module". If you literally use application and your application consists multiple wars, you might invalidate classloader isolation policy.

**Comment by struberg** [comment]
@smillidge according to my quick tests deploying an EAR to Glassfish still results in different CLs per WARs in the EAR + one parent CL for the EAR itself. That's perfectly sensible that way. 
The point is that depending on the interpretation of the term 'Application' (EAR, WAR, etc) you might end up with different results. 
Yes, 'Module', 'Application' etc. All used in JavaEE but without any proper definition throughout the EE specs. Or better: with contradicting definitions.

e.g. regarding 'Module': each WAR is a Module, right? And each EJB-jar is a Module as well, right? And Modules should not see each other. E.g. a class from war1 cannot see classes from war2 in the EAR. But why do ejb-jars see each other then? 

EARs are a huge mess. I totally understand the aim to not store the ClassLoader as key somewhere but only the Application. But since the 'Application' term is really not well defined we settled on the CL itself. You can still determine the App from the CL, so all that internal storage is an implementation detail anyway.

**Comment by struberg** [comment]
and +1 to @Emily-Jiang s arguments

**Comment by Emily-Jiang** [comment]
I think this can be closed with a lot of explaination already. Please reopen if you think otherwise.
