### ISSUE TITLE
Add TCK test for default named ConfigProperty

### ISSUE THREAD

**Issue by smillidge** [eclipse/microprofile-config#197]
Add a test to validate the javadoc comment for ```ConfigProperty```

If it is not specified, it will be derived automatically as {@code <class_name>.<injetion_point_name>},
     * where {@code injection_point_name} is the field name or parameter name,
     * {@code class_name} is the fully qualified name of the class being injected to with the first letter decaptialised.

I would add it but I am not clear on what the name should be from the description above.

**Comment by Emily-Jiang** [comment]
Thanks @smillidge ! Will add this test in the next version.

**Comment by johnament** [comment]
@smillidge My understanding is that if you have this definition:

```java
package com.superbiz.myapp;
...
public class SomeClass {
    @Inject
    @ConfigProperty
    public String someValue;
}
```

The resolved property is `com.superbiz.myapp.SomeClass.someValue`.  Do others agree?

**Comment by smillidge** [comment]
Yes but all in lowercase I think.

**Comment by johnament** [comment]
ah, but if I'm reading it again it should be `com.superbiz.myapp.someClass.someValue` e.g. with capital 'C'

**Comment by johnament** [comment]
Ok, so I'm looking at what needs to happen in the TCK to fix this.  Following the pattern, I'm creating a static class in `CDIPlainInjectionTest` which leads to the FQCN of `org.eclipse.microprofile.config.tck.CDIPlainInjectionTest.DefaultPropertyBean`

The class looks like this:

```java
    @Dependent
    public static class DefaultPropertyBean {
        @Inject
        @ConfigProperty
        private String configProperty;
    }
```

My reading of the spec right now is that the property should be defined as:

```
org.eclipse.microprofile.config.tck.CDIPlainInjectionTest.defaultPropertyBean.configProperty=someValue
```

E.g. the enclosing class should not have any of its capitalization changed, only the actual class's first letter.

**Comment by struberg** [comment]
Not a fan of the auto-naming in general. But what John quoted sounds right according to what is defined right now.
