### ISSUE TITLE
Fix Sonatype validations errors to release in Maven Central

### ISSUE THREAD

**Issue by OndrejM** [eclipse/microprofile-config#200]
The following validations are failing when deployed only API and parent artifacts:
 - `Invalid POM: /org/eclipse/microprofile/config/microprofile-config-parent/1.0/microprofile-config-parent-1.0.pom: Project description missing, Developer information missing`
 - `Missing: no sources jar found in folder '/org/eclipse/microprofile/config/microprofile-config-api/1.0'`
 - `Missing Signature: '/org/eclipse/microprofile/config/microprofile-config-parent/1.0/microprofile-config-parent-1.0.pom.asc' does not exist for 'microprofile-config-parent-1.0.pom', 'microprofile-config-api-1.0-javadoc.jar', 'microprofile-config-api-1.0.pom', 'microprofile-config-api-1.0.jar'`

Here are Sonatype requirements: http://central.sonatype.org/pages/requirements.html

**Comment by OndrejM** [comment]
A guide to sign with a GPG key: http://blog.sonatype.com/2010/01/how-to-generate-pgp-signatures-with-maven/

**Comment by johnament** [comment]
@OndrejM  is this all done?

**Comment by johnament** [comment]
Closing this out, seems done.
