### ISSUE TITLE
Support for primitives

### ISSUE THREAD

**Issue by johnament** [eclipse/microprofile-config#204]
Presently, the following primitive types are not supported:

- `int`
- `long`
- `float`
- `double`
- `boolean`

These are the primitive versions for some of the classes defined in https://github.com/eclipse/microprofile-config/blob/master/spec/src/main/asciidoc/converters.asciidoc

IMHO they should be supported, with the notion that if you use them they cannot be wrapped in optional.

**Comment by struberg** [comment]
Hi John! Primitives are supported via autoboxing. Or do you think we miss any wrapper type?
