### ISSUE TITLE
Programmatic way to add converters

### ISSUE THREAD

**Issue by johnament** [eclipse/microprofile-config#205]
#125 mentions a CDI way to add converters.

However, I just need a plain way to register extra converters.  It should take type into account, as it's possible to use the same converter for base classes without needing multiple registrations.

**Comment by struberg** [comment]
The whole Config is immutable by design. 
Can you think about a way to add a Converter or any other Config component via CDI but still have the Config immutable?

**Comment by johnament** [comment]
I was figuring this applied more to the config builder, or some annotation that could be added that indicated the types the converter supported, e.g. `configBuilder.addConverter(type, converter)` or saying that the existing `addConverter` looked for an annotation `@Converts(Class...)`

**Comment by Emily-Jiang** [comment]
@jmesnil will you be able to port the changes from config jsr here?

**Comment by Emily-Jiang** [comment]
solved by #298
