### ISSUE TITLE
Update README with information about MP Config 1.0

### ISSUE THREAD

**Issue by OndroMih** [eclipse/microprofile-config#217]
THe current readme is obsole and needs an update. The readme is also displayed in http://microprofile.io/project/eclipse/microprofile-config

**Comment by johnament** [comment]
I'm going to wait until after MP Config 1.1 is out and update it with that version.  Sound fair?

**Comment by johnament** [comment]
So thinking out loud a bit.  What exactly is obsolete about the current contents?

**Comment by vsmid** [comment]
Hi, 

configprovider.asciidoc is mentioning ConfigProvider#registerConfig and ConfigProvider#releaseConfig. I can't see that those methods are accessible from there, please check it.

**Comment by johnament** [comment]
@vsmid thanks.  That's a miss, but should be pretty invisible to an end user.  You should almost never have to use those methods.  They are now on `ConfigProviderResolver`

**Comment by Emily-Jiang** [comment]
We should fix the asciidoc pointed out by @vsmid. I'll create a PR shortly.

**Comment by jmesnil** [comment]
Closing as we are past MP Config 1.0
