### ISSUE TITLE
Support Supplier<T> in addition to Provider<T>?

### ISSUE THREAD

**Issue by struberg** [eclipse/microprofile-config#220]
It turned out that some containers have problems with supporting custom Bean<Provider<T>>.
So @Inject @ConfigProperty Provider<String> goes through the CDI containers Instance implementation which is probably not the fastest. 

By injecting 
```
@Inject
@ConfigProperty
Supplier<String> myconfig;
```
the config impls might provide a 'native' way to get the config.

The configured value will be exactly be the same, it's just better performing a bit.

**Comment by johnament** [comment]
even though we don't have a bean of type provider, provider behavior works

**Comment by struberg** [comment]
Yes, it technically works, but it's a bit slower to go through Instance and bean resolving every time. 
The main point is that also allowing Supplier is functionally fine from a user pov and it is also a bit faster technically.

**Comment by johnament** [comment]
Agreed.  I don't think this is a big thing to add, but probably not this first pass.  I could also see a per impl feature of having this.

**Comment by dkellenb** [comment]
This would be great to always get the latest value. Currently we do it in this way:
```java
@Inject
Config config;

private void doSomeOperation() {
   // dynamic value
   Integer timeout = config.getValue("external.system.timeout", Integer.class);
   ...
}
```

Is there a better way how to get the *latest* value?

**Comment by Emily-Jiang** [comment]
Use case:
As an end user, I want to inject `Supplier` to get my config, similar to `Provider`.

**Comment by mcserra** [comment]
Hi. I was thinking if I could do this... Is it just adding a tck test, right?

**Comment by radcortez** [comment]
Most likely we need to also add a note into the spec to mention that injection via `Supplier` is supported.

**Comment by mcserra** [comment]
Thanks @radcortez.

**Comment by radcortez** [comment]
The support for this was added in #561.

I think we need to discuss this a littler further. I'm not against supporting `Supplier`, but once again we are diverging the CDI vs Programatic API. 

Should we consider supporting `Supplier` via the programatic API?

**Comment by Emily-Jiang** [comment]
> Should we consider supporting Supplier via the programatic API?

Supplier is a CDI API for taking in a dynamic injection value. In the programmatic API, the injected Config object is a proxy. config.getValue always gives you the up-to-date value. Therefore, support of `Supplier` is not necessary via the programmatic API.

**Comment by Emily-Jiang** [comment]
By the way, since this issue is addressed. I am going to close this issue. @radcortez for your questions, if you disagree with my explaination, please feel free to raise a separate issue.

**Comment by radcortez** [comment]
Well, Supplier is not a CDI API. Its from Java functions package and it stands on its own. Calling `.get` in the supplier is like calling another `Config.getValue`, so I see no reason why this is a CDI only thing. You don't really require a proxy for it.

**Comment by Emily-Jiang** [comment]
> Well, Supplier is not a CDI API. Its from Java functions package and it stands on its own. Calling .get in the supplier is like calling another Config.getValue, so I see no reason why this is a CDI only thing. You don't really require a proxy for it.

I meant to say `Provider` is a CDI API. Since this PR is to talk about some performance improvement over `Provider` via `Supplier`, when dealing with dyanmic properties. Feel free to create another issue listing the use case with Supplier for programmtic lookup. In my previous message, I have mentioned config.getValue() will always give you up to date value, so the dynamic aspect of the `Provider`, `Supplier` is unnecessary.

**Comment by radcortez** [comment]
It's fine. Let's leave it this way.
