### ISSUE TITLE
Add example of a TCK setup to the running_the_tck.asciidoc

### ISSUE THREAD

**Issue by starksm64** [eclipse/microprofile-config#225]
A concrete example of what I would like to see in the Config TCK docs is a link to an example TCK setup from an existing implementation. I have a pull request for this issue to illustrate what I was talking about in the TCK forum thread.

**Comment by johnament** [comment]
So is what's included enough for this?

**Comment by starksm64** [comment]
I'm fine with what I showed in the PR #226
