### ISSUE TITLE
CDI PlainInejctionTest tck issue

### ISSUE THREAD

**Issue by Emily-Jiang** [eclipse/microprofile-config#234]
In CDIPlainInjectionTest.java, the line here:

```
@Deployment
    public static Archive deployment() {
        // this is needed since there's a requirement to validate on start up
        System.setProperty(DEFAULT_PROPERTY_BEAN_KEY, "pathConfigValue");
        return ShrinkWrap.create(WebArchive.class)
                .addClasses(CDIPlainInjectionTest.class, SimpleValuesBean.class, DynamicValuesBean.class,
                        AdditionalMatchers.class, TestConfigSource.class, DefaultPropertyBean.class)
                .addAsServiceProvider(ConfigSource.class, TestConfigSource.class)
                .addAsWebInfResource(EmptyAsset.INSTANCE, "beans.xml");
    }
```

The `System.setProperty` was not set when we ran this tck, so a deployment error occurred. 

It is better improved to match the other properties such as stringProperty, which were set in a configsource.

**Comment by OndrejM** [comment]
Fixed by #235

**Comment by johnament** [comment]
I don't understand the issue here.  Reopening.

**Comment by Emily-Jiang** [comment]
There are two issues here:
1. System.setProperty(DEFAULT_PROPERTY_BEAN_KEY, "pathConfigValue"); is odd. It should follow the other properties - set in a configure source and then read in.
2. It does not work. System.setProperty(DEFAULT_PROPERTY_BEAN_KEY, "pathConfigValue"); was not set as a system property in the application starting by Arquillian. Hence, a deployment error occurred. 
The new change follows the pattern with the other properties and improve the framework.

**Comment by johnament** [comment]
Ok, so in your specific case you need it set somewhere else.

However, that doesn't mean setting it here is wrong for all use cases.  In general, the config TCK doesn't seem to do a good job of documenting what properties it needs set.  Many are in property files which is fine, however most impls will need to have a stanza of system properties like this

```xml
<environmentVariables>
                        <CDPATH>value-for-tck-since-we-ignore-empty</CDPATH>
                        <GLOBIGNORE>value-for-tck-since-we-ignore-empty</GLOBIGNORE>
                        <GNOME_KEYRING_CONTROL>value-for-tck-since-we-ignore-empty</GNOME_KEYRING_CONTROL>
                        <GNOME_KEYRING_PID>value-for-tck-since-we-ignore-empty</GNOME_KEYRING_PID>
                        <HISTIGNORE>value-for-tck-since-we-ignore-empty</HISTIGNORE>
                        <HISTTIMEFORMAT>value-for-tck-since-we-ignore-empty</HISTTIMEFORMAT>
                        <INSTANCE>value-for-tck-since-we-ignore-empty</INSTANCE>
                        <UPSTART_INSTANCE>value-for-tck-since-we-ignore-empty</UPSTART_INSTANCE>
                    </environmentVariables>
```

**Comment by johnament** [comment]
I just confirmed, it doesn't seem to fail on other impls as well.  However, would be good to tread on things like this more carefully in the future.  Don't want to inadvertently break someone else's implementation.

**Comment by OndrejM** [comment]
I understand that the problem with setting a system property like this is that the property isn't transferred when test is executed in a different JVM. This is what many arquillian connectors do, except the embedded connectors.

I think that the cleanest solution is to always specify config properties using a custom ConfigSource class, which is added to the archive under the test. It is then evident that the config property is there for test purposes and is required by the test scenario. This is unless providing config values as system properties is specifically tested, but this should be covered by a separate test suite in another class.

**Comment by Emily-Jiang** [comment]
+1 on Ondro! Since I changed backed to the way we used in the past and I know both Gconfig and Liberty plus other servers were fine with during Config 1.0 release. I also agree the better way is to use config sources not system properties, hence the change:o.
