### ISSUE TITLE
Don't discriminate against common sense converters

### ISSUE THREAD

**Issue by johnament** [eclipse/microprofile-config#248]
I was trying to figure out how far off Apache Tamaya was from implementing the feature set.  I noticed one test kept failing, even though I knew it wasn't registering the converter (`AutoDiscoveredConfigSourceTest.testAutoDiscoveredConverterNotAddedAutomatically` is the test).  It fails in Tamaya because Tamaya has the notion of "common sense" conversion (at least that's my term).  If the target class has a string based constructor, or a static `valueOf` method that takes a string, Tamaya will automatically convert that type.  It doesn't look at the converter on the classpath instead just loads a default converter strategy.

So I'm wondering, should we perhaps use a more explicit test that should fail for unknown reasons rather than a converter that has too simple of a use case (e.g. the class takes 1 string but really should take 2 strings since there are two values passed in).

**Comment by Emily-Jiang** [comment]
+1. I think we should add this support of string based constructor and valueOf to the spec. Archaius has this notion of "common sense" as well.

**Comment by Emily-Jiang** [comment]
In order to get Tamaya to pass tck, I'll raise a discussion to get a process to exclude error test cases. Thoughts?

**Comment by smillidge** [comment]
+1 to add common sense conversion to the spec

**Comment by struberg** [comment]
fixed the TCK and added it as an explicit requirement.
