### ISSUE TITLE
Define namespaces for config keys

### ISSUE THREAD

**Issue by pilhuhn** [eclipse/microprofile-config#252]
We should define (reserved) name spaces for config keys, especially with respect to other MP-technologies. This came up yesterday in the rest-client call, where we may want to prefix rest-client config keys with rest.client or rest-client.
Now it should be clear that this is meant for the mp-rest-client and not for custom code.
Perhaps it could be defined that all the mp-technologies register their properties under `mp.*` as in 
mp.rest-client.url
or
mp.metrics.global_tags

**Comment by jmesnil** [comment]
Should this be addressed by MicroProfile overall spec (and cascade to other MP specs)?

**Comment by Emily-Jiang** [comment]
I think as a general guideline, most specs have adopted mp. syntax. I agree with @jmesnil that this should be addressed by MP overall guideline. This has been though, so this can be closed.
