### ISSUE TITLE
Create a converter test for injection of generic type

### ISSUE THREAD

**Issue by OndrejM** [eclipse/microprofile-config#254]
Create a test for a converter for a generic type, such as `List<String>`:

```
@Inject
@ConfigProperty(name = "list.of.values")
List<String> values;
```

This may break current implementations as generic types cannot be converted to Class. They are of type ParameterizedType which cannot be directly cast to Class. E.g. it breaks current Payara implementation.

**Comment by johnament** [comment]
This is very similar to #255 .  As @OndrejM mentions, you cannot use `List<String>` but `List.class` works fine.  

One clever way to fix this is to change the argument from `Class<?>` to `Type` to allow the broader spectrum of types to be used.

**Comment by OndrejM** [comment]
As a workaround right now, it's possible to use arrays for typed lists, such as `String[]` instead of `List<String>`. Arrays work fine, it's just necessary to provide a converter from `String` to `String[]`.

The issue #255 is about providing such converter out of the box. I'm not sure if it makes sense because there's no common separator for items which wouldn't collide with item values.

**Comment by johnament** [comment]
We've added support for `List<T>` and `Set<T>` as an injection point.  Does that satisfy this need?

**Comment by Emily-Jiang** [comment]
#259 provides this support.
