### ISSUE TITLE
Support delimited properties lists

### ISSUE THREAD

**Issue by derekm** [eclipse/microprofile-config#255]
In the MicroProfile Config spec, there is a sample config, and the sample config shows a comma-separated list of email addresses:

https://github.com/eclipse/microprofile-config/blame/master/spec/src/main/asciidoc/architecture.asciidoc#L48

This being in one of the first high-level docs suggests that delimited lists is something that is supported out-of-the-box by MicroProfile Config, but that doesn't appear to be the case.

Geronimo Config has a well-hidden and hard-to-access `ConfigValueImpl.getValueList()` that does backslash-escaping & splitting on commas, but it looks like a non-standard extension, and I can't figure out how to access it yet.

Anyway, I'm just here as a lone voice in support of getting delimited lists off of a single config key! Thanks!

**Comment by OndrejM** [comment]
This suggestion sounds appealing, but there's no standard string separator that wouldn't collide with values. If we choose a comma to separate strings, what if a comma is also in a value of one of the strings? Maybe provide an annotation to specify the separator. But that wouldn't work with programmatic API, although it's not critical.

What I think would be more beneficial is to provide a JSON converter using JSON-B once it's adopted by MicroProfile. JSON would make conversion more robust for any values and would also support conversion to any Java class.

As an example, a JSON value of ["item1", "item2"] would be translated into `List<String>`.

**Comment by OndrejM** [comment]
A converter for a comma-separated list is very easy to write. But comma isn't always the best separator as it may appear in the value too. The converter would need to support escaping commas in the value.

**Comment by Emily-Jiang** [comment]
I believe #259 fixes this issue. Please reopen if you think otherwise.
