### ISSUE TITLE
Master branch not compiling

### ISSUE THREAD

**Issue by jeyvison** [eclipse/microprofile-config#258]
Hey folks :) Just cloned the master branch and tried to  mvn clean install it but the **MicroProfile Config Specification** step fails with this error: 

`Failed to execute goal org.apache.maven.plugins:maven-install-plugin:2.4:install (default-install) on project microprofile-config-spec: Failed to install artifact org.eclipse.microprofile.config:microprofile-config-spec:pdf:1.2-SNAPSHOT: /Users/jeyvison/Documents/microprofile-config/spec/target/microprofile-config-spec.pdf (No such file or directory)`

Am i missing something ?

**Comment by Emily-Jiang** [comment]
I pulled in the latest code and it built cleanly in my local environment. Can you check again?

**Comment by jeyvison** [comment]
Working perfectly @Emily-Jiang , Thanks a lot :)
