### ISSUE TITLE
Replace the Hamcrest matchers with TestNG assertions.

### ISSUE THREAD

**Issue by mkouba** [eclipse/microprofile-config#261]
Tests that run in container mode (`@Deployment(testable = true)`) should add all the necessary classes to the test archive. E.g. [CDIPlainInjectionTest.java](https://github.com/eclipse/microprofile-config/blob/master/tck/src/main/java/org/eclipse/microprofile/config/tck/CDIPlainInjectionTest.java) must add all `org.hamcrest` imports used in the tests. The current version only works for embedded Arquillian containers. An Arquillian extension could be used as a workaround.

**Comment by smillidge** [comment]
This is definitely an issue we have to copy across the hamcrest jars to the remote server's classpath as part of our setup to run the TCK.

**Comment by johnament** [comment]
I disagree.  You should use an `ApplicationArchiveProcessor` if you need to add those dependencies.  In our case (GConfig) we actually manually build a JAR this way with Arquillian with the impl classes in it.

**Comment by mkouba** [comment]
@johnament That's IMO wrong. A test archive should always contain all classes under test and all the linked classes. In this case, there is a test that should run in container mode (test methods are invoked in container) but the test archive is missing `org.hamcrest.Matchers` which are not standard part of testng nor impl-specific classes. Arquillian extensions (e.g. `ApplicationArchiveProcessor`) should only be used to include _implementation-specific parts_.

**Comment by johnament** [comment]
@mkouba I'm going to repurpose this as "Replace Hamcrest matchers with TestNG matchers"
