### ISSUE TITLE
define a mapping rule from config property name to environment variable

### ISSUE THREAD

**Issue by Emily-Jiang** [eclipse/microprofile-config#264]
@Emily-Jiang commented on [Wed Nov 15 2017](https://github.com/eclipse/ConfigJSR/issues/24)

As the name of environment variable can only use alphabets and _ , it is difficult to override some config properties as environment variables.

e.g.
com.acme.me="blah"

This property cannot be specified as environment variable. How about to directly translate . to _ for the corresponding environment variables. 

com.acme.me -> com_acme_me
In this way, this property can be defined or override in environment variable.

---

@struberg commented on [Wed Nov 15 2017](https://github.com/eclipse/ConfigJSR/issues/24#issuecomment-344747644)

+1 to add it explicitly!

been there, done that 2 years ago ;) 

https://issues.apache.org/jira/browse/DELTASPIKE-1090
https://github.com/apache/deltaspike/blame/master/deltaspike/core/impl/src/main/java/org/apache/deltaspike/core/impl/config/EnvironmentPropertyConfigSource.java#L55

---

@kazumura commented on [Wed Nov 15 2017](https://github.com/eclipse/ConfigJSR/issues/24#issuecomment-344754084)

That means you cannot use '_' as a property key.

```
e.g.
 foo._bar
 foo_.bar
 foo..bar
 foo__bar

 Are all these same ?
```

I prefer to add a flag to specify auto converting or not.

---

@struberg commented on [Wed Nov 15 2017](https://github.com/eclipse/ConfigJSR/issues/24#issuecomment-344756004)

yes, you could not distinguish those in the EnvironmentConfigSource, but everywhere else. 
In practice it's not really an issue. 

We first catched this issue when integrating Docker where ENV=.. can also not contain any dots via scripts.

---

@kazumura commented on [Wed Nov 15 2017](https://github.com/eclipse/ConfigJSR/issues/24#issuecomment-344762543)

I agree the auto converting as the default behavior.

But there are some people who already use '_' as the keys.
My point is, should we provide them an option to use this feature or not?
I don't know how many people already use '_'. May not major.

---

@TFaga commented on [Wed Nov 15 2017](https://github.com/eclipse/ConfigJSR/issues/24#issuecomment-344763165)

+1 for `.` -> `_` as well. We're also doing this in KumuluzEE.

Another question though. How about other common characters that are used but not typically found or allowed in environemnt variable key names (like `-`, `[`, `]`, ...)? While there's not much that can be done about those examples, perhaps at least a note somewhere that certain characters may be problematic to use from the environment or that it's up to the implementation how it's additionally handled?

---

@Emily-Jiang commented on [Thu Nov 16 2017](https://github.com/eclipse/ConfigJSR/issues/24#issuecomment-344941445)

Yes, I think we should just pick the commonly used one like "." for the reason of @kazumura brought up, which will create overlapping. We can clearly document this as you said@TFaga !

---

@lilian-benoit commented on [Wed Nov 29 2017](https://github.com/eclipse/ConfigJSR/issues/24#issuecomment-347863524)

+1 for . -> _ as well.
Usually, we use _ for environment variable. 

is property name case-sensitive ? In fact, we have COM_ACME_ME as environment variable.

**Comment by OndrejM** [comment]
I suggest to require that environment variables with underscores are mapped to multiple keys. It should be a problem if e.g. a variable `COM_ACME_ME` represents all of these keys:

- `COM_ACME_ME`
- `com_acme_me`
- `com.acme.me`

All of them with the same value. There's almost no chance that an application would want to distinguish between these keys and would expect that there are different values under those keys.

**Comment by OndrejM** [comment]
If we want to support any character in the key, then we could specify a standard env variable prefix for variables which would hold both the key and the value as their value separated by a separator character, for example `=`.

For a prefix MP_CONFIG_ a variable MP_CONFIG_STRANGE_KEY could hold value `strange_key[1]=value1`, which would mean that the config key `strange_key[1]` contains value `value1`.

But I think it's fine to leave it implementation specific. In the end, everything can be specified by system properties when a JVM app is executed and implementations provide additional config sources. This doesn't affect application code so no need to specify if it's not a no brainer.

**Comment by jmesnil** [comment]
@Emily-Jiang Do you have a PR prepared for that?

I'm adding this feature to WildFly implementation (https://github.com/wildfly-extras/wildfly-microprofile-config/issues/36).
If you have nothing, I can work on a PR to update the spec and TCK to cover that case

**Comment by Emily-Jiang** [comment]
@jmesnil I have a work-in-progress PR but I think it might be better not to deliver as yet, as you know the current tck 1.1 needs to be enhanced. I am investigating how to do a micro release at the moment. I will get the PR out for tomorrow's call against config-jsr and then port back.

**Comment by smoyer64** [comment]
Dashes in Java property names are something else the mapping rule will have to consider (and are somewhat common in Java property names).  I've created https://github.com/eclipse/ConfigJSR/issues/53 since the microprofile-config team seems to be aligning this specification with the broader specification.

**Comment by smoyer64** [comment]
Dashes in Java property names are something else the mapping rule will have to consider (and are somewhat common in Java property names).  I've created https://github.com/eclipse/ConfigJSR/issues/53 since the microprofile-config team seems to be aligning this specification with the broader specification.
