### ISSUE TITLE
Overriding the ConfigProviderResolver doesn't work right

### ISSUE THREAD

**Issue by johnament** [eclipse/microprofile-config#265]
This issue isn't 100% consistent, and I'm seeing different behavior in a running app vs a unit test so I'm a bit miffed.  I first found this in Open API, see https://github.com/eclipse/microprofile-open-api/issues/80 and related PR https://github.com/eclipse/microprofile-open-api/pull/85

I'm not sure at this point if its an issue in other specs, but this unit test shows the problem.  If you've already called `getConfig()` (at least in some cases) you can cause the wrong config to be loaded after overriding the resolver.  I can get this to happen differently in a running app, where the value seems to have already been loaded without calling `getConfig()`, I'm guess its an oddity between how TestNG runs via Surefire and standalone apps.

**Comment by johnament** [comment]
No, I see it locally in a running app without calling `getConfig`.  I added that, as it was the only way to ensure that testng loaded that class first.

The problem happens when the static field is initialized before the `setInstance` is called.

**Comment by OndrejM** [comment]
I see, so the first step isn't caling `getConfig()` but when the `ConfigProvider` class is loaded by a classloader. A simple fix would be to refactor the initialization into the `getConfig()` method to so that the probem happens only in the scenario with calling `getConfig()`

**Comment by johnament** [comment]
I mirrored what you did in rest client (and what others did in their specs) in my config pr https://github.com/eclipse/microprofile-config/pull/266

**Comment by OndrejM** [comment]
The difference to the rest client is that `Config` is supposed to be a singleton while rest client is supposed to be always a new instance. That's why the methods are called `getConfig()` and `newBuilder()`

**Comment by OndrejM** [comment]
If we want to get config from the resolver every time `ConfigProvider.getConfig()` is called we have to ensure that the old config is properly released. The best way to do it is to keep the reference to it in the resolver so that all instances can be released when classloader is released. Currently, the spec expects a single Config instance per classloader.

**Comment by OndrejM** [comment]
Look at RestClientBuilderResolver.instance in REST client, this is how Config singleton should be retrieved from Config resolver in the `ConfigProvider.getConfig` method. This is a simple solution that fixes your problem when you don't call `getConfig` before `setInstance`.
