### ISSUE TITLE
Built in provider for Class types

### ISSUE THREAD

**Issue by johnament** [eclipse/microprofile-config#267]
This is needed in both the fault tolerance and the rest client specs.

There should be a built in way to convert `Class` objects (and likewise the `Class[]` class)

**Comment by OndrejM** [comment]
What is the scenario? Is it to enable specifying the class by it's name? As an example, the string value is "java.lang.String" and the converted value is `Class<String>`?

**Comment by OndrejM** [comment]
I guess that `Class[]` would be provided by #259 once both `Class` and `array` converters are provided.

**Comment by johnament** [comment]
@OndrejM yes, exactly that.  I would expect that it behaves like `Class.forName`, and that's likely the default implementation.
