### ISSUE TITLE
Where should microprofile-config.properties be located in a WAR file?

### ISSUE THREAD

**Issue by johnament** [eclipse/microprofile-config#268]
https://github.com/eclipse/microprofile-config/blob/master/spec/src/main/asciidoc/configsources.asciidoc#default-configsources mentions that the file should be on the classpath.

However, does this imply that the file is only read, while in a WAR file, from `WEB-INF/classes/META-INF`?  If so, can we add some TCK tests that check this?

**Comment by Emily-Jiang** [comment]
It is on the classpath. For WAR files, it will be under WEB-INF/classes/META-INF. +1 on adding tcks.
