### ISSUE TITLE
ArrayConverterTest is broken

### ISSUE THREAD

**Issue by johnament** [eclipse/microprofile-config#287]
The TCK test ArrayConverterTest is broken.  It assumes that a ProcessAnnotatedType is fired for fields in an Arquillian test, which is not the case.

**Comment by johnament** [comment]
I'm not sure if we have this with other new tests, but previously we set these fields on beans directly, instead of in the test class.

The formatting of this class is also a bit hard to read.

**Comment by Emily-Jiang** [comment]
@jmesnil ran the tests against his impl and the tests passed ok. This might have something to do with the arquillian integrator, maybe. Will you be able to do a PR to improve the tests?
