### ISSUE TITLE
TCK: expects mutable config sources

### ISSUE THREAD

**Issue by tomas-langer** [eclipse/microprofile-config#304]
There are TCK tests that expect system properties to be mutable in MP config. The specification does not state this is a requirement.
ConfigProviderTest.testDynamicValueInPropertyConfigSource()
ConfigProviderTest.testGetPropertyNames()
ConfigProviderTest.testPropertyConfigSource() (as a side effect of properties set during runtime of TCK)
EmptyValuesTest.testEmptyStringProgrammaticLookup()

1) there should be no requirement for the  system properties config source to be mutable
2) in general mutability of config is dangerous (e.g. if somebody changes 2 values and an application uses both of them, it could get first value from old version and second value from new version of config -> this creates inconsistencies that are really hard to troubleshoot)

**Comment by kenfinnigan** [comment]
Any update to this?

**Comment by dmlloyd** [comment]
This relates to #432.

**Comment by tomas-langer** [comment]
As far as I understand the updated specification, it now mandates that `Config` implementation never caches and must cycle through all config sources to obtain a value.

Although this seems like a major decision about an implementation and a risk (as I mentioned above - if a change happens, we may get data from two change sets), I think this issue can be closed.
