### ISSUE TITLE
TCK: inaccessible constructor used for converter test

### ISSUE THREAD

**Issue by tomas-langer** [eclipse/microprofile-config#305]
ImplicitConverterTest.testImplicitConverterStringCt() uses class ConvTestTypeWStringCt that has a package local constructor only.
This will be a problem with Java 9 and in general doesn't make sense - there is usually a reason that a constructor is hidden and we may cause trouble if we "magically" called it from config.
I think this constructor should be public (and the spec should probably mention that only public implicit converters should be used).

**Comment by tevans78** [comment]
Note that my PR only fixes the TCK and does not update the spec.
