### ISSUE TITLE
Static nested classes in TCK lead to ambiguous CDI resolution errors

### ISSUE THREAD

**Issue by heiko-braun** [eclipse/microprofile-config#307]
```
WELD-001409: Ambiguous dependencies for type ClassConverterBean with qualifiers @Default
--
at injection point [BackedAnnotatedField] @Inject private org.eclipse.microprofile.config.tck.ClassConverterTest.classConverterBean
at org.eclipse.microprofile.config.tck.ClassConverterTest.classConverterBean(ClassConverterTest.java:0)
Possible dependencies:
- Managed Bean [class org.eclipse.microprofile.config.tck.ClassConverterTest$ClassConverterBean] with qualifiers [@Any @Default],
- Managed Bean [class org.eclipse.microprofile.config.tck.ClassConverterTest$ClassConverterBean] with qualifiers [@Any @Default]
 
```

On both [1] and [2] the usage of static inner bean classes, that are added to `WEB-INF/lib` (see `@Deployment`) as well implicitly by arquillian, the TCK tests fail with an exception. 

The most simple fix would be to turn these bean classes into regular classes, like in the other tests.

[1] https://github.com/eclipse/microprofile-config/blob/master/tck/src/main/java/org/eclipse/microprofile/config/tck/ClassConverterTest.java

[2] https://github.com/eclipse/microprofile-config/blob/master/tck/src/main/java/org/eclipse/microprofile/config/tck/ImplicitConverterTest.java

**Comment by mkouba** [comment]
Just for clarification: 
- Arqullian automatically adds the test class to all testable archives which implement `ClassContainer` (see also https://github.com/arquillian/arquillian-core/blob/master/container/test-impl-base/src/main/java/org/jboss/arquillian/container/test/impl/client/deployment/DeploymentGenerator.java#L169-L171). 
- In case of `ClassConverterTest`, both `ClassConverterTest` and `ClassConverterTest$ClassConverterBean` are placed in `WEB-INF/classes` and `WEB-INF/lib/foo.jar` (note that this is considered a non-portable behavior - see also 12.1. Bean archives) 
- As a result Weld registers two beans for `ClassConverterTest$ClassConverterBean` and both satisfy `@Inject ClassConverterBean` -> ambiguous error

**Comment by Emily-Jiang** [comment]
@heiko-braun @mkouba will you be able to update your arquillian integration for Wildfly swarm to fix this?

**Comment by tevans78** [comment]
I opened an arquillian-core issue: arquillian/arquillian-core#157
