### ISSUE TITLE
TCK: ConfigProviderTest.testEnvironmentConfigSource() is not a reliable test

### ISSUE THREAD

**Issue by tevans78** [eclipse/microprofile-config#310]
`testEnvironmentConfigSource()` uses an injected Config which has default ConfigSources... i.e both Environment variables and System properties. The ordinal values of those default sources (300 & 400 respectively) mean that if a property exists as a system property it will mask the corresponding environment variable. For the most part those values tend to be the same but there is no guarantee and the method does not safely test the things it is supposed to.

A possible fix might be to only test those properties which are unique to the environment (i.e. not system properties) but it still doesn't feel like a good test. One would also have to do the opposite for `testPropertyConfigSource()`

Alternatively, it might be better to just test a single unique property ... but I'm not sure where the TCK could set a unique environment variable?

**Comment by Emily-Jiang** [comment]
We could remove the environment variables also existing as system properties in the testEnvironmentConfigSource()

**Comment by tevans78** [comment]
Note that while theoretically this problem could affect any property, the one which has highlighted the  problem is `sun.java.command`. The system property turned out to have a different value to the environment variable.

**Comment by tevans78** [comment]
On my local system, when the tck runs, there are 69 properties which are both an environment variable and a system property.

**Comment by hutchig** [comment]
This is also related to our discussion of the 'RAS' for a Config - particularly 'where is a value coming from/what is the 'winning' source for this value'. If this data had been available as a Config object 'dump', that we used when looking at the issue, it would probably have been a lot faster to determine why it was occurring.

**Comment by hutchig** [comment]
Should such a toString/dump feature of the Config object be implementation specific or part of the interface? @Emily-Jiang  @struberg ?
