### ISSUE TITLE
Create a test for Config.getPropertyNames

### ISSUE THREAD

**Issue by OndroMih** [eclipse/microprofile-config#315]
Add some tests that cover the method `Config.getPropertyNames`.

The method `getPropertyNames` on `Config` isn't covered by any test in the TCK. There's only test that covers a method of the same name on `ConfigSource`.

**Comment by Emily-Jiang** [comment]
We also need to figure out whether this method has real usage. If not, we should deprecate this and mark for removal in the future.

**Comment by dmlloyd** [comment]
We rely on it in Quarkus.

**Comment by Emily-Jiang** [comment]
close this one and use #431 to determine whether to keep this method. If yes, we will add tests. Otherwise, we will deprecate this. @dmlloyd please comment on #431 for your usage so that we can decide whether there is workaround.
