### ISSUE TITLE
Create a test for no defined config value

### ISSUE THREAD

**Issue by OndroMih** [eclipse/microprofile-config#319]
If:
  A value with no default value specified in `@ConfigProperty` and in no config source
When:
  Injecting the value using Optional
Then:
  value.orElse("Not defined") should give the value "Not defined"

An example code: https://github.com/payara/Payara-Examples/blob/27eda7b9da1eff4dbe2748ad03d0780c26bb1ba8/microprofile/config-injection/src/main/java/fish/payara/examples/microprofile/configinjection/ShowConfigValues.java#L303

**Comment by Emily-Jiang** [comment]
The answer is yes. We need to add a tck for this one.
