### ISSUE TITLE
dynamic handling of configured values

### ISSUE THREAD

**Issue by struberg** [eclipse/microprofile-config#320]
As discussed in the last MP steering hangout we gonna apply interesting stuff from ConfigJSR also to MP-config. The intention is to have people being able to play with it and give valuable feedback.

This ticket handles all the dynamic handling

https://github.com/eclipse/ConfigJSR/issues/9

PRs 
for 'push'
https://github.com/eclipse/ConfigJSR/pull/40
https://github.com/eclipse/ConfigJSR/pull/46 (basically the same while independently created by Tomas Langr)

for 'pull'
https://github.com/eclipse/ConfigJSR/pull/41

Gonna move them over and apply to master as discussed in our meeting

**Comment by Emily-Jiang** [comment]
@struberg can you stop commit your PR directly without being reviewed?

**Comment by struberg** [comment]
Emily, this was _explicitly_ acked in the mp meetings!

**Comment by Emily-Jiang** [comment]
@struberg I bet no one asked you to directly push your changes without being reviewed. Besides, you went ahead to disable the bnd plugin without asking why. This must be stopped in the future. I will discuss in the mailing list. We need to add a guard to the repos in the future.

**Comment by Emily-Jiang** [comment]
@kwsutter for your info. We need to find out from Eclipse how to stop a PR to be merged without being reviewed.

**Comment by OndrejM** [comment]
I agree with @Emily-Jiang - committing non-trivial things directly should be avoided. Instead, all should go through a PR. It's always possible to create a PR and merge it right away, but only if the change is trivial or nobody commented on the PR for a while.

**Comment by OndrejM** [comment]
I suggest reverting the commit and any other direct commits that bypassed a PR and raising a proper PR and allow a short discussion before it's merged.

**Comment by struberg** [comment]
calm down folks. That has been discussed in the MicroProfile steering meeting a month ago. I was asked twice to push the changes from the ConfigJSR also over to mp-config.

**Comment by Emily-Jiang** [comment]
@struberg I think you were asked to move changes. You can move the changes but it needs to be reviewed. However this changes are prematured though. After yesterday's meeting, I think we do need to revert it after all.

**Comment by Emily-Jiang** [comment]
We need to revisit this and rework the current commit.

**Comment by smillidge** [comment]
Where is the spec for this? Is this still scheduled for Config 1.3 or will this be pushed back as there is no spec or TCK to look at.

**Comment by struberg** [comment]
we had many discussions around it and while it looked like a no-brainer at the first glance it turned out to be way more complicated when digging deeper. 

See https://docs.google.com/document/d/1ixB3_Lu4Os__mw4_W5zlKspUE-lL3_h0asflewErlFY/edit?usp=sharing
point 6 and 7 from the meeting on 2018-03-15

Happy to push back the changes, but this is kind of the key feature for the upcoming mp-config release.

**Comment by struberg** [comment]
It was agreed to port the changes from the ConfigJSR back to mp-config. This was explicitly asked for in the mp steering meetings.

**Comment by smillidge** [comment]
OK I've asked Mike at Eclipse to clarify the IP flows as ConfigJSR is done under the JCP and therefore the JSPA.

**Comment by smillidge** [comment]
The Microprofile config TCK and spec will still need updates otherwise nobody can implement this without reading the Config JSR spec which is licensed differently.

**Comment by struberg** [comment]
@smillidge Both MicroProfile and the ConfigJSR JSR-382 are licensed under ALv2 for all 3 parts: API, spec PDF and TCK. 
But yes, the TCK needs some updates and we (both mp-config and ConfigJSR) need to think hard about the dynamic part again! Probably even do a 2h brainstorming session just about this very topic.

**Comment by smillidge** [comment]
OK the JCP proposal suggests otherwise for the spec https://www.jcp.org/en/jsr/detail?id=382 

```The specification will be licensed using the standard specification license (see http://jcp.org/aboutJava/communityprocess/speclead/final-license.txt). ```

**Comment by struberg** [comment]
Hmm, the JSR has clearly be filed as ALv2 and the License still says that https://github.com/eclipse/ConfigJSR/blob/master/spec/NOTICE
Anyway, _currently_ is all ALv2 so it's safe to pull over.

**Comment by OndrejM** [comment]
After reading the comments in the Config JSR issue, especially https://github.com/eclipse/ConfigJSR/issues/9#issuecomment-340735736, I tend to think that it would be better notify the application by some other way than config.

I mean, it would still make sense to add an option for Config Source to notify the container about changes. But Config shouldn't notify the application via a listener. Instead, a messaging mechanism outside Config API could be used. 

Although no messaging is available in MP yet, there's a proposal to add messaging API in the sandbox: https://github.com/eclipse/microprofile-sandbox/tree/master/proposals/streams

Maybe it's better to wait for the messaging API and then use it to publish config changes to the application.

**Comment by Emily-Jiang** [comment]
@OndrejM we don't have time to draw an conclusion on this issue. Hence, I have backed out the commits done by Mark and I have also excluded this in MP Config 1.3 release.
