### ISSUE TITLE
Remove some built in converter and swap the order of implict converter

### ISSUE THREAD

**Issue by Emily-Jiang** [eclipse/microprofile-config#325]
Since we have the notion of the implicit converter, it takes all classes with the following criteria:

<p>If no explicit Converter and no built-in Converter could be found for a certain type,

-  The target type {@code T} has a public Constructor with a String parameter, or
-  the target type {@code T} has a {@code public static T valueOf(String)} method, or
-  the target type {@code T} has a {@code public static T parse(CharSequence)} method

With this, all built in converters are not required to be listed as they either have valueOf or a constructor taking a String parameter. 

However, to improve the performance  (as valueOf has a cache facility while the constructor does not have) and take into the new JVM class method naming scheme, I suggest we update the search sequence for the implicit converter.
-  the target type {@code T} has a {@code public static T of(String)} method
-  the target type {@code T} has a {@code public static T valueOf(String)} method, or
- The target type {@code T} has a public Constructor with a String parameter, or
-  the target type {@code T} has a {@code public static T parse(CharSequence)} method

We can then remove the section of built-in converters.

**Comment by tevans78** [comment]
We can't remove all of the built-in converters;

`Boolean(String)` only accepts `true`; not `yes`, `y`, `on` or `1`

The `java.time.*` classes throw `DateTimeParseException` from their `parse(CharSequence)` methods; according to the current spec, we need to catch and rethrow as `IllegalArgumentException`

`URL(String)` throws `MalformedURLException`

The Class converter would also have to remain as it is a very special case, requiring a ClassLoader as well.
