### ISSUE TITLE
Consider adding <links>

### ISSUE THREAD

**Issue by ljnelson** [eclipse/microprofile-config#331]
Regarding https://github.com/eclipse/microprofile-config/blob/a864099be3484e9f1062c5033a3852b2eec5800c/pom.xml#L27:

Consider adding a `<links>` property, so that the `maven-javadoc-plugin`-generated documentation will link to appropriate pages (such as, for example, OSGi's annotation javadocs).

Sample content:

    <links>https://osgi.org/javadoc/r6/annotation/</links>

Reference: https://maven.apache.org/plugins/maven-javadoc-plugin/javadoc-mojo.html#links (note the **User Property** item)

PR forthcoming when I get around to it :smile:

**Comment by Emily-Jiang** [comment]
@ljnelson are you going to do a PR soon?

**Comment by ljnelson** [comment]
Thanks for the nudge.  May get to it later today.

**Comment by ljnelson** [comment]
Done: https://github.com/eclipse/microprofile-config/pull/351
