### ISSUE TITLE
Standardize support for MP Config in EL

### ISSUE THREAD

**Issue by arjantijms** [eclipse/microprofile-config#332]
It's often handy to be able to use MP config in EL expressions, but currently this is not supported out of the box.

EL support can be added in a variety of ways, for instance by defining an implicit object (provided CDI bean with a default name), via a custom EL resolver, or by statically importing `ConfigProvider` (getELContext().getImportHandler().importClass(...)).

Maybe the implicit object is the easiest way and also allows for better namespacing. 

An example of using MP Config in EL would be in the yet to be defined annotation to install JWT authentication:

```java
@JWTConfig(
    issuer = "#{microprofile.config['my.accepted.issuer']}"
)
```

Here the main implicit object is `microprofile`, which serves as a namespace as well as an access point to potentially other microprofile services. 

`config` would be a Map here that essentially wraps `ConfigProvider.getConfig()` and only supports a few operations. There's a few additional options that could be explored, for instance use method expressions, where the backing code can automatically pass in the class type for the `getValue(String propertyName, Class<T> propertyType)` call, based on the type of the EL expression (if known).

As another example, existing MP Annotations could be extended with EL enabled attributes, so they can use a more elaborate pull style config in addition to the existing config methods that override globally or per service, to e.g. config per group of services:

```java
@CircuitBreaker(
    successThreshold = 10, 
    requestVolumeThreshold = 4, 
    failureRatio=0.75, 
    delayExpression = "#{microprofile.config['com.example.groupx.delay']}")
public Connection serviceA() {}
```

Yet another example is on Facelets templates:

```xml
<h:panelGroup rendered="#{microprofile.config['app.featureX.enabled']}">
    <!-- Some markup here -->
</h:panelGroup>
```

**Comment by struberg** [comment]
Yikes, have a bad feeling. Could open us up for security issues. We should think twice if we would like to go down that route.

Note that IF you need something in e.g. JSF, you could already just have a CDI bean which resolves the value and reference this via @Named

**Comment by arjantijms** [comment]
@struberg What would these security issues be, then?

Do you mean that an EL expression itself could be provided externally then?

This is not quite the case, even though it may seem so.

The interceptor that grabs the value from either the annotation or MP Config is in control. So the spec would simply say that values obtained from the MP Config should **not** be allowed to be passed into the EL Processor, and those from the annotation are.

E.g. in pseudo code in an interceptor:

```
Val value = ConfigProvider.config.getValue(....);
if (value != null) {
   Annotation annotation = getInterceptorBindingAnnotation(...);
   value = elProcessor.eval(annotation.value);
}
```

So the ElProcessor is only ever invoked with the EL expression that's hardcode in the annotation, which is ours.

>Note that IF you need something in e.g. JSF, you could already just have a CDI bean which resolves the value and reference this via @Named

You can, but that's at the application level. You'd have to ask users to create such a bean for every application, which can be done, of course, but is boilerplate compared to the spec providing it for them.

**Comment by OndrejM** [comment]
I agree that having a standard named object to access configuration from an EL is useful. Especially to access configuration in templates (JSF, facelets, etc.)

But I don't think that having support for ELs in annotation values is the best solution to have scriptable configuration for interceptors. 2 reasons:
- each field in the annotation would have to be doubled to accept EL instead of a value (this wouldn't have to be done for fields of type String but definitely for other types like int)
- it's better to use Java code in Java code rather than uncompiled and untyped EL

I suggest to evaluate a different approach to provide some logic to the configuration, e.g. by supplying another class that would provide methods to configure them, e.g.:

```
@CircuitBreaker(
    successThreshold = 10, 
    configProvider = MyCustomConfigProvider.class
)

@Dependent
class MyCustomConfigProvider  {
    @Inject Config config;
    
    void configure(CircuitBreakerBuilder builder) {
        builder.setDelay(config.getValue("com.example.groupx.delay", Integer.class));
    }
}

**Comment by arjantijms** [comment]
The alternatives for non-String attributes are indeed a compromise, but lacking an expression language or lambdas that can be directly used for an annotation attribute, all other approaches compromise in some way.

EL has the alternative attributes for non-string ones, which is not so bad if there are mostly strings, but otherwise does indeed add some overhead.

Making values primarily dynamic by adding the fully qualified class name to some config file somewhere doesn't feel like the ultimate best solution either. It strongly brings back memories of defining managed beans in faces-config.xml, ejb-jar.xml etc. The config expression (not the config value it self) is far away from the code, which has proven time again is something people struggle with. As an escape hatch override it's cool to have this, but as the primary mechanism... I'm not convinced.

The config provider is another compromise, since it too requires another attribute which can feel somewhat awkward when there's only 1 original attribute, and you don't see directly which things are configured. I do like it though and I proposed something quite identical before ;)

Note that Java EE has the notion of EL in attributes:

> For all attributes of type String on these annotations, Expression Language 3.0 expressions can be used. All named CDI beans are available to that expression, as well as the default classes as specified by EL 3.0 for the ELProcessor.
> Expressions can be either immediate (${} syntax), or deferred (#{} syntax). Immediate expressions are evaluated once when the bean instance corresponding to the "...Definition" annotation is actually created. Since such beans are application scoped, that means once for the entire application. Deferred expressions are evaluated in each request where the security runtime needs to use the value of these attributes.
> 
> Attributes that are documented as being EL alternatives to non-String type attributes (attributes for which the name ends with Expression, hereafter called EL alternative attribute) MUST evaluate to the same type as the attribute they are an alternative to. If the EL alternative attribute has a non empty value, it takes precedence over the attribute which it is an alternative to.
> 
> The EL alternative attribute MUST contain a valid EL expression. Attributes of type string that are not EL alternative attributes can contain either an expression or a string value that is not an expression.

See https://javaee.github.io/javaee-spec/javadocs/javax/security/enterprise/package-summary.html

So one reason to go with EL in attributes would be for consistency.

**Comment by arjantijms** [comment]
@struberg Already any idea what the potential security issue could be here?

**Comment by Emily-Jiang** [comment]
Since MP has excluded EL, I think we should close this feature request till EL is back to MP.
