### ISSUE TITLE
ConfigBuilder.addDefaultConverters method to go along with addDefaultSources?

### ISSUE THREAD

**Issue by dstutz** [eclipse/microprofile-config#335]
I am trying to integrate MP config into an application running on Payara 4.1.2.181, which uses MP config 1.1.  I initially created a simple ConfigSource that used our database.  I added my class name to the /META-INF/services/org.eclipse.microprofile.config.spi.ConfigSource and while it loaded my source, there was no injection available to inject the EntityManager I assume since the class is loaded by the ServiceLoader mechanism and is not a managed object.  I tried several hacks like trying to get the BeanManager from JNDI but that never worked.  
So then I moved on to using the ConfigBuilder and I call "addDefaultSources" which gives me 12 on Payara and then follow up with "withSources(mysource)" and it adds my custom source.  Now I have a Config object.  I tried to read a Boolean value and it tells me there is no BooleanConverter.  If I inspect the Builder and the resulting Config object I can see there are no converters but if I use ConfigProvider.getConfig() to create the Config object then that object has 15 default converters.  Calling ConfigBuilder.addDiscoveredConverters() didn't add anything to my builder/Config.

Is there a way around getting injection in my autoloaded ConfigSource or a way to get the default converters loaded when I'm "building" a Config such as adding a method along the lines of the issue title?

**Comment by Emily-Jiang** [comment]
This looks to be implementation related issue. Need to double check tck to make sure the config created by ConfigBuilder has the default converted associated with.

**Comment by Emily-Jiang** [comment]
need to clarify in javadoc.

**Comment by smillidge** [comment]
I don't think this is an implementation issue but a spec issue. Given the addDefaultSources method why isn't there an addDefaultConverters method?

**Comment by dstutz** [comment]
"All default converters will be added automatically"  

Is that supposed to happen in all cases?  When I used ConfigBuilder I'm not getting any converters.

**Comment by smillidge** [comment]
Where is this documented or tested? This means there is a specification bug and a TCK testing bug. We can easily fix our implementation to make this happen but it is not specified.

**Comment by Emily-Jiang** [comment]
will clarify the spec and add tck for this.

**Comment by Emily-Jiang** [comment]
fixed under #348
