### ISSUE TITLE
Broken URI test uses a value which is not an invalid URI String

### ISSUE THREAD

**Issue by tevans78** [eclipse/microprofile-config#344]
https://github.com/eclipse/microprofile-config/blob/dd4e5c8d64a4e15245cccb5dcf4a85b94cb917fe/tck/src/main/java/org/eclipse/microprofile/config/tck/ConverterTest.java#L366

The test re-uses a property from the broken URL test...
```
tck.config.test.javaconfig.converter.urlvalue.broken=tt:--location
```

That is an invalid URL but is not an invalid URI.

**Comment by Emily-Jiang** [comment]
@tevans78 can you do a PR? thanks
