### ISSUE TITLE
Build from master branch fails with unresolvable build extension

### ISSUE THREAD

**Issue by ljnelson** [eclipse/microprofile-config#350]
Following the README instructions, if I check out microprofile-config (and nothing else) and do:

    mvn clean install

I get the following error:

```
LANELSON$ mvn clean install site
[INFO] Scanning for projects...
Downloading: http://localhost:8081/repository/maven-public/org/eclipse/microprofile/maven/microprofile-maven-build-extension/maven-metadata.xml
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[WARNING] 'build.plugins.plugin.version' for org.eclipse.microprofile.maven:microprofile-maven-build-extension is missing. @ line 183, column 21
[ERROR] Unresolveable build extension: Error resolving version for plugin 'org.eclipse.microprofile.maven:microprofile-maven-build-extension' from the repositories [local (/Users/LANELSON/.m2/repository), nexus (http://localhost:8081/repository/maven-public/)]: Plugin not found in any plugin repository @ 
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
```

Usually of course this means I don't have a relevant `<pluginRepository>` in my `.m2/settings.xml`.  I'm guessing that such information should show up in the `README`.

**Comment by ljnelson** [comment]
Looks like this needs to be in the mix: https://repo.eclipse.org/content/repositories/eclipse-releases/

**Comment by Emily-Jiang** [comment]
@ljnelson We looked at this during our weekly hangout. We cannot recreate your problem. Can you rename/delete your .m2 and do `mvn clean install` again?

**Comment by Emily-Jiang** [comment]
@struberg said @OndrejM might need to confirm whether this plugin is still needed. @OndrejM can you confirm whether this plugin can be deleted?

**Comment by ljnelson** [comment]
I run Nexus locally so I'll also need to recreate my Nexus configuration.  When I have time after my real job I'll try to do this.  (Please note it was a pretty clean install to start with; should be relatively easy to ask Maven if indeed that plugin is needed, and to verify that indeed that plugin is not available from Maven central.)

**Comment by jmesnil** [comment]
@ljnelson is it still relevant?

**Comment by ljnelson** [comment]
Yes, this is still relevant.  Without a plugin repository from which the `microprofile-maven-build-extension` may be downloaded, the build does not complete.

**Comment by Emily-Jiang** [comment]
This issue is pretty old and we cannot replicate this. I think this is to do with your setting. I am going to close this for now. Please reopen it if you think you still cannot build it. You might want to upgrade your mvn to try again.
