### ISSUE TITLE
Case sensitivity of environment variables in TCK CDIPropertyNameMatchingTest

### ISSUE THREAD

**Issue by neilgsyoung** [eclipse/microprofile-config#358]
CDIPropertyNameMatchingTest assumes that the environment in which the TCK runs is case sensitive. In particular, the assumption is that my_string_property and MY_STRING_PROPERTY may be configured as distinct variables. This is not the case on, for example, Windows.

The test should be reworked to tolerate case insensitive environments.

**Comment by jmesnil** [comment]
we can split this test in 2.

* one simple test that checks the mapping rule without any case conversion
* another test that checks with case conversion. In this 2nd case, we can them use JUnit assume to check it is not run on Windows.

**Comment by neilgsyoung** [comment]
@jmesnil and @Emily-Jiang, I believe the test in its current form will run cross-platform. I'm happy to tackle @jmesnil's suggestion but how about I open a new issue and we do it the other side of RC4?

**Comment by Emily-Jiang** [comment]
I double checked and found out #361 fixed this issue properly. Close this issue and move out of the milestone as it was fixed before MP Config 1.3.
