### ISSUE TITLE
Support config files in WEB-INF for a WAR file

### ISSUE THREAD

**Issue by OndroMih** [eclipse/microprofile-config#362]
As clarified in #268 the current spec mandates that in a WAR file, the `microprofile-config.properties` should be located in `WEB-INF/classes/META-INF/microprofile-config.properties`. This isn't very intuitive and it's easy to make a mistake by placing the file into `WEB-INF` like `beans.xml` in CDI.

I suggest supporting an alternative location for `microprofile-config.properties` in `WEB-INF`, with higher priority than the current location.

Note: Another source of confusion is in teh OpenAPI spec (https://github.com/eclipse/microprofile-open-api/issues/217) which requires that `microprofile-config.properties` can be located also in the top-level `META-INF` directory next to the `WEB-INF` directory. It's probably best supporting all of these locations so that users don't have to think about it too much because it's easy to make a mistake and put the file in a wrong location.

**Comment by Emily-Jiang** [comment]
@OndrejM, @struberg and I defined this way to avoid the conflict if someone places the microprofile-config.properties under WEB-INF and also another conflicting file under WEB-INF\classes\META-INF\. They need to remember the priority. Both Mark and I agreed that it was a mistake done by CDI. Config should not follow that path. @danielsoro shows the same view in today's hangout.
