### ISSUE TITLE
[Clarification] Keys in custom annotations

### ISSUE THREAD

**Issue by Cousjava** [eclipse/microprofile-config#363]
When creating a custom annotation that will work with MP Config, should the value in the annotation be a key that is defined elsewhere or should the key be pre-defined?

i.e.
`@NewAnnotation("foo")`
microprofile-config.properties:
`foo=bar`
or
```
/**
 Mp Config Key is com.example.newannotation
*/
@NewAnnotation
```
microprofile-config.properties:
`com.example.newannotation=bar`

**Comment by Emily-Jiang** [comment]
@danielsoro and I discussed in today's hangout. We are not sure what you would like to achieve. Can you define your use case in more details?

**Comment by Emily-Jiang** [comment]
This ticket has been opened for a while and no further replies toward the use case question. I'm closing this for now. Please reopen and provide more info if you would like to proceed @Cousjava !
