### ISSUE TITLE
osgi dependency should be optional in the api

### ISSUE THREAD

**Issue by rmannibucau** [eclipse/microprofile-config#368]
Hi,

the api depends on 

    <groupId>org.osgi</groupId>
    <artifactId>org.osgi.annotation.versioning</artifactId>

This can be set as provided and avoids all not OSGi environments to import it for nothing.

**Comment by Emily-Jiang** [comment]
Agreed. thanks @rmannibucau !

**Comment by Ravisankar-Challa** [comment]
org.osgi.annotation.versioning is there in all the micro-profile specs. Will this be changed to provided in all specs?

**Comment by rmannibucau** [comment]
+1 to make it a general rule
