### ISSUE TITLE
ArtifactId should match module / repo name

### ISSUE THREAD

**Issue by keilw** [eclipse/microprofile-config#37]
Right now there's `microprofile-config` but the artifactId for the parent POM is defined as `microprofile.config.parent`.
While dots as separators are quite common especially under Eclipse, see https://github.com/eclipse/rt.equinox.framework, the artifactId should match the module or repository name wherever possible.
So either `microprofile.config.parent` in a repo `microprofile.config` or an artifactId  `microprofile-config` in the existing name pattern.

**Comment by emilyjiang** [comment]
Mark and I discussed this. Since this artificateId is used for the jar file name, it should not contain a dot in the name.

**Comment by keilw** [comment]
That is not the case for almost every Eclipse project. Take "org.eclipse.debug.core" and that isn't even the one with most dots ;-) However if all of Microprofile agreed to follow some convention without dots in artifactIds, I guess it would be OK do do so, but it should be consistent across every module and subproject.

**Comment by struberg** [comment]
Eclipse must follow Maven convention if we want to use Apache Maven and maven.central.

**Comment by keilw** [comment]
Sorry but did you ever look at MavenCentral? ;-)
http://jcenter.bintray.com/org/eclipse/jdt/org.eclipse.jdt.annotation/1.1.0/
	<groupId>org.eclipse.jdt</groupId>
	<artifactId>org.eclipse.jdt.annotation</artifactId>
And thousands of other Eclipse/OSGi bundles are there.

**Comment by keilw** [comment]
Even on Windows a JAR file can have more than one dot these days, maybe it was a problem for Windows 95 or 98 ;-)

**Comment by Emily-Jiang** [comment]
That is true. I see the maven central has two styles: using dot or dash. Even for eclipse projects, some use dot while other use dash. I don't mind either dot or dash. We just need to be consistent among all microprofile projects.

**Comment by struberg** [comment]
+1 for consistency.

There are technically 3 main options

1. dots: microprofile.config_1.0.jar
2. dash: microprofile-config_1.0.jar
3. underline: microprofile_config_1.0.jar 

Let's just do a vote.

+1 for option 2.

**Comment by Emily-Jiang** [comment]
+1 for option 1. option 2 will be fine as well. I would leave option 3 out.
@keilw you were quite right. What I typed in the first place was incorrect. Too tired to write properly. I have thousands of jars like that laying around.

**Comment by keilw** [comment]
It should be consistent across Microprofile, otherwise it'll get confusing. So that in the right place should be done in a more central place, not just for a single groupId/Module.

**Comment by OndrejM** [comment]
+1 for option 2
+1 for consistency

Dash is also used in GitHub repository names. Dots would be confusing, as they are used as separators in group names, but artifact name is not separable. We can have artifact group org.eclipse.microprofile.config and artifact name microprofile-config, at least that's what feels natural to me.

**Comment by starksm64** [comment]
+1 for option 2, use of dashes as the separator.

**Comment by keilw** [comment]
I'm neutral between 1 and 2. Knowing the OSGi world (and especially IBM also everywhere including Java EE related things like MQ) uses 1, but in other areas 2 is most common. I would hope a wider consensus can be found in a place like https://github.com/eclipse/microprofile

**Comment by gunnarmorling** [comment]
Why using underscores as separator? Hardly ever seeing that out there.

I'd use _microprofile-config-1.0.0.Final.jar_:

* three digits so we can do bugfix releases like 1.0.1
* an "Alpha", "Beta", "CR", "Final" suffix to have preview releases which can be nicely sorted. That's the convention we have in Hibernate (and other JBoss) projects and it's working very well.

**Comment by atsticks** [comment]
+1 for option 2: bar-foo_VERSION.jar

**Comment by keilw** [comment]
We don't have to exactly stick to a particular vendor's conventions on postfixes like "CR". "GA" or similar, but I'd stick to standard Maven conventions. If there's an underscore then usually as qualifier e.g. for a timestamp of OSGi bundles, otherwise it is not common.

**Comment by Emily-Jiang** [comment]
I looked at the maven central. It seems xx-xx-version.jar style is popular. Anyway, this is only file name.  In OSGi, bundle symbolic name and version are the ones matters. I am happy to use what Gunnar suggested microprofile-config-1.0.0.Final.jar. Any objections?

**Comment by keilw** [comment]
Although the underscore is pretty common when you build OSGi bundles with Tycho or similar (just check any "plugins" folder of an Eclipse based distro) the likes of Spring and others are pretty used to "1.1.1.RELEASE" or something else at the end, so it sounds OK to me.

**Comment by struberg** [comment]
Any postfix like .Final .RELEASE or something else creates problems in practice. 
It is not a out-of-the-box supported Maven versions schema and e.g messes up maven-versions-plugin in my experience.
I'd rather stick with a simple n.n.n version e.g. 1.0.0.

**Comment by keilw** [comment]
I have no problem with that either. It's vendors (Pivotal, Red Hat and others) that seem so like that kind of postfix ;-)

**Comment by OndrejM** [comment]
+1 for plain 1.0.0, like microprofile-config-1.0.0.jar
RC, milestones or anything similar should rather go into a snapshot repo

**Comment by gunnarmorling** [comment]
> Any postfix like .Final .RELEASE or something else creates problems in practice.

Details?

It's a common convention used by a plethora of JBoss projects, Spring etc. We're using the versions plug-in with that all the time, I'm aware of no issues.

We also can use 1.0.0 for the final and add a qualifier only for non-final releases (also like 1.0.0-beta1 if you prefer). Though I'd prefer to consistently use it, as it's the easiest for people to remember and use. Suprised you are having problems with it tbh.

> RC, milestones or anything similar should rather go into a snapshot repo

Uff, no. It's a pain for people to configure (need another repo than Central) and it's not reproducable. Reproducing bugs from preview releases would be a nightmare.

**Comment by struberg** [comment]
Maven uses numbers between dots. If it is not be converted to a number then it does string sort.
So .alpha comes before .beta but .RC  (Release Candidate) is **higher** than .Final in terms of Maven version handling. 

I know we (Maven) tried to add a few special hacks for a few 'known' postfixes, but I don't think we came far with it.

Just think about -MR. Some people use this abbreviation for 'Maintenance Release' (means after a proper final release) where others use it for 'Milestone Release' (so _before_ any proper final release). That's nasty ^^

**Comment by struberg** [comment]
Btw, this question will not bring the sky down. It's really a minor question. Worth to discuss, but not worth to fight for. We can technically live with any of those options. There are just minor pros and cons on each side.

**Comment by OndrejM** [comment]
Thank you, @struberg, for explaining cons of version suffixes. If there are any pros to using them, I'd like to know, but otherwise I prefer keeping the version number simple, without any suffix. I think final versions without any suffix is by far most frequently used across artifacts in maven central (jetty, tomcat, log4j, junit, ...) Sometimes I saw both GA and Final with the same artifact, which is super confusing.

**Comment by gunnarmorling** [comment]
> So .alpha comes before .beta but .RC (Release Candidate) is higher than

Sure, which is exactly why we use Alpha, Beta, CR and Final.

> There are just minor pros and cons on each side.

True; what I find not helpful though is hand-waving statements such as "creates problems" without any details and despite that scheme being in wide-spread use.

**Comment by Emily-Jiang** [comment]
With my OSGi cap on, as for the bundle version, it has four parts major.minor.micro.qualifier. Since version can be compared, the major, minor and micro follow number comparisionwhile qualifier can be strings, which will follow string comparison (alpha<beta<Final). When we say the number scheme of major.minor.micro.qualifier (microprofile-config-1.0.0.Final.jar), this is the final release. For an alpha release, we have microprofile-config-1.0.0.alpha.jar, which is smaller than microprofile-config-1.0.0.Final. At least, we can differentiate the different stages of the releases.

**Comment by struberg** [comment]
Back to the original issue description:
The artifactId effectively becomes the jar name in the end. So changing the artifactId to the module name, e.g. "api" will result in an api.jar file. I think we do all agree that this does not make sense, right?

**Comment by keilw** [comment]
There's been a consensus on using the "sub-module" aka "config" by several contributors here https://groups.google.com/forum/?hl=en#!searchin/microprofile/groupid|sort:relevance/microprofile/tPoOrdSJffw/bcBZ6OUECwAJ including @OndrejM
