### ISSUE TITLE
Clarify and add test for injected collections without configured and default values

### ISSUE THREAD

**Issue by jmesnil** [eclipse/microprofile-config#376]
What is the expected behaviour for injected collections or arrays that are not configured and provide no default value, e.g.

```
@Inject
@ConfigProperty(name = "myPets")
private String[] myArrayPets;

@Inject
@ConfigProperty(name = "myPets")
private List<String> myListPets;

@Inject
@ConfigProperty(name = "myPets")
private Set<String> mySetPets;
```

The specification and TCK does not specify the expected behaviour for that case.

We have 2 different possibilities:
1. Throw a `DeploymentException` as the properties are not *correct* (no configuration and no default values)
2. Inject them with empty collection

(1) is consistent with any other injected type but (2) seems more intuitive.

If we clarify to (1), the application should use an empty string `""` as the `defaultValue` to support empty collection.
If we clarify to (2), the application does not have to specify anything more but it can no longer distinguish between unconfigured property and default empty collection.

What do you think?

**Comment by jmesnil** [comment]
Personally, I'd vote for (2) as it simplifies the code (using `defaultValue=""` to get an empty collection is not straightforward).
Besides, if the application is expecting non-empty collections, it can assert that in the code.

**Comment by svenhaag** [comment]
I vote for (2) empty collections too.  Everything else screams for NPEs and makes no semantical sense to me. Cheers.

**Comment by svenhaag** [comment]
It should also be clarified if the collection contains null values if the config value e.g. contains 2 commas in a row. I would prefer to omit null values.

**Comment by radcortez** [comment]
#598 will resolve this.
