### ISSUE TITLE
Propose to change the logic for implicit converters

### ISSUE THREAD

**Issue by Emily-Jiang** [eclipse/microprofile-config#383]
At the moment:
However, to improve the performance (as valueOf has a cache facility while the constructor does not have) and take into the new JVM class method naming scheme, I suggest we update the search sequence for the implicit converter.

    the target type {@code T} has a {@code public static T of(String)} method
    the target type {@code T} has a {@code public static T valueOf(String)} method, or
    The target type {@code T} has a public Constructor with a String parameter, or
    the target type {@code T} has a {@code public static T parse(CharSequence)} method
It is better to move the constructor to the bottom of the list so that all static methods have higher priority than the constructor.

**Comment by struberg** [comment]
We had a vote over at https://github.com/eclipse/ConfigJSR/issues/86 and there seems to be a majority of votes for option B. I'd love to take the arguments from over there into consideration.
We gonna talk about this on thursday in our EG meeting and nail it down.

**Comment by struberg** [comment]
The vote got tallied yesterday in our weekly ConfigJSR EG meeting and it was decided to use option B.
```
   * the target type {@code T} has a {@code static T of(String)} method, or
   * the target type {@code T} has a {@code static T of(CharSequence)} method, or
   * the target type {@code T} has a {@code static T valueOf(String)} method, or
   * the target type {@code T} has a {@code static T valueOf(CharSequence)} method, or
   * the target type {@code T} has a {@code static T parse(String)} method, or
   * the target type {@code T} has a {@code static T parse(CharSequence)} method, or
   * the target type {@code T} has a Constructor with a String parameter, or
   * the target type {@code T} has a Constructor with a CharSequence parameter
```

**Comment by jmesnil** [comment]
Is it still relevant?

**Comment by dmlloyd** [comment]
It was agreed to make this change on the call last week.
