### ISSUE TITLE
Backport ConfigAccessor and ConfigSnapshot from ConfigJSR

### ISSUE THREAD

**Issue by struberg** [eclipse/microprofile-config#384]
ConfigJSR introduce a few advanced features for handling dynamic values. 
See the discussions over here 
https://github.com/eclipse/ConfigJSR/issues/9
and
https://github.com/eclipse/ConfigJSR/issues/8

**Comment by jmesnil** [comment]
@struberg is it still relevant? ConfigAccessor is already in the code base?
