### ISSUE TITLE
ConfigProperty.UNCONFIGURED_VALUE should have it's typo restored

### ISSUE THREAD

**Issue by tevans78** [eclipse/microprofile-config#389]
All versions of MP Config released so far have had a typo in the value of  ConfigProperty.UNCONFIGURED_VALUE: _org.eclipse.microprofile.config.configproperty.unconfigured_**d**_value_

This typo was "fixed" at some point since 1.3. However, this is actually a breaking change since String constant values may be inlined at compile time. Any older code which was compiled against 1.3 or earlier would no longer be compatible with the "fixed" code.

Although one option would be to make the next version 2.0 rather than 1.4, that seems like overkill to me. Easier just to put the typo back, it doesn't hurt anything by being there.

https://github.com/eclipse/microprofile-config/blob/5c29d64e7eac30b595a1e1f08cbe54bd48ea00b0/api/src/main/java/org/eclipse/microprofile/config/inject/ConfigProperty.java#L104

**Comment by derekm** [comment]
MicroProfile leads need to get better about exactly respecting Semantic Versioning and closely understanding when they're introducing breaking changes.

The best approach is to do both 1.4 & 2.0: carry the 1.3 change in 2.0 and restore the 1.x API in 1.4.

**Comment by Emily-Jiang** [comment]
I think this typo change does not gain much value but introduced backward incompatibility. Let's revert the changes. I don't understand why bnd-sementic-versioning plugin did not complain.

**Comment by Emily-Jiang** [comment]
To address @derekm comments, the typo change is not backward compatibility changes. Please see JVM chapter 13 backward incompatibility 
If a field is a constant variable (§4.12.4), then deleting the keyword final or changing its value will not break compatibility with pre-existing binaries by causing them not to run, but they will not see any new value for the usage of the field unless they are recompiled. This is true even if the usage itself is not a compile-time constant expression (§15.28). 

However, it is a behavior change as explained earlier. Hence why the bnd versioning plugin did not spot it. Let's revert the typo change update.

**Comment by Emily-Jiang** [comment]
I have reverted the changes under https://github.com/eclipse/microprofile-config/pull/391.
