### ISSUE TITLE
Conflicts on default config source ordinal

### ISSUE THREAD

**Issue by gaol** [eclipse/microprofile-config#394]
https://github.com/eclipse/microprofile-config/blob/4611c9433675e34ee73bd1eba026e01631582772/api/src/main/java/org/eclipse/microprofile/config/package-info.java#L44-L45
https://github.com/eclipse/microprofile-config/blob/4611c9433675e34ee73bd1eba026e01631582772/api/src/main/java/org/eclipse/microprofile/config/spi/ConfigSource.java#L44-L45

The default `ConfigSource` ordinal `400` and `300` and defined differently in above 2 places.

**Comment by Emily-Jiang** [comment]
oops. The javadoc in the package-info is wrong. will fix it soon. Thanks for reporting this!

**Comment by dmlloyd** [comment]
This is still wrong AFAICT
