### ISSUE TITLE
Standardize a convention for using MP Config to override annotation attributes?

### ISSUE THREAD

**Issue by njr-11** [eclipse/microprofile-config#400]
MicroProfile Fault Tolerance already defines a way to use MicroProfile Config to override annotation values,
https://download.eclipse.org/microprofile/microprofile-fault-tolerance-2.0/microprofile-fault-tolerance-spec.html#configuration 

MicroProfile Concurrency very nearly introduced a slightly different way of doing the same thing for override of its own config annotations, but having discovered the FaultTolerance approach, is now switching to align with the FaultTolerance approach so that MicroProfile specs can be consistent.

It would be helpful if MicroProfile Config spec itself defined the convention, because that is where new specifications will look before coming up with their own approaches.

**Comment by FroMage** [comment]
Very good idea!

**Comment by Emily-Jiang** [comment]
Let's discuss this in this week's hangout

**Comment by njr-11** [comment]
Closing because this issue has been taken up by MicroProfile in general, and is being tracked under the following issue instead under the general MicroProfile repository:
https://github.com/eclipse/microprofile/issues/98
