### ISSUE TITLE
Clarify if @ConfigProperty injected values are bean passivating enabled.

### ISSUE THREAD

**Issue by rdebusscher** [eclipse/microprofile-config#404]
There is not much info in the specification around the fact if an injected `@ConfigProperty` is passivating enabled or not.

For example

    @Inject
    @ConfigProperty(name = "config.foo.value")
    private String value;

Will fail upon deployment in some runtimes when it it used in a passivating scoped bean like `SessionScoped`.

There is only a mentioning about the Provider variant
    
     Instances of Provider<T> are guaranteed to be Serializable.

So we should mention the restrictions of using `@ConfigProperty` in a passivating scoped bean.

**Comment by Emily-Jiang** [comment]
I prefer not to add this info into the spec. Please comment if you think otherwise.

**Comment by ljnelson** [comment]
I think the issue here is (if I'm reading it right): using `@ConfigProperty` in any bean prevents that bean from being passivated.  That means no bean can be passivated if it uses MicroProfile Config.  That seems important to call out.

**Comment by Emily-Jiang** [comment]
Using `@ConfigProperty` does not cause any issue, as it is just a qualifier. The real issue is `@Inject` as it declares injection point as explained in my previous comment.

**Comment by ljnelson** [comment]
Isn't all of this important to spell out to end users?

**Comment by Emily-Jiang** [comment]
Let's add a sentence in this spec to mention CDI spec  (Section 6.6.2) as per https://github.com/eclipse/microprofile-config/issues/404#issuecomment-543213159

**Comment by rdebusscher** [comment]
And we need a TCK test to enforce it for the implementations,  I guess.

Inject into a CDI scoped bean?

**Comment by Emily-Jiang** [comment]
@rdebusscher as I explained this is not introduced by Config spec but by CDI. I am not sure we need a TCK for this. The sentence is just for CDI spec awareness though.
