### ISSUE TITLE
ConfigProperty.cacheTimeUnit should be a ChronoUnit

### ISSUE THREAD

**Issue by tevans78** [eclipse/microprofile-config#406]
https://github.com/eclipse/microprofile-config/blob/d46dd14ec3370ae861da8e26cf1c4016cbf8a040/api/src/main/java/org/eclipse/microprofile/config/inject/ConfigProperty.java#L153

ConfigProperty.cacheTimeUnit should be a `java.time.temporal.ChronoUnit` rather than a `java.util.concurrent.TimeUnit`

This keeps it consistent with the use of `java.time.Duration` in `ConfigAccessorBuilder.cacheFor`

**Comment by keilw** [comment]
I guess since Java 9 that seems acceptable because you can use that `ChronoUnit` to build a `TimeUnit` which is still the default everywhere like CompletableFuture/CDI Async or JCache and many other places.
