### ISSUE TITLE
TCK assertion parameters are backwards

### ISSUE THREAD

**Issue by tevans78** [eclipse/microprofile-config#409]
https://github.com/eclipse/microprofile-config/blob/d46dd14ec3370ae861da8e26cf1c4016cbf8a040/tck/src/main/java/org/eclipse/microprofile/config/tck/ConfigAccessorTest.java#L97

These parameters should be the other way around ... expected, actual

**Comment by jmesnil** [comment]
@tevans78 the code is correct.

This method comes from TestNG Assert class: `org.testng.Assert#assertEquals(java.lang.String, java.lang.String)` whose parameters are `actual, expected`.

This is the opposite of JUnit Assert class `org.junit.Assert#assertEquals(java.lang.Object, java.lang.Object)`whose parameters are `expected, actual`.

**Comment by tevans78** [comment]
Hmmm I thought I had spotted this problem when running (failing) the TCKs and the messages looked backwards. I will try that again.

**Comment by tevans78** [comment]
My mistake then... maybe this issue should have been against TestNG ;-)
