### ISSUE TITLE
Support for dynamic property names

### ISSUE THREAD

**Issue by markusincognitus** [eclipse/microprofile-config#419]
Is there any chance to support dynamic property names and dynamic property resolving?

Examples:
   api.baseurl.service1
   api.baseurl.service2
or
   business.limit.customer1
   business.limit.customer2
   business.limit.default

Or do I always have to know all property names (all variants) in advance?

The ConfigSource defines two methods
     - Map<String, String> getProperties()
     - Set<String> getPropertyNames()
which seem to make any dynamic configs impossible.

BR Markus

**Comment by cghislai** [comment]
A ConfigSource implementation has to list defined properties only. You don't have to know all possible keys, this is an infinite set. You don't have to know keys handled by the application, this is application specific.

You could use string formatting in your application to query a property with a name following a specific pattern.

**Comment by dmlloyd** [comment]
We support this in Quarkus to an extent, for our built in extensions.  It's not simple but it is *possible*.

**Comment by Emily-Jiang** [comment]
We discussed at today's hangout. It is not required for MP Config to spec mandate all config names are listed due to security purpose. We are going to close this issue. Please reopen and provide more info if you disagree.
