### ISSUE TITLE
Ban use of '/' in config keys

### ISSUE THREAD

**Issue by kenfinnigan** [eclipse/microprofile-config#420]
For "Cloud Native" use we need to ban the use of '/' within configuration keys.

As per https://github.com/eclipse/microprofile-rest-client/issues/171, it's not possible to convert a configuration key with '/' into an appropriate environment variable.

I believe FT also uses '/' heavily in configuration keys.

**Comment by cescoffier** [comment]
I would even go further. The spec should enforce the [IEEE 1003.1-2017 - IEEE Standard for IEEE Information Technology - (POSIX)](https://standards.ieee.org/standard/1003_1-2017.html) recommendations.

```
Environment variable names used by the utilities in the Shell and Utilities volume of
POSIX.1-20xx consist solely of uppercase letters, digits, and the ’_’ (underscore). 
```

So `/` is not an accepted character.

I believe that all specs requiring `/` in their configuration key should be updated (as MP 3.0 allows breaking change, it's the right moment).

**Comment by Emily-Jiang** [comment]
Config automatically converts non alphabetical numberic character to _ when trying to match environment variables. There is no issue when using /.

**Comment by cescoffier** [comment]
Doesn't that make environment variables weird with potentially several consecutive `_`.

**Comment by cescoffier** [comment]
And from https://github.com/eclipse/microprofile-rest-client/issues/171 it seems that `.` is not replaced. While `.` should not be accepted either.

**Comment by cescoffier** [comment]
I'm actually confused because https://github.com/eclipse/microprofile-config/issues/264 says that `.` are replaced by `_`.

**Comment by cescoffier** [comment]
So basically, the spec should enforce that the mapped names are valid according to the IEEE recommendations.

**Comment by Emily-Jiang** [comment]
As per my previous comment, all non alphabetical numberic will be replaced with _. It cover . / or any others, which is not alphabetical nor numberic.

**Comment by Emily-Jiang** [comment]
Read the config spec, which explains more. I think there is any issue to provide wider replacements beyond . -> _

**Comment by kenfinnigan** [comment]
For me it's not the fact that there isn't a solution around the problem, it's that we make it confusing by needing to know what the key can contain in different environments.

I would prefer the key is identical wherever it's used, which is why I think it makes sense for MP Config to ban inappropriate key name content

**Comment by cghislai** [comment]
i think it is not confusing. the intent and the behaviour are clearly specified, under the 'Default ConfigSources' title.
Other config sources might have other restrictions and require other key names mappings, so restricting it at the spec level would just put your issue one step further provided you use a non-default config source.

**Comment by hutchig** [comment]
It would seem to me that if an organisation does not like '/' in properties it is free to do this as local policy and the Config spec will be perfectly happy with that too.

**Comment by hutchig** [comment]
Also relevant is that https://github.com/eclipse/microprofile/pull/100/files references
FT's use of "/" as a delimeter as a common pattern!

**Comment by Emily-Jiang** [comment]
At today's hangout, @kenfinnigan @jmesnil and I discussed this in more details. We should certainly document the character mapping in the javadoc of Config.java to ensure end users are aware of how to override properties in environment variables.
