### ISSUE TITLE
Specify a REST endpoint that exposes config properties

### ISSUE THREAD

**Issue by OndroMih** [eclipse/microprofile-config#428]
I have the following use case in mind:

It's very easy to access config in a Java service. But not so easy on the frontend, which is very often built using Javascript. For Javascript frontends, it would be very useful to be able to read the config using a REST service exposed by the Java backend in a standard way.

Considerations:

* MicroProfile runtimes would expose a REST service to expose config values, or a standard endpoint, e.g. /config
* the REST service would allow accessing a single property or a set of properties (via GET query params or JSON array as a POST body)
* the response would be a JSON map with key-value pairs (needs to be investigated which format would work best with popular Javascript frameworks)
* it needs to be restricted in the backend which config values can be exposed (e.g. with a special config property which contains a list of allowed keys)
* it should support JWT authentication or another mechanism to restrict access only to pages served by the application

This would greatly simplify accessing config values in a JS frontend, increasing productivity and creating a unified way how to configure all frontend code.

Currently, JS code on frontend can be configured only by a custom config REST endpoint or an external configuration service like etcd directly accessed from JS, which is not a safe pattern.

**Comment by derekm** [comment]
I believe @phillip-kruger had thoughts here. He has built a UI for MP Health in MicroProfile-Ext.org, IIRC.

**Comment by phillip-kruger** [comment]
You mean the REST Endpoint in memory config source?
https://github.com/microprofile-extensions/config-ext/tree/master/configsource-memory

**Comment by derekm** [comment]
Ah, there they are!

I think those endpoints are limited to the one MemoryConfigSource instance.

But yeah, something similar for the coalesced values across all config sources & for inspecting each config source, etc.

**Comment by phillip-kruger** [comment]
The endpoint expose all config sources and values, and because of the Ordinal of Memory Config source is very high, when you then set a value via the REST Api, it's the one that will be used (until the application restarts and the memory is clears).

**Comment by kenfinnigan** [comment]
@OndroMih what kind of config are you thinking that's beneficial to be defined on the backend and retrieved by JS? Why not have configuration defined within the front end?

**Comment by Emily-Jiang** [comment]
This can be easily extended by either end user or runtime. I hesitate putting this in the spec for the following reasons:

1. What is the performance like for sucking out the huge configure sources, e.g. zookeeper

1. I think it is ideal for microservices to expose the end point and have full responsibility as they know the application and scenario well.

1. How often the endpoint is assessed? I wonder whether it wastes resources to display something only used occasionally.

With the above concern, I think if some microservices need the end point, it might be ideal for the microservices to provide this end point as they know the environment and config sources provided very well.

**Comment by Emily-Jiang** [comment]
I plan to close this one as this should not be covered by the spec and the implementations can provide this kind of extra tool. Please reopen if you think otherwise.
