### ISSUE TITLE
How to best convert Environment Variables to application properties?

### ISSUE THREAD

**Issue by rsoika** [eclipse/microprofile-config#441]
I have a general question about config api and custom ConfigSources. 

My application expects config parameters in the naming convention

    my.custom.config.param=xxxxx

This works for microprofile.properties and also for my custon ConfigSource reading a application property file.

When I run my application with Docker and I want to inject a parameter as an environment variable my naming convention is not compatible with Docker/Unix ENV Params. So I must translate my param

    from 'my.custom.config.param' into 'MY_CUSTOM_CONFIG_PARAM'

Now my idea is to extend my custom ConfigSource with something like this

```
	@Override
	public String getValue(String key) {
		if (properties == null) {
			loadApplicationProperties();
		}

		// convert from 'my.custom.config.param' into 'MY_CUSTOM_CONFIG_PARAM'
		Sting keyUnixStyle=convertKey(key); 
		ConfigBuilder builder = ConfigProviderResolver.instance().getBuilder(); 
		builder.addDefaultSources(); 
		Config config = builder.build(); 

		String sys_env_value=config.getValue(keyUnixStyle);
		// do we have a UNIX param?
		if (sys_env_value!=null && !sys_env_value.isEmpty()) {
			return sys_env_value; // YES
		}

		return properties.get(properties.get(key));
	}
```

Is this crazy nonsense or just a genial idea?

**Comment by jmesnil** [comment]
The Env config source is providing this mapping for you as documented in https://github.com/eclipse/microprofile-config/blob/master/spec/src/main/asciidoc/configsources.asciidoc#default-configsources

**Comment by rsoika** [comment]
Wow - this is great. I was not aware of this functionality. Thanks a lot

**Comment by Emily-Jiang** [comment]
Close this one as this is resolved.
