### ISSUE TITLE
Must a Config actually use Converters?

### ISSUE THREAD

**Issue by ljnelson** [eclipse/microprofile-config#448]
The [`Config` interface of course does not refer to them at all](https://static.javadoc.io/org.eclipse.microprofile.config/microprofile-config-api/1.3/org/eclipse/microprofile/config/Config.html).

The [`ConfigBuilder` interface accepts them](https://static.javadoc.io/org.eclipse.microprofile.config/microprofile-config-api/1.3/org/eclipse/microprofile/config/spi/ConfigBuilder.html) but there does not seem to be a requirement anywhere I can find that these `Converter`s actually be _used_ by a `Config` implementation.

By contrast, `ConfigSource`s, which are also accepted by a `ConfigBuilder`, clearly show up in the `Config` interface (although they give rise to [another issue whose comment section apparently augments the specification](https://github.com/eclipse/microprofile-config/issues/431#issuecomment-519858099)).

The specification around Converters also mentions, at the bottom:

> If a `Converter` implements the `java.lang.AutoCloseable` interface then the `close()` method will be called when the underlying `Config` is being released.

What does "underlying" mean?

Also this implies that an autocloseable `Converter` must be used in some unspecified way by exactly one `Config` instance, or it will be at risk of being closed improperly from the viewpoint of some other `Config` instance.  This doesn't seem to be spelled out anywhere.

For clarity: clearly I understand the _intent_ is that conversion must happen using `Converter` instances during the [`Config#getValue(String, Class)` method](https://static.javadoc.io/org.eclipse.microprofile.config/microprofile-config-api/1.3/org/eclipse/microprofile/config/Config.html#getOptionalValue-java.lang.String-java.lang.Class-) in some hazy way.  But it seems to me there is no such requirement anywhere.

If such conversion must be used, is it reasonable to provide a `getConverters()` method on `Config`, much as there is a `getConfigSources()` method on `Config`?

Is it therefore also reasonable to suggest that there be a full specification of how conversion must behave when the `getValue(String, Class)` and `getOptionalValue(String, Class)` methods are invoked?

**Comment by dmlloyd** [comment]
The behavior of converters is more or less laid out here: https://github.com/eclipse/microprofile-config/blob/master/spec/src/main/asciidoc/converters.asciidoc

I've proposed the following improvements/clarifications to the JavaDoc: https://github.com/eclipse/microprofile-config/pull/445/files#diff-cba20e499de1f727fdbf90650c680ce9R36 (see the result here: https://github.com/eclipse/microprofile-config/blob/74a8c9f881931ffd38d19156e8248b707d7c9499/api/src/main/java/org/eclipse/microprofile/config/spi/Converter.java#L35-L108)

I would agree that at the very least there needs to be a `<T> Converter<T> getConverter(Class<T> clazz)` method on `Config` which returns the converter that would be used for the given class.  Having a `getConverters` method is a bit hazy because it would need to be decided whether built-in or implicit converters are included, and those are generally created on demand so if those are included, the returned collection might confusingly change over time.

**Comment by ljnelson** [comment]
I truly understand the intent, I really do.

But I urge you and others to read the specification with "robot implementor" eyes.  Here, for example, I don't think there is anything that says when `Converter`s should be used, how they should be used, how many of them there can be, what the builder must do to "install" them into the `Config` if indeed they must live "inside" the `Config`, what happens if they're shared between `Config`s, whether they're thread safe, etc. etc. etc. etc.  Language matters.

I always look to the CDI specification as a good example that splits the difference between having an answer for everything where one is needed, readability, and clear identification of where implementations may do what they wish.  I find nothing like that in this specification in many different areas and have been trying to [file issues](https://github.com/eclipse/microprofile-config/issues/created_by/ljnelson) (as advised) where I've noticed gaps so that in [my own implementation](https://microbean.github.io/microbean-microprofile-config/index.html) I can document all the non-specified choices I've had to take as an implementor with references to this project's issue board.

**Comment by dmlloyd** [comment]
I agree that the specification quality is very sub-par.  This has caused us many headaches as well maintaining SmallRye Config and Quarkus.  I'm hoping that if we can get past #443 and #445, we can follow up with some proposals which would greatly improve the specification language.

**Comment by Emily-Jiang** [comment]
@ljnelson 
The specification around Converters also mentions, at the bottom:

    If a Converter implements the java.lang.AutoCloseable interface then the close() method will be called when the underlying Config is being released.

What does "underlying" mean?

The above sentence means the config object constructed via the Builder pattern where you supplied the converters.

I am not sure how useful it is to list the converters at all. Can you explain why do you need this method?

**Comment by ljnelson** [comment]
> The above sentence means the config object constructed via the Builder pattern where you supplied the converters.

But there is no requirement that the converters supplied to the builder are actually used by the `Config`.  If you think there is such a requirement, please point to the text where it says that a `Config` object must use `Converter`s supplied to the builder.

**Comment by dmlloyd** [comment]
In the `converters` part of the spec, [the text](https://github.com/eclipse/microprofile-config/blob/master/spec/src/main/asciidoc/converters.asciidoc#adding-custom-converters) currently reads:

> A custom `Converter` for a target type of any of the built-in Converters will overwrite the default Converter.

I think it is meant to say "override" not "overwrite".  In [a follow-up section](https://github.com/eclipse/microprofile-config/blob/master/spec/src/main/asciidoc/converters.asciidoc#automatic-converters) it says:

> If no built-in nor custom `Converter` exists for a requested Type `T`, an implicit `Converter` is automatically provided if the following conditions are met:

I think this implies that custom converters will be used for a given type if available.

But I agree again that the spec language is not clear and needs refinement.

**Comment by Emily-Jiang** [comment]
@dmlloyd please come up with a PR to clarify this.

**Comment by Emily-Jiang** [comment]
@dmlloyd I'm going to create a PR for this in a minute so that it can be included in the Config 1.4 release.

**Comment by dmlloyd** [comment]
I've been working on an overarching JavaDoc cleanup PR which I hope to submit today, but there will likely be conflicts.

**Comment by ljnelson** [comment]
What was the final result here?  Was the specification text altered?

**Comment by kenfinnigan** [comment]
@ljnelson https://github.com/eclipse/microprofile-config/pull/498 contains the changes
