### ISSUE TITLE
Javadoc build warning during MicroProfile 3.1 release build

### ISSUE THREAD

**Issue by jclingan** [eclipse/microprofile-config#455]
From a [MicroProfile 3.1 Release build](https://ci.eclipse.org/microprofile/view/Release/job/MicroProfile%20Releases/258/console):

[INFO] [WARNING] Javadoc Warnings
[INFO] [WARNING] Picked up JAVA_TOOL_OPTIONS: -Xmx2G -Djava.io.tmpdir=/tmp/genie.microprofile -DforkCount=2
[INFO] [WARNING] /jobs/genie.microprofile/MicroProfile Releases/workspace/target/checkout/target/distro-javadoc-sources/microprofile-config-api-1.3-sources/org/eclipse/microprofile/config/ConfigProvider.java:82: warning: empty <p> tag
[INFO] [WARNING] * <p>
[INFO] [WARNING] ^

**Comment by jmesnil** [comment]
It has been fixed since MicroProfile Config 1.3 in https://github.com/eclipse/microprofile-config/commit/bd2b3c9c824cbc455fb9382b5a71bbfe809cfb89#diff-cef42990db8902fbdfcfc7a0936e3ad0
