### ISSUE TITLE
Incorrect description in the README

### ISSUE THREAD

**Issue by kenfinnigan** [eclipse/microprofile-config#457]
The project README has the following statement in the third paragraph:

> Under some circumstances, some data sources may change dynamically. The changed values should be fed into the client without the need for restarting the application. This requirement is particularly important for microservices running in a cloud environment. The MicroProfile Config approach allows to pick up configured values immediately after they got changed.

As the current specification doesn't describe the ability to handle dynamically changing values, it is probably a good idea to remove this statement.

**Comment by Emily-Jiang** [comment]
Both spec and Javadoc on ConfigProperty annotation mentions the retrieval of the dynamic config property. 

> //Injects a Provider for the value of myprj.some.dynamic.timeout property to
    //resolve the property dynamically. Each invocation to Provider#get() will
    //resolve the latest value from underlying Config.
    //The existence of configured values will get checked during startup.
    //Instances of Provider<T> are guaranteed to be Serializable.
    @Inject
    @ConfigProperty(name="myprj.some.dynamic.timeout", defaultValue="100")
    private javax.inject.Provider<Long> timeout;

We left how the runtime handles the dynamism unspeced on purpose.

**Comment by kenfinnigan** [comment]
I'd missed that reference in searching yesterday.

Not sure if there are other issues related to this, but I think the spec needs to move away from leaving it undefined otherwise it becomes a huge gray area where implementations can do completely different things and users get unexpected behavior if they migrate between them

**Comment by Emily-Jiang** [comment]
Thanks for your feedback, Ken! Points taken. Let's add a couple of sentences in the spec to clearly spell it out.

**Comment by ljnelson** [comment]
Related: #369, #370, #371, #395, #431

**Comment by Emily-Jiang** [comment]
Since we have not reached a conclusion, I'll move this issue out of the MP Config 1.4 milestone.

**Comment by dmlloyd** [comment]
Also related: #432 #304

**Comment by Emily-Jiang** [comment]
fixed by #478
