### ISSUE TITLE
Fix indentation issue in spec for default configsource

### ISSUE THREAD

**Issue by jmesnil** [eclipse/microprofile-config#464]

**Comment by jmesnil** [comment]
This duplicates #380

**Comment by jmesnil** [comment]
@Emily-Jiang I'm still not able to pass the ECA validation tool in the PR #464...
I have a valid ECA for jmesnil@redhat.com but the tool thinks this commit is done anonymously instead of being signed-off by me (https://accounts.eclipse.org/users/jmesnil)...

**Comment by Emily-Jiang** [comment]
@jmesnil in the error message, it says your email address did not associate with your account. In your Eclipse account, did you put your github url there as well? I'll try to ask someone from Eclipse next week at EclipseCon Europe.
