### ISSUE TITLE
Should Interfaces extend Serializable?

### ISSUE THREAD

**Issue by kenfinnigan** [eclipse/microprofile-config#473]
Should `ConfigSource`, `Converter`, and other interfaces extend `Serializable` to prevent the need for implementations of converters, etc to do it explicitly?

**Comment by Emily-Jiang** [comment]
@kenfinnigan @carlosdlr and I discussed this. We agreed that it makes sense for `Converter` to implement `Serializable`.

**Comment by smillidge** [comment]
Can we actually have discussion on the issue rather than somewhere else?

**Comment by kenfinnigan** [comment]
@smillidge from what I recall it was a very short conversation, that leads to the outcome above.

If you have a different view, then please comment here and it can be discussed further

**Comment by Emily-Jiang** [comment]
For the record of this converation, IIRC we think the reason to make converter seralizable since it is quite trivial to do so and this change will save implemenation a lot of work.

**Comment by radcortez** [comment]
What was the reasons against `ConfigSource`?

**Comment by Emily-Jiang** [comment]
It is difficult for the configsource impl to deal with the seralization and get it right.
