### ISSUE TITLE
Copyright dates have not been properly updated

### ISSUE THREAD

**Issue by tevans78** [eclipse/microprofile-config#489]
I noticed that https://github.com/eclipse/microprofile-config/pull/467 significantly changed `ConfigProviderResolver` but the dates in the copyright header were not also updated. The dates are still `2016-2017` when I think they should be `2016-2019`.
https://github.com/eclipse/microprofile-config/blob/c520c7dd2bb20655814cc313a444fd0b71b3ec84/api/src/main/java/org/eclipse/microprofile/config/spi/ConfigProviderResolver.java#L3

I have not checked any other source files, this is just the one I happened to notice.

**Comment by Emily-Jiang** [comment]
This has been fixed.
