### ISSUE TITLE
add convenience methods for getting multi-valued properties

### ISSUE THREAD

**Issue by emattheis** [eclipse/microprofile-config#496]
The existing `Config` API only permits retrieving multi-valued properties as arrays like this:

```java
for (String value : config.getValue("my.key", String[].class)) {
    // do something with value
}
```

I propose we add the following methods to permit retrieving more than one value in a more natural way:

```java
<T> Iterable<T> getValues(String propertyName, Class<T> propertyType);
    
<T> Optional<Iterable<T>> getOptionalValues(String propertyName, Class<T> propertyType);
```

This would enable the use of lamba-friendly patterns like this:

```java
config.getValues("my.key", String.class)
      .forEach(value -> {
            // do something with value
      });
```

As a bonus, the developer doesn't need to worry about asking for `String.class` or `String[].class` depending on the scenario.

**Comment by kenfinnigan** [comment]
Not sure I agree with your final comment around bonus, either way, you need to know whether you're dealing with a single value or array of values.

I've heard that the use of lambdas instead of `forEach()` is not better for performance and marginal on readability, so not sure about the benefits of this.

Curious as to what others think

**Comment by emattheis** [comment]
My last comment wasn't meant to imply that a developer doesn't need to know whether she is dealing with multiple values, just that she needn't concern herself with creating the actual array class. Selecting the first element of a list of one or more is a fairly common idiom, and if you want to layer something on top of microprofile-config to abstract away the difference between a single value or many values of an arbitrary type you have to deal with this: https://stackoverflow.com/questions/4901128/obtaining-the-array-class-of-a-component-type.

Debates about whether lambdas are "better" in the readability and performance departments aside, functional programming is alive and well on the Java platform, so I think we ought to at least reduce any friction there.

Even with traditional Java programming techniques, the new methods are still valuable because implementations are not restricted to constructing arrays. By using `Iterable<T>`, this is still an option:

```java
for (String value : config.getValues("my.key", String.class)) {
    // do something with value
}
```

and the implementation is free to use any iterable under the covers.

**Comment by dmlloyd** [comment]
In SmallRye we take the approach of allowing the user to give a generator which could yield (for example) a List, Set, or Sorted/NavigableSet.  We could likely use that to implement a feature like this without too much trouble.  That said, it might be worth deciding about config accessors before we add more methods to `Config` itself...

**Comment by emattheis** [comment]
I did see the SmallRye approach, but felt it might be overcomplicated for the basic need, but I'm not opposed to it as an overloaded option.

I ultimately went with `Iterable<T>` because:

1. `Config` is already using `Iterable` to provide access to property names and source.
2. To simply iterate over configured values, the caller doesn't need to know (or wish to specify) the collection type.
3. To collect values, the caller likely already has a place to put them (e.g. a builder or existing collection) so an iterable solves that neatly without an intermediate collector.

Is there an ongoing discussion about accessors?

**Comment by dmlloyd** [comment]
> Is there an ongoing discussion about accessors?

Yes, but it's tied up in #444/#445 and related discussion.  It might be a good idea to break that concept out into a separate discussion.

**Comment by dmlloyd** [comment]
> I did see the SmallRye approach, but felt it might be overcomplicated for the basic need, but I'm not opposed to it as an overloaded option.
> 
> I ultimately went with `Iterable<T>` because:
> 
> 1. `Config` is already using `Iterable` to provide access to property names and source.

+1.

> 2. To simply iterate over configured values, the caller doesn't need to know (or wish to specify) the collection type.

I suppose.  The caller might commonly want access to the number of values though, ahead of time.  And at least in our case the collection type is going to end up always being like an `ArrayList` or something like that.

> 3. To collect values, the caller likely already has a place to put them (e.g. a builder or existing collection) so an iterable solves that neatly without an intermediate collector.

Is there an advantage to using `Iterable` (e.g. `iter.forEach(existing::add)`) over `Collection` (e.g. `existing.addAll(coll)`)?  `Collection` is more functional while also compatible so I'd think it would be down to whether it is substantially more difficult to implement `Collection` in the result than `Iterable`.

Of course once you're supporting `Collection`, then `List` makes a lot of sense...

**Comment by emattheis** [comment]
I didn't consider wanting to know the number of values, but that's certainly a valid reason for exposing a more expressive type. As you mention, `List<T>` feels like the best approach semantically, but `Iterable<T>` feels less imposing from a specification point of view. My personal motivation for this issue was to provide an alternative to the use array classes to access multivalued properties, so I'm okay with just about anything that achieves that.

On the accessor front, I'm ambivalent. I can appreciate its appeal, but I don't think it adds a tremendous amount of value in most cases. Even if accessors are the way we go, I would still argue for default convenience methods in the `Config` interface that use accessors under the covers.

In my experience, application usage of MicroProfile Config is almost entirely through injected values, so I'm fine with the idea of the `Config` interface itself becoming more complex since it really only affects those who need the complexity.

**Comment by dmlloyd** [comment]
> I didn't consider wanting to know the number of values, but that's certainly a valid reason for exposing a more expressive type. As you mention, `List<T>` feels like the best approach semantically, but `Iterable<T>` feels less imposing from a specification point of view. My personal motivation for this issue was to provide an alternative to the use array classes to access multivalued properties, so I'm okay with just about anything that achieves that.

OK.  I think `List` is probably the way to go then: we could even supply a default implementation which determines the array type (in the hacky way) and then gets and wraps the resultant array using `Arrays.asList`.

> On the accessor front, I'm ambivalent. I can appreciate its appeal, but I don't think it adds a tremendous amount of value in most cases. Even if accessors are the way we go, I would still argue for default convenience methods in the `Config` interface that use accessors under the covers.

Makes sense, I feel that way as well as it happens.

> In my experience, application usage of MicroProfile Config is almost entirely through injected values, so I'm fine with the idea of the `Config` interface itself becoming more complex since it really only affects those who need the complexity.

OK.

**Comment by emattheis** [comment]
That works for me. Not sure which hacky way is best for obtaining the array class in the default implementation, but the `Array#newInstance` approach seems like the cleanest since there are no magic string formulas or checked exceptions to deal with.

```java
default <T> List<T> getValues(String propertyName, Class<T> propertyType) {
    @SuppressWarnings("unchecked")
    Class<T[]> arrayType = (Class<T[]>) Array.newInstance(propertyType, 0).getClass();
    return Arrays.asList(getValue(propertyName, arrayType));
}

default <T> Optional<List<T>> getOptionalValues(String propertyName, Class<T> propertyType) {
    @SuppressWarnings("unchecked")
    Class<T[]> arrayType = (Class<T[]>) Array.newInstance(propertyType, 0).getClass();
    return getOptionalValue(propertyName, arrayType).map(Arrays::asList);
}
```

**Comment by Emily-Jiang** [comment]
We talked about this in the past to return the List<> Set<> etc. We didn't add to the spec eventually as it is so easy to get array and then you can use Arrays.asList<> in your code. The other reason is that the injection flavour was used often rather than the programmatic api. We try to reduce the concrete impl so that less bug is contained.

**Comment by emattheis** [comment]
I would argue that this is a very minor addition to the spec that is basically zero cost to maintain. The main benefit is that it makes it extremely clear at a glance that there is in-built support for multi-valued properties. When you encounter the MicroProfile Config API for the first time, figuring out how do call `getValue("my.key", String[].class)` is a bit of a journey and you end up with pretty clunky code to boot.

If we refuse to grow the spec to accomodate users, we simply encourage non-standard deviations from the spec. One only has to glance at the SmallRyeConfig class to see that happening 😛

**Comment by struberg** [comment]
Hi @emattheis! Regarding you comment that it's 'just one more method and zero cost to maintain'. That might be true, but there is another side: it makes the API bigger. And finally we will end up with 20 'convenience functions' which are each almost zero cost'. Well, but they blur the whole API. Users then will not only have our 5 methods which do the heavy-lifting, they will have 25 methods, 20 of them just convenience. So it will make the design blurry and not so clear anymore. Got me?

We have been there in the past. And then we went back and radically got rid of anything which is not core. And we achieved this without loosing any functionality. This fundamental design approach may not be written down somewhere, but it is what we decided at some point in time.

**Comment by emattheis** [comment]
@struberg totally understand and agree - there is definitely a limit to how far we want to expand the API for the sake of convenience.

In this case, however, I think the API is already blurry: it is not clear at a glance that multi-value properties have first class support. The `Array[].class` mechanism is hard to discover and (arguably) cumbersome to use.

I'm onboard with the accessor idea to keep Config concise, I just don't know that we're there yet.

**Comment by dmlloyd** [comment]
I don't think that any of the reasons given are sufficient to keep one method out of the API.  The "slippery slope" argument is also fallacious as well, since it could equally be used to say that nothing should ever be added to the specification.

The changes specified in #501 are low impact, provide a cleaner solution for a valid use case, and do not require any work on behalf of implementation authors.  I think that to deny this enhancement for 2.0 would be unnecessarily curmudgeonly and really a big negative for contributors.

After all if we can't even agree to accept a simple enhancement like this, why would any contributors even try for anything more interesting or ambitious?

**Comment by dmlloyd** [comment]
Let's discuss accepting this for 2.0.

**Comment by Emily-Jiang** [comment]
The PR #501 has been merged a while ago.
