### ISSUE TITLE
Complete Optional family support

### ISSUE THREAD

**Issue by rmannibucau** [eclipse/microprofile-config#513]
Follow up ticket of a side note of https://github.com/eclipse/microprofile-config/issues/365

Wonder if there is any rational to not support OptionalInt and friends as valid injection types out of the box.

**Comment by emattheis** [comment]
I would also suggest specifying support for `Optional<List<T>>` and `Optional<Set<T>>`.

**Comment by Emily-Jiang** [comment]
@rmannibucau we do support Optional Injection. See the spec and [javadoc](https://download.eclipse.org/microprofile/microprofile-config-1.4-RC2/apidocs/) of `ConfigProperty` .

**Comment by Emily-Jiang** [comment]
Do you see any other gaps in the Optional injection? If not, please close this issue.

**Comment by rmannibucau** [comment]
This issue is about all optional flavors. Only Optional is supported, not OptionalInt and friends.

**Comment by Emily-Jiang** [comment]
Since you cannot do `Optional<int>`, I think the boxed version `Optional<Integer>` makes sense.

**Comment by rmannibucau** [comment]
@Inject @ConfigProperty OptionlInt optionalInt;

Same for doubles, booleans... ;)

**Comment by Emily-Jiang** [comment]
ah. sorry. I now got it. Thanks! +1 on support it!

**Comment by radcortez** [comment]
These are the specialised Optional types:

`java.lang.OptionalDouble`
`java.lang.OptionalInt`
`java.lang.OptionalLong`

**Comment by Emily-Jiang** [comment]
Let's get it done in June's release.

**Comment by Emily-Jiang** [comment]
@radcortez

**Comment by radcortez** [comment]
Done.
