### ISSUE TITLE
Using org.junit in TCK tests

### ISSUE THREAD

**Issue by gpor0** [eclipse/microprofile-config#516]
One of TCK tests in mp-config 1.4 contains Assert from org.junit package.
https://github.com/eclipse/microprofile-config/blob/950133a4e6fee46885aa2ad088822b4dd3b84089/tck/src/main/java/org/eclipse/microprofile/config/tck/ConverterTest.java#L443

This is causing Class Not Found exception when running TCK tests. Since this is the only occurrence I believe it should be refactored to use org.testng.

**Comment by radcortez** [comment]
Thank. Would you like to submit a PR for it? Thanks!

**Comment by gpor0** [comment]
sure.

**Comment by Emily-Jiang** [comment]
Good obeservation @gpor0! We tried to use testNG across the board.

**Comment by pzygielo** [comment]
> Since this is the only occurrence

How about https://github.com/eclipse/microprofile-config/blob/bb6c66fa698c3f2f32dcd564b17adc72811431a5/tck/src/main/java/org/eclipse/microprofile/config/tck/CDIPropertyNameMatchingTest.java#L37?

**Comment by gpor0** [comment]
I didn't have any problems with that Test probably because Junit Assert is used in fails only and all my tests were passed. @Emily-Jiang should we remove that usages too?
