### ISSUE TITLE
(Process issue) Label cleanup

### ISSUE THREAD

**Issue by dmlloyd** [eclipse/microprofile-config#525]
Our labels are a little bit of a mess at the moment; I propose that we do a little bit of a cleanup based on the discussion we had on the call today.

Here's what I propose:

* Add the `Implementation` label as discussed.
* Drop unused or seldom used labels.  We can always re-add them if it turns out they are needed.  The labels I suggest dropping are:
   * `duplicate` (this should just be a comment in the issue)
   * `help wanted`
   * `in progress`
   * `invalid`
   * `question`
   * `test`
   * `wontfix`
   * `work-in-progress`
* Drop the old `mpconfig-1.0` and `mpconfig-1.4` labels and create milestones for these releases instead.
* Drop the `mpconfig-later` label altogether.  Issues can be opted into a milestone to be scheduled; there's no need to have a label that means unscheduled when unscheduled also means unscheduled.
* Drop the `enhancement` label and divide these issues between `Use case` and `Implementation` as needed.
* Drop these categorical labels in favor of linking to "use case" issues:
   * `ConfigProperties`
   * `ConfigValue`
   * `empty`
   * `mutable`
* Minor cleanups to make the label names consistent in terms of punctuation, capitalization, etc.

REMEMBER that this doesn't have to be perfect - we can always add or remove labels later - but since I wanted to make several changes at once I thought it would be good to run it past the group first rather than just doing it.

↓↓ If you support this change, please click the 👍 instead of commenting with +1 or similar.

**Comment by Emily-Jiang** [comment]
@dmlloyd are you saying deleting all lables and just add `Implementation` tag to mean the issues is not about use case but implementation ideas? With this, we have two labels: use case and implementation. If yes, feel free to add it. As for the categories, I think it is nice to group them so that when you fix one issue you can view other related ones, which might influence your design. I am ok to get rid ot them if you have strong preferences.

**Comment by dmlloyd** [comment]
> @dmlloyd are you saying deleting all lables and just add `Implementation` tag to mean the issues is not about use case but implementation ideas?

No, I did not say anywhere that all labels should be deleted, only the ones I've listed.  Each bullet point is one proposal.

**Comment by Emily-Jiang** [comment]
> No, I did not say anywhere that all labels should be deleted, only the ones I've listed. Each bullet point is one proposal.

Sorry, I meant to say all listed labels in your issue. Good idea to clean up.

**Comment by dmlloyd** [comment]
This work is complete! :heavy_check_mark:
