### ISSUE TITLE
clarify behavior when null is passed to Converter::convert

### ISSUE THREAD

**Issue by emattheis** [eclipse/microprofile-config#539]
Per [a discussion](https://github.com/eclipse/microprofile-config/pull/495#discussion_r391108071) in #495, `null` should never be passed to a converter. We should clarify what exception should be thrown if this occurs.

Obvious choices are `NullPointerException` or `IllegalArgumentException`.

**Comment by dmlloyd** [comment]
The convention used throughout the JDK is `NullPointerException`.  Given that this is technically an SPI I think that is sufficient, and also allows use of the standard `Objects.requireNonNull` methods.

**Comment by dmlloyd** [comment]
I'm not sure if we want to define this though.  It might be better to say something like: "Passing `null` to this method is not allowed, and may result in a `NullPointerException` or other undesired behavior".

**Comment by emattheis** [comment]
Or we could say that `null` must be returned if `null` is supplied 🤔 It might be more convenient to propagate `null`values than to raise an exception in certain scenarios.

**Comment by dmlloyd** [comment]
That did not seem to be the case when we implemented this behavior within SmallRye.  The extra check for `null` is more of a hindrance, and it can be skipped altogether if we go with exception (or exception+undefined) behavior because the moment the string is dereferenced, an NPE arises.

**Comment by emattheis** [comment]
Okay, so maybe something to consider in the discussion around externalizing converters. I was thinking along the lines of XML or JSON converters where you might chain converters together and you need to ultimately produce `null` without raising an exception.

**Comment by Emily-Jiang** [comment]
We could choose between NPE and null. Maybe NPE is more reasonable.

**Comment by dmlloyd** [comment]
> Okay, so maybe something to consider in the discussion around externalizing converters. I was thinking along the lines of XML or JSON converters where you might chain converters together and you need to ultimately produce `null` without raising an exception.

You *do* chain them together, but not input-to-output-to-input-to-output; rather it's input-to-input-to-output-to-output.

**Comment by Emily-Jiang** [comment]
We settled on NPE if the value null is passed to convert().
