### ISSUE TITLE
move getString back to getValue (as it originally was)

### ISSUE THREAD

**Issue by struberg** [eclipse/microprofile-config#54]
I just became aware (due to a commit in #44) that getValue got renamed back to getString. I think this was an accident.

The method originally was named getValue(String key) and an overload to getValue(String key, Class<T> type).

When Emily did experiment with explicit methods for different types (getInteger, getLong, getFloat, ...) the method also got renamed to getString().

But since we agreed during a discussion (somewhere at the list) that the explicit convenience methods are not worth it we should also move the method back to getValue(String key).

**Comment by Emily-Jiang** [comment]
The reason getInteger, getLong was removed is that they are less frequently used and can use getValue to achieve. However, for getString(), it is frequently used. I recommend this one is to be different from getValue. This getString should not go through conversion. Maybe, we can change this method to be String getRawValue() or getString() with a clear javadoc to specify the return value.

**Comment by struberg** [comment]
but getString is effectively an overload of the more generic T getValue(String key, Class<T> type); 
Let's ask the broader community what they think is better.

**Comment by Emily-Jiang** [comment]
I would like to state getString to get the raw string without being converted, which is different from getValue(String key, Class type).

**Comment by emilyjiang** [comment]
I suggest to change this method to getRawString to make it clearer.

**Comment by OndrejM** [comment]
I like what Mark suggests - getValue(key) is really only an overload of getValue(key, String.class) - in both cases it is evident there is no conversion as the raw config values are always strings (so far). I also like getStringValue(key), but getRawString(key) sounds a bit weird and technical for a method we expect to be used very often.

**Comment by Emily-Jiang** [comment]
@OndrejM There is little value to keep getString or getValue if you can get the same thing from getValue(key, String.class). getRawString is to return a string that is in raw format and bypasses String converter. In this circumstances, you need to retrieve the raw value without going through String converters, such as for debug purpose.

**Comment by Emily-Jiang** [comment]
All I want is to have a method to return a raw string without being through a String converter. That is my use case.

**Comment by OndrejM** [comment]
I get it now, @Emily-Jiang, and agree.
However, I wouldn't mind having both methods, the second one just for less typing, but it would also help clarify the raw method, because I'm afraid people could use it instead of getValue(key, String.class) which is much longer (you know developers, that are sometimes too much lazy). Or we could move getRawString a layer deeper, into another less frequently used interface, not sure.

**Comment by Emily-Jiang** [comment]
So the proposal is
```
Optional<String> getValue(String) => a short hand for the following getValue method. Maybe change the current getString to getValue better?
Optional<T> getValue(String, Class<T>)
String getRawString(String)
```
