### ISSUE TITLE
TCK: MissingValueOnObserverMethodInjectionTest fails for a different reason

### ISSUE THREAD

**Issue by mkouba** [eclipse/microprofile-config#543]
**Describe the bug**
`org.eclipse.microprofile.config.tck.broken.MissingValueOnObserverMethodInjectionTest` asserts a `DeploymentException`. However, since the `ConfigObserver` bean is `@ApplicationScoped` (must be proxyable) and `final` (unproxybale type) the deployment fails but for a different reason:
https://github.com/eclipse/microprofile-config/blob/master/tck/src/main/java/org/eclipse/microprofile/config/tck/broken/ConfigObserver.java#L40

**Comment by mkouba** [comment]
Actually, it seems that the bean class is final and declares private no-args constructor, ie. unproxyable, but the observer method is static. That's very confusing. The truth is that a CDI container should only validate bean types used for injection points but what's the point of `@ApplicationScoped`?

**Comment by dmlloyd** [comment]
@ljnelson ?

**Comment by ljnelson** [comment]
Happy to make any changes needed.  What's the recommendation?

**Comment by mkouba** [comment]
Ideally, a test like this should rely on minimum features and if possible avoid "unusual" features. In this particular case, pls remove the final flag from the `ConfigObserver` class and use an ordinary observer method instead of the static one.
