### ISSUE TITLE
URL.equals() is not a 100% reliable method to use in a TCK

### ISSUE THREAD

**Issue by tevans78** [eclipse/microprofile-config#549]
There are a number of tests which rely on two URLs being equal and use the standard URL.equals() method to check that. However, the equals method for a URL does not just do a simple comparison of the URL String. The javadoc says...
```
Two URL objects are equal if they have the same protocol, reference equivalent hosts, have the same port number on the host, and the same file and fragment of the file.

Two hosts are considered equivalent if both host names can be resolved into the same IP addresses; else if either host name can't be resolved, the host names must be equal without regard to case; or both host names equal to null.

Since hosts comparison requires name resolution, this operation is a blocking operation. 
```
It is possible for two URL instances to be correctly created using the same String but for URL.equals to return false if, for some reason, one of the URLs can not be resolved at runtime. This failure would probably be due to a momentary network issue and nothing to do with the MP Config implementation.

Clearly, this is an extreme edge case that we have only seen fail once, on AIX. While there are several tests that use URL, the test that failed for us was https://github.com/eclipse/microprofile-config/blob/dea55bee3f61f40703fc759f04d374c3ed6a19f2/tck/src/main/java/org/eclipse/microprofile/config/tck/ArrayConverterTest.java#L931

The stack trace was
```
testUrlArrayInjection_EE7_FEATURES:
      java.lang.AssertionError: Lists differ at element [0]: http://microprofile.io != http://microprofile.io expected [http://microprofile.io] but found [http://microprofile.io]
at org.testng.Assert.fail(Assert.java:94)
at org.testng.Assert.failNotEquals(Assert.java:496)
at org.testng.Assert.assertEquals(Assert.java:125)
at org.testng.Assert.assertEquals(Assert.java:551)
at org.testng.Assert.assertEquals(Assert.java:670)
at org.testng.Assert.assertEquals(Assert.java:727)
at org.eclipse.microprofile.config.tck.ArrayConverterTest.testUrlArrayInjection(ArrayConverterTest.java:764)
```

**Comment by dmlloyd** [comment]
Yes this is definitely a bug.  Thanks for the report!

**Comment by Emily-Jiang** [comment]
Since URL.equals() performs DNS resolution, it was advised not to use it. What people think if we use URI.equals() instead?
