### ISSUE TITLE
Create TCK tests for Date etc

### ISSUE THREAD

**Issue by struberg** [eclipse/microprofile-config#55]
This is related to #28.
We should also have TCK test for each of the mentioned types.

**Comment by keilw** [comment]
How many are those?

- java.util.Date, etc.
- java.time
- java.util.concurrent.TimeUnit, too?

**Comment by Emily-Jiang** [comment]
+ *     <li>Duration</li>
+ *     <li>LocalDateTime</li>
+ *     <li>LocalDate</li>
+ *     <li>LocalTime</li>
+ *     <li>OffsetDateTime</li>
+ *     <li>OffsetTime</li>
+ *     <li>Date</li>
+ *     <li>Instant</li>

**Comment by keilw** [comment]
Thanks, so `Date` would be the one in java.util, correct?

**Comment by keilw** [comment]
If the ordinal gets changed to a double as David suggested, there has to be some comma and locale consideration there as well.

**Comment by Emily-Jiang** [comment]
After Mark's PR, we still need to add test to cover the following:
OffsetDateTime
OffsetTime
Date
Instant

**Comment by struberg** [comment]
I've now also re-added a test for Custom Converters. 
We still had the DuckConverter in our codebase but it didn't get tested yet.
Fixed that now.
A few date types are still on the todo list.

**Comment by Emily-Jiang** [comment]
I have added the remaining tests.
