### ISSUE TITLE
How are SessionScoped beans supposed to work with java.lang.Optional?

### ISSUE THREAD

**Issue by svenhaag** [eclipse/microprofile-config#558]
Currently it does not seem possible to have optional values for session scopes CDI beans?!

According to: 
https://github.com/eclipse/microprofile-config/blob/master/spec/src/main/asciidoc/configexamples.asciidoc

someone always have to provide a default value.
==> `Optional` is not `Serializable`

Also this usage of `Optional` is questionable:
`void method(@ConfigProperty(name = "a.config.key") final Optional<String> value)){...}`
Optional should be used for return types only!

**Comment by Emily-Jiang** [comment]
@svenhaag In your issue, you asked how SessionScoped Beans supposed to work with `Optional`. The answer is that it can if you make the field of `Optional` as transient. 

> Also this usage of Optional is questionable:
void method(@ConfigProperty(name = "a.config.key") final Optional<String> value)){...}
Optional should be used for return types only!

I am not quite sure what you tried to demonstrate. If you do the following
`@Inject
void method(@ConfigProperty(name = "a.config.key") final Optional<String> value))
{...}`

It should work.

**Comment by svenhaag** [comment]
Thanks for your answer. Sure, I can make it transient but that only defers the problem. I would have to take care of serialization (writeObject/readObject), otherwise the config param would be gone. Alternativaly I must use javax.inject.Provider all the time which is otherwise not necessary and also comes with a performance penalty.

**Comment by Emily-Jiang** [comment]
@svenhaag The optionality is for some properties that might have not got value assigned. The best practices is that you should provide default value. If you do need to have optional value, you can use programmatic lookup e.g. `ConfigProvider.getConfig.getOptionalValue()` instead of injection on your `SessionScoped` or `ConversationScoped` or any other passivation scoped beans.

The injection for the type `Optional` is fine for non passivation scoped beans though.

**Comment by svenhaag** [comment]
Thanks for your reply. I think this should be mentioned in the documentation. E.g. in the mentioned example:
https://github.com/eclipse/microprofile-config/blob/master/spec/src/main/asciidoc/configexamples.asciidoc

Cheers

**Comment by Emily-Jiang** [comment]
@svenhaag please review the above PR to see whether the text is helpful.

**Comment by svenhaag** [comment]
Thanks for adding this to the docu. However what happens if the bean gets serialized and deserialized? No re-injection will hapen on transient fields. You are ending up with a null value. Please see the [CDI spec](https://docs.jboss.org/cdi/spec/2.0/cdi-spec.html#injection_point).

> The isTransient() method returns true if the injection point is a transient field, and false otherwise. If the injection point represents a dynamically obtained instance then the isTransient() method returns true if the Instance injection point is a transient field, and false otherwise. If this injection point is declared as transient, after bean’s passivation, the value will not be restored. Instance<> injection point is the preferred approach.

**Comment by Emily-Jiang** [comment]
> Thanks for adding this to the docu. However what happens if the bean gets serialized and deserialized? No re-injection will hapen on transient fields. You are ending up with a null value. Please see the CDI spec.

That is the transient behaviour and nothing new. By the way, this is CDI knowledge and not something defined in Config. I don't really want to repeat what defined in CDI here.

**Comment by svenhaag** [comment]
Indeed you shouldn't but I think the suggested solution itself dangerous. Maybe it should be: `private javax.inject.Provider<Optional<String>>`?

**Comment by Emily-Jiang** [comment]
@svenhaag feel free to propose a PR to demonstrate how you wish the spec and tcks are to be updated.

**Comment by Emily-Jiang** [comment]
I'll close this as it has been nearly 3 years for no activities (no clear way forward). Please reopen it if you would like to suggest some improvement.
