### ISSUE TITLE
Clarify MP 2.0 getProperties and getPropertyNames

### ISSUE THREAD

**Issue by radcortez** [eclipse/microprofile-config#566]
**Description**

The following commit switched the default implementation from `getPropertyNames` to `getProperties`: https://github.com/eclipse/microprofile-config/commit/fafb7ce575210a3c17368d202a23aae46f166b2d, breaking `ConfigSource` compatibility.

Now, looking into the commit log, it not clear why this change was made.

Plus, the javadoc for `gePropertyNames` still references that is a default method:
https://github.com/eclipse/microprofile-config/blob/master/api/src/main/java/org/eclipse/microprofile/config/spi/ConfigSource.java#L123-L124

I'm not discussing the change itself, but I'm suspecting that this ended up there by accident? It was first added here https://github.com/eclipse/microprofile-config/commit/76d5a900672f1f6dcf4cbf6ae286e2cf032e6236, then removed here https://github.com/eclipse/microprofile-config/commit/0cf4c850e3418fa5edffb2a0a8fb1452c8fbfb2e to later reappear in https://github.com/eclipse/microprofile-config/commit/fafb7ce575210a3c17368d202a23aae46f166b2d with a commit log not related with the change.

This seems to be originated from #431.

I would like to clarify is this change is supposed to be there, if so we need to fix the java docs, if not we need to revert it.

**Comment by Emily-Jiang** [comment]
The changes are intended. The javadoc needs to be updated to reflect the changes. I'll do the fix shortly. Thanks @radcortez for noticing it!

**Comment by Emily-Jiang** [comment]
> I'm not discussing the change itself, but I'm suspecting that this ended up there by accident? It was first added here 76d5a90, then removed here 0cf4c85 to later reappear in fafb7ce with a commit log not related with the change.
The reason the commit was reverted from last release and then delivered now is that the change breaks backward compatibility. Therefore, it was not excluded from last minor release.

**Comment by Emily-Jiang** [comment]
fixed by #568
