### ISSUE TITLE
Support BitSet look up out of box

### ISSUE THREAD

**Issue by Emily-Jiang** [eclipse/microprofile-config#570]
As a:

- [x] Application user/user of the configuration itself
- [ ] API user (application developer)
- [ ] SPI user (container or runtime developer)
- [ ] Specification implementer

...I need to be able to:

directly inject or programmatically look BitSet in my java class without providing a converter myself.

...which enables me to:

Specify a bitset in a configsource and then I can look up from my java class
bits=10001

`@Inject @ConfigProperty(name="bits") BitSet bits;`

**Comment by radcortez** [comment]
Isn't this type too specific for a built in converter?

**Comment by Emily-Jiang** [comment]
> Isn't this type too specific for a built in converter?

What do you mean?

**Comment by tomas-langer** [comment]
Why `BitSet` specifically? There are a lot of classes that could be supported by built-in converters such as:

- `BigDecimal`
- `BigInteger`
- all the `java.time` classes
- `Path`
- `Charset`
- `URI`
- `URL`
- `Pattern`
- `UUID`
- all old time classes, such as `Date`, `Calendar`, `TimeZone`....

And probably a lot others. I would argue there are some much more widely used than `BitSet`

**Comment by Emily-Jiang** [comment]
@tomas-langer most of the converters you mentioned are already supported and they are under automatic converter category. See the category details [here](https://download.eclipse.org/microprofile/microprofile-config-1.4/microprofile-config-spec.html#_automatic_converters). In more details,



If no built-in nor custom Converter exists for a requested Type T, an implicit Converter is automatically provided if the following conditions are met:

    The target type T has a public static T of(String) method, or

    The target type T has a public static T valueOf(String) method, or

    The target type T has a public static T parse(CharSequence) method : **all of java.time classes**

    The target type T has a public Constructor with a String parameter : **BigDecimal, BigInteger, URI, URL**

This leaves UUID, Charset, and Pattern.

For the old time classes, I think the java.time is more preferred and they become legacy. I suggest not to do anything for them. I will open another issue to support UUID, Charset and Pattern as built-in converters.

In the meanwhile, I'm going to close this issue of adding Bitset as built-in converter since not many people are keen with this.

**Comment by Emily-Jiang** [comment]
See #604 @tomas-langer please comment if you think more converters are to be added. I believe I have address your comments.
