### ISSUE TITLE
Clarification about default ConfigSources ordinal

### ISSUE THREAD

**Issue by NicoNes** [eclipse/microprofile-config#573]
Hi,

The spec states that:

> a special property config_ordinal can be set within any built-in ConfigSource implementation

Does it means that default config sources MUST honor this special property when present otherwise use the respective default ?

Thanks

**Comment by radcortez** [comment]
Hi @NicoNes 

From my understanding yes. We should not treat default sources differently, or we will run into consistency issues :)

**Comment by NicoNes** [comment]
Hey @radcortez 

Thanks for the anwser. I agree with you. 

Actually I was asking for this clarification because SmallRye config implementation you seems to contribute to does not honor this this spec requirement:
- `SysPropConfigSource` ordinal is always 400 
- `EnvConfigSource` is always 300.
- `PropertiesConfigSource` is OK and behave as expected.

It's maybe the wrong place to talk about it, let me know if I'm right or not and if you want me to open and issue on SmallRye config project.

Thanks

**Comment by radcortez** [comment]
Ahaha, I was actually wondering if SmallRye was doing that when I've answered. I guess there is no TCK for this, so we probably need to add it as well.

I'll have a look to see if I can come up with a fix.

**Comment by Emily-Jiang** [comment]
The spec allows end users to set the ordinal for the default config sources. It suggests we should add TCKs to ensure this behaviour.

**Comment by Joseph-Cass** [comment]
I've made a SmallRye issue for this: https://github.com/smallrye/smallrye-config/issues/401
