### ISSUE TITLE
Add ConfigSource.getDefaultOrdinal() 

### ISSUE THREAD

**Issue by NicoNes** [eclipse/microprofile-config#574]
**Description**

Hi guys,

The spec states that:

> Note that a special property config_ordinal can be set within any built-in ConfigSource implementation. The default implementation of getOrdinal() will attempt to read this value. If found and a valid integer, the value will be used. **Otherwise the respective default value will be used.**

And to handle it properly in our custom built-in ConfigSources we often use following or similar boilerplate:

```
 @Override
   public int getOrdinal() {
      String configOrdinal = getValue(CONFIG_ORDINAL);
      if(configOrdinal != null) {
          try {
              return Integer.parseInt(configOrdinal);
          }
          catch (NumberFormatException ignored) {

          }
      }
      return getDefaultOrdinal();
  }

   public int getDefaultOrdinal() {
      return this.defaultOrdinal;
   }
```
 So I was wonderwing if a change to default `ConfigSource.getOrdinal()` could be made to invoke another default method `getDefaultOrdinal` that will return `ConfigSource.DEFAULT_ORDINAL` by default and that could be overriden by ConfigSource implementors easily instead of the boilerplate.

* Fixes 

The code will looks like:

```
 @Override
   default int getOrdinal() {
      String configOrdinal = getValue(CONFIG_ORDINAL);
      if(configOrdinal != null) {
          try {
              return Integer.parseInt(configOrdinal);
          }
          catch (NumberFormatException ignored) {

          }
      }
      return getDefaultOrdinal();
  }

   default int getDefaultOrdinal() {
      return DEFAULT_ORDINAL;
   }
```

WDYT ?

Thanks

**Comment by radcortez** [comment]
Hum, I'm mostly wondering if `getOrdinal` should have any code at all, other than returning the `DEFAULT_ORDINAL`.

The behaviour around the `CONFIG_ORDINAL` configuration is just an implementation detail in my opinion. The way the method is implemented right now requires consumers to worry about this details, like you are doing.

I would probably propose to drop the entire implementation, have `getOrdinal` return only the `DEFAULT_ORDINAL` and the Config implementation handles the rest. It may even be better for the implementations, since they can handle this on their side.

**Comment by NicoNes** [comment]
Well, droping the entire implementation of `getOrdinal` to return only 'DEFAULT_ORDINAL' definitively makes sense to me.

> The behaviour around the CONFIG_ORDINAL configuration is just an implementation detail in my opinion. The way the method is implemented right now requires consumers to worry about this details, like you are doing.

I agree with you this is more an implementation concern than a spec one.

**Comment by Emily-Jiang** [comment]
> I would probably propose to drop the entire implementation, have getOrdinal return only the DEFAULT_ORDINAL and the Config implementation handles the rest. It may even be better for the implementations, since they can handle this on their side.

Not really. The getOrdinal returns the value of config_ordinal it set in the configsource. The default one is only used if the property config_ordinal is missing.

**Comment by NicoNes** [comment]
> Not really. The getOrdinal returns the value of config_ordinal it set in the configsource. The default one is only used if the property config_ordinal is missing.

Yes and in many cases when `config_ordinal` property  is not set in the configsource, we have to return the **ConfigSourceImpl respective default ordinal**  not the `ConfigSource.DEFAULT_ORDINAL` to follow the spec.
That why implementors needs to use the boilerplate I talked about instead of relying on default implementation of `ConfigSource.getOrdinal()` that becomes useless.

So that's why I think that something should be changed in current default implementation of `ConfigSource.getOrdinal()` so that it becomes more usefull.

**Comment by radcortez** [comment]
Well if an implementor of a `ConfigSource` overrides `getOrdinal` to set whatever original with a simple implementation just retuning a number and later on he wants to override it with the config property he can't because he missed that behaviour in the method implementation.

That is why this method should only return the numeric value of the ordinal and the spec implementation should handle the logic about checking the configuration via property or via implementation of the method in the `ConfigSource`.

**Comment by NicoNes** [comment]
> Well if an implementor of a ConfigSource overrides getOrdinal to set whatever original with a simple implementation just retuning a number and later on he wants to override it with the config property he can't because he missed that behaviour in the method implementation.

Just to be sure to undertsand what you mean: If he missed that behavior when he implements the method it's not because of the spec API. Actual default implementation of `ConfigSource.getOrdinal()` does not prevent implementor that override this method to reimplement it following the specs requirement right ?

Well I was reading at the JAVA doc of `ConfigSource.getOrdinal()` and things are clear about the default implementation behavior.
It is clearly stated that if `config_ordinal` is not present then **`ConfigSource.DEFAULT_ORDINAL`** will be used not the **ConfigSourceImpl respective default ordinal** as I thought it was when I opened the issue.
More the JAVA doc states that this method may be overriden by ConfigSourceImpl to provide a different behavior.
So it's up to implementor to override this method in respect of the spec requirement for any default or built-in ConfigSource. Any other user ConfigSourceImpl are free to override this method or not since there is no spec requirement for this kind of `ConfigSource`.

So to me things are OK are they are now,  I think Imisinterpreted the JAVADOC and the spec sorry guys.

**Comment by radcortez** [comment]
Yes.

**Comment by NicoNes** [comment]
So @radcortez  if you also think there is noting more to talk about and that things are OK as they are, let me know if I can close the issue ?

Thanks
