### ISSUE TITLE
Valid characters in config property names

### ISSUE THREAD

**Issue by xorye** [eclipse/microprofile-config#585]
**Description**

Does the microprofile-config specification define what kind of characters (alphanumeric, symbols, etc.) are allowed in config property names? I couldn't find any information about this in the specification: https://download.eclipse.org/microprofile/microprofile-config-1.4/microprofile-config-spec.pdf.

I'm thinking there isn't such restriction?

**Comment by radcortez** [comment]
Hi @xorye.

I believe there are no restrictions. The only limitation is on each of the ConfigSource itself. For instance, Environment variables  do not support all characters, so for that case some mapping rules are provided by the spec. Check here:
https://github.com/eclipse/microprofile-config/blob/adf90d7f1e674b265d6fa812f9667b1b573c8b8c/spec/src/main/asciidoc/configsources.asciidoc#L63

**Comment by xorye** [comment]
Awesome, thank you for the feedback @radcortez
