### ISSUE TITLE
should we use int or float as ordinal numbers?

### ISSUE THREAD

**Issue by struberg** [eclipse/microprofile-config#59]
Idea from David from the microprofile-google group:

The ordinal as int might not be as easy to squeeze something inbetween. 
Should we move this magic number to being a float?

**Comment by struberg** [comment]
No comment so far?
Generally a float as magic number is a good idea. But in this very case it might be overkill. 
We have plenty of space to fit in. Any other opinions? 
I'll leave this open for further 72h before I gonna close it - txs!

**Comment by OndrejM** [comment]
I don't mind leaving integers, if we plan to provide more options for sorting config sources later. Floats would help in some edge cases, but I believe we can find better ways to approach them.

**Comment by Emily-Jiang** [comment]
I will prefer to leave it as integer. Here are the reason;
1. Priority uses integer. We can use annotations for the cases where the ordinal is specified on the config source classes.
2. The same priority only cause issues with the same property key. The chance is small. 
3. I commented on another ticket somewhere. I propose to order by ordinal. If the ordinal is the same, we should then order by config name. In this case, there is no clash.

**Comment by struberg** [comment]
yes perfectly fine for me.

**Comment by Emily-Jiang** [comment]
good. We can also close #66 with javadoc update on sorting of config sources. I will get it done soon if no other objections.

**Comment by Emily-Jiang** [comment]
We should just use int as it is commonly accepted approach.
