### ISSUE TITLE
Add the option to use default value into properties file

### ISSUE THREAD

**Issue by otaviojava** [eclipse/microprofile-config#592]
# **Description**

The goal is to allow us to overwrite some configuration keys, so we can externalize the configuration, for example, for the production environment, and also provide a default value for development. 

## **Use cases**

In the properties files we can set: 

The above example will default to localhost and port 8080 if no value is found (rather than throwing an exception).

```
endpoint=http://${SERVER:localhost}:${PORT:8080}/
```
The above example will default to localhost and port 8080 if no value is found.

## Implementations

* [Micronaut](https://docs.micronaut.io/latest/guide/config.html)
* [Spring](https://docs.spring.io/spring-boot/docs/current/reference/html/spring-boot-features.html#boot-features-external-config)

**Comment by radcortez** [comment]
Hi @otaviojava there is already a PR with a proposal to add it into the spec.

Please, check here and contribute :)

https://github.com/eclipse/microprofile-config/pull/577

**Comment by otaviojava** [comment]
Thank you @radcortez
