### ISSUE TITLE
New method in 2.x should be default

### ISSUE THREAD

**Issue by tomas-langer** [eclipse/microprofile-config#593]
**Describe the bug**

When I upgraded to `2.0-M1`, I got a compilation error in my `ConfigSource`s, because method `getPropertyNames` is not implemented.
As this is a new method and there is a reasonable default, can you please add it as a default method to the interface?
```java
default Set<String> getPropertyNames() {
    return getProperties().keySet();
}
```
Even though this is a new major version, keeping reasonable backward friendliness would be helpful.

**Comment by tomas-langer** [comment]
I have revisited the old interface in 1.4, and it actually was a default method. I am confused why this was removed?

**Comment by radcortez** [comment]
Hi @tomas-langer 

Please check https://github.com/eclipse/microprofile-config/issues/431. It contains the discussion that lead to the change.

**Comment by tomas-langer** [comment]
@radcortez I have read through the thread, and I do not see an explanation why a backward incompatible change was made. 

This change renders all existing config sources useless (unless they implement the method explicitly).

The original default implementation was reasonable and documented - and if you need a different approach (due to performance, mutability), it is really easy to implement.

**Comment by radcortez** [comment]
Hi @tomas-langer, I didn't participate in the discussion, so my knowledge about this is limited.

From my understanding the idea was to deprecate `org.eclipse.microprofile.config.spi.ConfigSource#getProperties` since it not used in the specification and there are no use cases for it.

**Comment by tomas-langer** [comment]
At least in the milestone the `getProperties` is not deprecated, making this backward incomp. change wrong.
Once it is deprecated, I understand the intention to remove the `default`, yet it still makes a major issue for any custom config source in use.

Options I see:

1. Deprecate `getProperties` and remove default (I think this is not a good choice for continuity)
2. Deprecate `getProperties` and have `default` returning a different value (such as an empty set)
3. Revert back to 1.4 code (if deprecation of `getProperties` is not planned)

**Comment by radcortez** [comment]
@Emily-Jiang you made the original change. What do you think?

**Comment by Emily-Jiang** [comment]
@tomas-langer the default method was not deprecated but it was updated to be an abstract method. The default was removed because we want to support lazy lookup instead of eagerly invoke getProperties(). You can reply on getValue() to look up a particular property. It was labelled as breaking changes in the Spec.

**Comment by tomas-langer** [comment]
@Emily-Jiang - and as I said in my comment - this removal of default is hurting any user and I think it is not justified, especially if `getProperties()` stays in.

**Comment by Emily-Jiang** [comment]
@tomas-langer I don't quite undestand why you said it is not justified. It was concluded via #431. Besides it is clearly documented as breaking changes, so the customers have to implement this method. By the way, there is a tendency in the future we might deprecate getProperties and get it removed.

**Comment by tomas-langer** [comment]
One of the side effects of this change - TCK tests of other MP specifications fail because they declare a custom `ConfigSource` without this method. So practically as soon as you upgrade an implementation to Config 2.0, other specs fail to run TCK tests.

By not justified I mean - this is a useless breaking change. There is no need to force people to implement a method if they decided it does not deserve custom implementation. 

I understand the need for breaking changes - when a method signature is bad, you need additional parameters etc. But in this case there is no API need for it. It is just "we felt like default implementation was not so good for our users so we removed it", practically hurting every single user that implemented a custom `ConfigSource`, including other MP specs.

**Comment by Emily-Jiang** [comment]
@tomas-langer I think I have explained the reason for this change is under #431 . If we provide all of the defaults, end users will go ahead without doing any implementation. By updating the method in question to non-default will force the implementors to think carefully on what config property they would like to retrieve or filter out etc. Besides, we clearly documented this is a breaking change and provided suggestion. A lot of people was involved in the previous discussion.

**Comment by radcortez** [comment]
I'm closing this one, since we released with this change and not much we can do about it now. Unless we want to revert the change in 2.1. Please reopen if this is the case.
