### ISSUE TITLE
ConfigProvider registerConfig vs setConfig

### ISSUE THREAD

**Issue by struberg** [eclipse/microprofile-config#61]
Which name is better?

My original method name was `registerConfig`. Because one 'registers' a specific config within the Application.

Emily changed this to `setConfig`.
Imo this sounds  a bit too bean like (which it isn't).

Any opinion?

**Comment by Emily-Jiang** [comment]
I'm fine with changing to registerConfig. To make it pair up with release, the releaseConfig should be deRegister(Classloader classloader).
