### ISSUE TITLE
@ConfigProperties usages

### ISSUE THREAD

**Issue by radcortez** [eclipse/microprofile-config#629]
**Description**

I'll try to summarize here the multiple usage options of `@ConfigProperties`so we can analyze them and confirm we want to support all of these:

# 1 - No @ConfigProperties Annotation in Class

```java
class Server {
  String hostname;
}

@Inject
@ConfigProperties
Server server

@Inject
@ConfigProperties(prefix = "server")
Server server;
```

This allows to use any class (requires at least a no args constructor), which may even be from outside of the scope of the user code. In this case, the `@ConfigProperties` is required at the injection point level, either with a supplied prefix or empty prefix.

# 2 - @ConfigProperties Annotation in Class

```java
@ConfigProperties
class Server {
  String hostname;
}

@ConfigProperties(prefix = "server")
class Server {
  String hostname;
}

@Inject
Server server;
```

The class sets the `@ConfigProperties` annotation either with a supplied prefix or empty prefix. We don't require additional information at the injection point, so a simple `@Inject` is enough.

# 3 - @ConfigProperties Annotation in Class and Injection Point

```java
@ConfigProperties
class Server {
  String hostname;
}

@ConfigProperties(prefix = "server")
class Server {
  String hostname;
}

@Inject
@ConfigProperties
Server server;

@Inject
@ConfigProperties(prefix = "cloud")
Server server;
```

The class sets the `@ConfigProperties` annotation either with a supplied prefix or empty prefix. The `ConfigProperties` annotation at the injection point is used solely to override the prefix from the class. A single `@ConfigProperties` will always override the prefix of the Class with an empty prefix.

**Comment by radcortez** [comment]
My main concern over this is the inconsistent coding. Depending on the scenario I may require to use or not use `@ConfigProperties` at the injection point. In the end I believe this will be a source of confusion for consumers of the API.

Also, I know that we added the ability to override the prefix at the injection point. If I want to use `@ConfigProperties` for extra clarity, so I know what is my bean type, I override my prefix with an empty value and I have to redefine the prefix again.

**Comment by Emily-Jiang** [comment]
We only should support option 3.
Both Option 1 and 2 voilate [CDI spec Qualifier section](https://jakarta.ee/specifications/cdi/2.0/cdi-spec-2.0.html#qualifiers)
Option 1: the bean `Server` has no qualifer. When injecting the object with qualifer `ConfigProperty`, it clearly does not work based on CDI spec.
Option 2: the bean `Server` has a qualifier `ConfigProperties`, but when you inject `Server` with the `default` qualifier, it clearly does not match either.
Option 3: correct. The bean has a qualifier `ConfigProperties` and when you inject `Server`, you should always use `ConfigProperty` qualifier with a specified `prefix` if you like.

**Comment by radcortez** [comment]
I agree.

I'll probably add that if `@ConfigProperties` used at the injection point without a prefix, this will not override the prefix at the class level with an empty one.

**Comment by Emily-Jiang** [comment]
> I agree.
> 
> I'll probably add that if `@ConfigProperties` used at the injection point without a prefix, this will not override the prefix at the class level with an empty one.

Absolutley. That is why the prefix should be `NonBinding`.

**Comment by radcortez** [comment]
Now, I agree to make the prefix `NonBinding`. The way it was before was just confusing.
