### ISSUE TITLE
ConfigSource#getId() vs getName()

### ISSUE THREAD

**Issue by struberg** [eclipse/microprofile-config#63]
We started this discussion and then the changes got made without much community feedback.

What is more self-explaining? 

First let me explain what that method used to do in DeltaSpike:
If you log out some info about picked up config (from which ConfigSource did a value effectively get picked up) or if you need this info via JMX or some admin page, then you need to give all the ConfigSources a 'name'. Technically it doesn't even need to be unique (of course it is better if you are searching for an error), but the Config system itself doesn't require it. The name is really just used for helping the admin to better understand the current state of his system.

**Comment by Emily-Jiang** [comment]
change getId to getName.
