### ISSUE TITLE
Conversion example inconsistent with conversion description

### ISSUE THREAD

**Issue by Azquelt** [eclipse/microprofile-config#633]
**Describe the bug**

The Config Value Conversion Rules section of the spec includes this:

Value | Convert To | Method | Result
---|---|---|---
| `"\,"`| String| getValue| `"\,"`
| `"\,"`| String[]| getValue| throws `NoSuchElementException`
| `"\,"`| String| getOptionalValue| `Optional.of("\,")`
| `"\,"`| String[]| getOptionalValue| `Optional.empty()`
| `"\,"`| String| getOptionalValues| `Optional.empty()`

I think this is wrong. Since `\` is used as an escape character, the list style conversions should treat the `,` as a literal character, rather than a separator, so the result for `getValue` with `String[]` would be `{","}`.

I'm unsure whether this table should also have code tags around almost every entry. (My only doubt here is that `\` is also the string escape in Java, so it could be confusing as to whether we're using Java's string syntax or not if it's formatted as code)

**Comment by Azquelt** [comment]
I note that this case was listed as 3(b) in #446, and I'm not looking to reopen that discussion, but it does seem like the [example][spec-example] in the spec contradicts the description of the rules [here][spec-arrays] and [here][javadoc-arrays].

When I read the example, I assumed it was just a copy-paste error, but I'm happy for the other parts of the spec to change if the example is correct.

[spec-example]:https://github.com/eclipse/microprofile-config/blob/master/spec/src/main/asciidoc/configexamples.asciidoc#config-value-conversion-rules
[spec-arrays]:https://github.com/eclipse/microprofile-config/blob/master/spec/src/main/asciidoc/converters.asciidoc#array-converters
[javadoc-arrays]:https://github.com/eclipse/microprofile-config/blob/master/api/src/main/java/org/eclipse/microprofile/config/spi/Converter.java#L124-L133

**Comment by Azquelt** [comment]
Smallrye Config has a specific check to remove a value of `,` from the array as the last step of converting the value: https://github.com/smallrye/smallrye-config/blob/master/implementation/src/main/java/io/smallrye/config/Converters.java#L694

**Comment by Emily-Jiang** [comment]
@Azquelt in this table you quoted, can you point out which row is wrong. Do you just say `\,` 4b is inconsistent or any row in the table you quoted is wrong?

**Comment by Azquelt** [comment]
Sorry, I just realised that github's formatting had removed my backslashes, making it make no sense. I've now corrected it.

I think that rows 2, 4 and 5 of the part of the table that I quoted are wrong.

They should be

Value | Convert To | Method | Result
---|---|---|---
| `"\,"`| String[]| getValue| `{","}`
| `"\,"`| String[]| getOptionalValue| `Optional.empty({","})`
| `"\,"`| String| getOptionalValues| `Optional.empty(List.of(","))`

**Comment by Emily-Jiang** [comment]
The suggestion from @Azquelt sounds reasonable to me, since `\` is an escape character for array of strings. @radcortez @jbee thoughts?

**Comment by jbee** [comment]
Sounds reasonable to me.

**Comment by radcortez** [comment]
Ok.

**Comment by Emily-Jiang** [comment]
Thanks @radcortez @jbee! Let me propose a PR to get it fixed.
