### ISSUE TITLE
Release 2.0

### ISSUE THREAD

**Issue by pavolloffay** [eclipse/microprofile-config#639]
The MP 4.0 is planned for November 10. 

The MP-OpenTracing 2.0 spec includes MP-Config 2.0 (currently RC). The OpenTracing spec 2.0 is going to be included in MP 4.0, however the spec should depend on the final config spec (2.0). When do you plan to cut the final release? Note that it should give enough time for OpenTracing spec to review and release (1 week).

**Comment by Emily-Jiang** [comment]
@pavolloffay once we have a go ahead signal, we will release MP Config 4.0. I think we would like to be released a couple of days before the rest of MP specs. We will announce formally and then the rest specs can change their dependency and then perform the final release.

**Comment by pavolloffay** [comment]
thanks @Emily-Jiang please ping me once the release is out.

**Comment by Emily-Jiang** [comment]
done now.
