### ISSUE TITLE
common groupId for all specs and tcks

### ISSUE THREAD

**Issue by struberg** [eclipse/microprofile-config#64]
Currently we have a groupId of `org.eclipse.microprofile.config.specs` but it should imo be `org.eclipse.microprofile.specs` instead.
Same for tcks.

The reason is that people will just have a single folder in maven.central where they can find all microprofile specs.

**Comment by keilw** [comment]
I would not do that as modules should be self-contained. Whether you use a pure Microprofile or SCS (Self-Contained Systems) pattern or a mix of both, "self-contained" also means each module should be independent where possible, so updating config does not force others to be chaged. If the groupId was `org.eclipse.microprofile.config.api `or `org.eclipse.microprofile.config.specs `IMO is up to each module, but a general purpose module like `org.eclipse.microprofile.core` (or "specs") should only be for reusable aspects that are component-neutral, e.g. an independent annotation (though I would rather call that `org.eclipse.microprofile.annotation` or `org.eclipse.microprofile.annotations` than just "specs")

**Comment by keilw** [comment]
IC what you mean with the "specs" artifactId.
https://github.com/eclipse/microprofile-config/blob/master/spec/pom.xml has no binary deliverables, so it cannot be seen as a module of its own. Should all "document/spec" modules be preferred in one artifactId, for that it seems OK. For a TCK testing Config or other modules, I would certainly not mix them, but stick to `org.eclipse.microprofile.config.tck` or just `org.eclipse.microprofile.config` (and keep all artifacts under the module groupId)

**Comment by struberg** [comment]
moving them to the following groupId. Please speak out if you find a better name.
<pre>
org.eclipse.microprofile.apis
</pre>
