### ISSUE TITLE
MP Config SEO

### ISSUE THREAD

**Issue by Joseph-Cass** [eclipse/microprofile-config#641]
**Description**
When I search for "MP Config" in Google, the MicroProfile Config GitHub "landing page" (the README) doesn't show on the first page.

**Use cases**
Searching "MP Config", "MP Config Git", or "MP Config Github" into a search engine should return the [MicroProfile Config GitHub README page](https://github.com/eclipse/microprofile-config) high up the list, preferably first.

**Comment by Emily-Jiang** [comment]
I'm not sure what you are proposing here. MP is not a known acronym for MicroProfile. We call MicroProfile MicroProfile not MP.

**Comment by Joseph-Cass** [comment]
A couple of examples of MP being used: 
- https://projects.eclipse.org/projects/technology.microprofile/releases/mp-config-1.3/review
- https://github.com/eclipse/microprofile-config/milestone/7

OpenLiberty's feature name for `MicroProfile Config` is also `mpConfig`, so whether this is an official term or not I think people (like myself) are going to use it. 

I don't know much about Search Engine Optimisation, but I'm proposing that there should be something in place such that a search for "MP Config GitHub" returns the [MicroProfile Config GitHub page](https://github.com/eclipse/microprofile-config) as a result.

**Comment by Joseph-Cass** [comment]
For example, searching "MP fault tolerance" returns https://github.com/eclipse/microprofile-fault-tolerance as the first result

**Comment by Emily-Jiang** [comment]
I am going to close this one as this is not directly related to api/spec/tck updates.
