### ISSUE TITLE
Address copyright issue for generated pdf and html, as well as javadoc

### ISSUE THREAD

**Issue by Emily-Jiang** [eclipse/microprofile-config#654]
Based on the feedback from @kwsutter , we need to ensure:

The license for the specification source is Apache v2. That's fine and should be left that way. But, the generated Specification has to be EFSL licensed. The Apache v2 license is not sufficient for the generated Specification (pdf and html). So, this has to be updated before we are ready.

Similar comment for the Javadoc. The Java source code is Apache v2 licensed. But, the generated Javadoc has to be EFSL licensed. This is easily done by updating the footer for the javadoc. Here's an example of how we do this for Jakarta EE specs:
https://github.com/eclipse-ee4j/jakartaee-api/blob/211785b901de26bd3b708112fd0055ca70dadc86/pom.xml#L268

 The spec source keeps the Apache v2 or EPL or whatever license is used for developing the spec. But, the generated Spec should only only contain the EFSL. As an example, most all of the Jakarta EE specs source are EPL. But, the EPL is replaced with the EFSL when generating the PDF or HTML versions of the final specs and javadoc.

For an example for [spec license](https://raw.githubusercontent.com/eclipse-ee4j/jms-api/master/spec/src/main/asciidoc/messaging-spec.adoc)

**Comment by Emily-Jiang** [comment]
working on a fix now

**Comment by radcortez** [comment]
No need, I already have it done :)
