### ISSUE TITLE
SmallRye Compatible Certification Request for MicroProfile Config 2.0

### ISSUE THREAD

**Issue by radcortez** [eclipse/microprofile-config#656]
- [x] Organization Name ("Organization") and, if applicable, URL:<br/>
  Red Hat

- [x] Product Name, Version and download URL (if applicable):<br/>
  [SmallRye Config 2.0-RC3](https://repo1.maven.org/maven2/io/smallrye/config/smallrye-config/2.0.0-RC3/)

- [x] Specification Name, Version and download URL:<br/>
  MicroProfile Config 2.0

- [x] Public URL of TCK Results Summary:<br/>
  https://github.com/smallrye/smallrye-config/actions/runs/400792522

- [x] Java runtime used to run the implementation:<br/>
  Java 8 and 11

- [x] Summary of the information for the certification environment, operating system, cloud, ...:<br/>
  GH Actions - Ubuntu  

- [x] By checking this box I acknowledge that the Organization I represent accepts the terms of the [EFTL](https://www.eclipse.org/legal/tck.php).
- [x] By checking this box I attest that all TCK requirements have been met, including any compatibility rules.

**Comment by radcortez** [comment]
Since the template is going to be available per project, we can probably tailor it to default the Specification Name (or drop it).

**Comment by Emily-Jiang** [comment]
Thank you Reberto! At least, the template can have the spec name :o, which is known.

**Comment by radcortez** [comment]
Everything released!
