### ISSUE TITLE
Discuss whether having 2 keys in 2 ConfigSources with the same ordinal should lead to a DeploymentException?

### ISSUE THREAD

**Issue by struberg** [eclipse/microprofile-config#66]
Consider you have 2 ConfigSources with the same ordinal and they contain the same key. 
Should we consider this a deployment error and blow up with an Exception?

Or do we leave it to the impl to detect such a situation and just issue a warning?

**Comment by Emily-Jiang** [comment]
It is not an issue if we order the config source via the ordinal first  and then via the getName/getId.

**Comment by Emily-Jiang** [comment]
See my commit above.
