### ISSUE TITLE
 Broken link in Config 2.0 release notes

### ISSUE THREAD

**Issue by torrespro** [eclipse/microprofile-config#666]
In the Releases page: https://github.com/eclipse/microprofile-config/releases/tag/2.0

There is a link to the **Changelog** with the following URL -> https://download.eclipse.org/microprofile/microprofile-config-2.0/microprofile-config-spec.html#release_notes_20

That's a 404, the correct one is: https://download.eclipse.org/microprofile/microprofile-config-2.0/microprofile-config-spec-2.0.html#release_notes_20

**Comment by ederks85** [comment]
Hi Andrés,

Thanks for notifying us. I have updated the URL on the release page.

Edwin
