### ISSUE TITLE
[DISCUSS] move Config#getConfigSources back to returning an Array or List<ConfigSource> ?

### ISSUE THREAD

**Issue by struberg** [eclipse/microprofile-config#67]
Config#getConfigSources originally have been a ConfigSource[]  [1,2]

This got moved to an Iterable<ConfigSource>.
But that way we might end up loosing a few use cases.

The ConfigSources are sorted in a descending way. Means the ones with the highest ordinal are in first position (btw we should define this more precisely). Sometimes you need exactly this ordering. E.g. if you want to know the value of a single key then you iterate from the ConfigSource with the highest ordinal and once you find a value you are done.

But think about e.g. an admin UI as @starksm64 mentioned. In that case you want to start at the ConfigSource with the lowest ordinal and drop all the values into a big Map<String, String>. Then you take the next one and again just drop all the values into the map. Effectively overwriting the lower values IF they got also specified in a higher ordinal ConfigSource.

But for doing that you have to iterate in an ASCENDING way! With just an Iterable<ConfigSource> you cannot easily do that without having to repackage it, right? So what do we win with the Iterable over a good old array?

LieGrue,
strub

[1] https://github.com/struberg/javaConfig/blob/master/api/src/main/java/io/microprofile/config/Config.java#L85
[2] https://github.com/apache/deltaspike/blob/master/deltaspike/core/api/src/main/java/org/apache/deltaspike/core/api/config/ConfigResolver.java#L476

**Comment by gunnarmorling** [comment]
Yes, I also stumbled upon the return type of `Iterable`. That's most of the type not useful for callers of a method.

I'd return a `SortedSet`: set as no source should be in there only once, and sorted so Mark's ordering requirement is satisfied.

**Comment by struberg** [comment]
I now worked with it and Iterable is seriously fucked up for this use case.
We do not get 10000s of ConfigSources, so Iterable does not add any benefit.

Previously the code was:
allConfigSources.addAll(configSource.Provider.getConfigSources);
But now I have to do the 
Stream.of(StreamSupport.spliterattor(configSourceProvider.getConfigSources(),false)..stream(), anotherMessingSrream).flatMap(bla()).collect(toList() bla shit bla
and add this to the existing allConfigSoures list.

Sorry for the profanity, but that's batshit crazy

**Comment by struberg** [comment]
@gunnarmorling a SortedSet is semantically probably the most correct one. But that requires that the ConfigSource would need to implement the Comparator interface. So I think having a defined sort order and an unmodifyable List is probably the best

**Comment by struberg** [comment]
Or simply an array. Makes it immutable automatically.

**Comment by gunnarmorling** [comment]
How is an array immutable?

Using an interface type (Set) leaves more freedom to implementors, whereas
an array is a fixed type. I wouldn't go for arrays at this time and age
unless it's super perf-critical. Let's not make the API look like it's from
2002 ;)

**Comment by struberg** [comment]
Indeed you are right, moving to SortedSet.

**Comment by struberg** [comment]
gnn SortedSet has no index access, you need to resort again. And it's mutable.

**Comment by struberg** [comment]
sticking with Iterable after a discussion with Gunnar
