### ISSUE TITLE
[DISCUSS] Move Config#getPropertyNames() from Iterable<String> to Set<String> ?

### ISSUE THREAD

**Issue by struberg** [eclipse/microprofile-config#68]
An Iterable<String> does not allow to check whether a given key exists. A Set<String> would. 

Is this an issue for some use cases?

For completeness sake: The original design used to be Map<String, String> getAllProperties(); [1,2]

LieGrue,
strub

[1] https://github.com/struberg/javaConfig/blob/master/api/src/main/java/io/microprofile/config/Config.java#L76
[2] https://github.com/apache/deltaspike/blob/master/deltaspike/core/api/src/main/java/org/apache/deltaspike/core/api/config/ConfigResolver.java#L452

**Comment by Emily-Jiang** [comment]
I would like to keep Iterable, for the performance gain and unmodifiable status. Besides, you can easily use StreamSupport.stream(iterable.spliterator(), false) to find items.

**Comment by struberg** [comment]
But that would again create temp objects and is code one has to write. He could ofc stream the iterable and equals the key String. But don't we internally have this as Set anyway?
So what is the benefit of an Iterable over a Set when it in reality is a Set anyway?

**Comment by OndrejM** [comment]
I agree with Emily that Iterable is more performant, especially with custom config sources based on external resource (DB, webservice). Iterable enables to stream (using paging, cursors, etc.) the property names, while Set would require pulling all of them at once to fill the Set before the Set is returned.

**Comment by struberg** [comment]
Oki this argument sounds compelling. While in practice it will have little impact because the list of configured properties hopefully doesn't exceed 1000 entries, but I can see the point. So let's stick with Iterable for this one. ok?
