### ISSUE TITLE
The Spec and JavaDoc are inconsistent about String Converters

### ISSUE THREAD

**Issue by tevans78** [eclipse/microprofile-config#680]
The Converter JavaDoc lists a String Converter as being a built-in one;
https://github.com/eclipse/microprofile-config/blob/4bda7c776e00a3baf41af728215900e02485de2c/api/src/main/java/org/eclipse/microprofile/config/spi/Converter.java#L70

The Spec does not list a String Converter as being a built-in one;
https://github.com/eclipse/microprofile-config/blob/master/spec/src/main/asciidoc/converters.asciidoc#built-in-converters

In my original PR (https://github.com/eclipse/microprofile-config/pull/679), @Emily-Jiang suggested that a String Converter was an _automatic_ one and that it is the JavaDoc that should be changed. That seems fine to me.

**Comment by Emily-Jiang** [comment]
Thanks @tevans78 for reporting this! I think the javadoc mentioning String should be removed but missed when trying to remove the duplicate info from built-in converters when the same type is coverted by an automatic converter.
