### ISSUE TITLE
[DISCUSS] How to resolve same key names in multiple config sources

### ISSUE THREAD

**Issue by OndrejM** [eclipse/microprofile-config#69]
As per discussion in a hangout ([minutes here](https://docs.google.com/document/d/1X6Q9K28VNHhVRkVBFlbNa-ZMusxjCfmoA7--uJFHWx0/edit)), we haven't come to an agreement how to specify resolving a config property if it is defined in multiple config sources. This was also discussed later in #65, without any conclusion.

Points from the discussion worth to summarize here:

@viktorklang reminds that the original problem is overwriting of conflicting values - 
the target is to **enable overwrites**, but **prevent accidental overwrites**

@Emily-Jiang, @struberg, @viktorklang: we can come with namespace conventions to prevent accidental overwrites

In order to enable intentional overwrites, we need to 
 - specify a deterministic way to order the config sources to determine the one with the highest priority. 

The current API in the master branch ([here](https://github.com/eclipse/microprofile-config/blob/master/api/src/main/java/org/eclipse/microprofile/config/spi/ConfigSource.java#L58)) uses ordinals, which define a priority of a config source.

Some people (@ondrejm, @atsticks, @viktorklang) don't agree that this is the best solution and have suggested alternative solutions with an attempt to compare them and choose the best one.

Other solutions suggested (mentioned in the hangout and in the discussion in #65):

- ordinals
- external comparator
- naming (like in web-fragments)
- define a (hopefully obvious) tree/hierarchy for config sources
- ordinals defined optionally as a config property instead of by a method in the API, complemented by other solutions
- ordering specified by the order of config sources in config.xml, referenced by a unique id

**Comment by OndrejM** [comment]
I suggest that for every solution, the author creates a PR (including a test case) to demonstrate the idea. We can then discuss each idea separately and compare them in the discussion in this issue.

**Comment by struberg** [comment]
I think this ticket got clarified during out last hangout and we can close this ticket as resolved, right?

**Comment by viktorklang** [comment]
@struberg Apologies for the silence on my part—which clarification are you referring to?

@OndrejM (IME) The *key* to resolving accidental overrides is to have namespacing and usage-site deterministic order of resolution, the *key* to deliberate overrides is namespacing and usage-site *arrangement* of order of resolution. Conclusion: namespacing and usage-site deterministic, arrangeable, order is needed.

**Comment by struberg** [comment]
@viktorklang The main argument was that even if some overriding happened accidentally, then the Ops team still has ways to check where they came from and override the value in a higher ordinal ConfigSource. 
The only 'accident' which could happen is that the same config effectively get resolved in 2 ConfigSources which have the same ordinal. We could detect this at bootstrap (although not if values dynamically change during runtime).
See https://github.com/eclipse/microprofile-config/issues/66

**Comment by viktorklang** [comment]
@struberg values changing would be fine, keys changing wouldn't.

**Comment by OndrejM** [comment]
I'm OK to close this. I added my notes from the hangout into the calendar invitation here: https://plus.google.com/u/0/events/csi9l7mu3qporfhdst29osiipbc/103606775052569552781
