### ISSUE TITLE
Clarify usage of property expression in the code.

### ISSUE THREAD

**Issue by NicoNes** [eclipse/microprofile-config#705]
Hi guys,

As discussed here https://github.com/smallrye/smallrye-config/issues/601#issuecomment-865081956 with @radcortez , due to my understanding of the 2 following pararaphs of the spec, I was expecting the following code to work:

> Property expressions applies to all the methods in Config that performs resolution of a configuration property, including getValue, getValues, getConfigValue, getValues, getOptionalValue, getOptionalValues and getConfigProperties.

> Property expressions must also be applied to configuration properties injected via CDI. A default value defined via org.eclipse.microprofile.config.inject.ConfigProperty#defaultValue is not eligible to be expanded since multiple candidates may be available.

```
ConfigProvider.getConfig().getValue("${property1} ${property2}", String.class);
```
```
@Inject
@ConfigProperty(name = "${property1} ${property2}")
private String myProperty;
```

@radcortez explained to me that my understanding was wrong and now I feel like those two paragraphs are a bit misleading.
Don't you think that hey should be removed from the spec since the behavior they try to explain is pretty obvious and does not really need to be mentionned ? Maye a code snippet as follow would be enough:

`@Inject @ConfigProperty(name="server.url") String serverUrl; \\Returns http://example.org:8080/foo`
`@Inject @ConfigProperty(name="server.backup.url", defaultValue="server.url") String serverUrl; \\Returns server.url`
`String serverUrl= ConfigProvider.getConfig().getValue("server.url", String.class); \\Returns http://example.org:8080/foo`

WDYT ?

Thanks

**Comment by Emily-Jiang** [comment]
@NicoNes the expression only works on the config values not the config names. Config names are fixed and not changable. Which lines in the spec do you feel it suggests the config names support property expression?

**Comment by NicoNes** [comment]
@Emily-Jiang 

- Lines 64 to 67 in https://github.com/eclipse/microprofile-config/edit/master/spec/src/main/asciidoc/property-expressions.asciidoc

> Property expressions applies to all the methods in `Config` that performs resolution of a configuration property,
> including `getValue`, `getValues`, `getConfigValue`, `getValues`, `getOptionalValue`, `getOptionalValues`
> and `getConfigProperties`. The methods `getValue` and `getProperties` in `ConfigSource`, may support property
> expressions as well, but it is not required by the specification.

- Lines 69 to 71 in https://github.com/eclipse/microprofile-config/edit/master/spec/src/main/asciidoc/property-expressions.asciidoc

> Property expressions must also be applied to configuration properties injected via CDI. A default value
> defined via `org.eclipse.microprofile.config.inject.ConfigProperty#defaultValue` is not eligible to be expanded since
> multiple candidates may be available.

**Comment by Emily-Jiang** [comment]
@NicoNes these paragraphs are all talking about the values though as all of the methods mentioned look up for config values. Having that said, if you feel it is unclear, please go ahead to propose a sentence to improve the wording.

**Comment by NicoNes** [comment]
@Emily-Jiang well in my opinion the behavior explained by those paragraph is just like pushing an open door.
 I mean if all the methods in `Config` and configuration properties injected via CDI did not work with property expressions, property expressions will be useless.
So that's why these paragraph mislead me. I though they were pointing out an exceptional behavior but it's not the case.

So if you think that the wording is clear enougth do not change anything my misunderstanding is maybe because of my english and we can close the issue the expected behavior is now clear to me thanks you.
Else my proposal was to replace text by code snippet instead. Or add code snippet to make text clearer.

```
@Inject @ConfigProperty(name="server.url") String serverUrl; \\Returns http://example.org:8080/foo
@Inject @ConfigProperty(name="server.backup.url", defaultValue="server.url") String serverUrl; \\Returns server.url
String serverUrl= ConfigProvider.getConfig().getValue("server.url", String.class); \\Returns http://example.org:8080/foo
```

Thanks
