### ISSUE TITLE
[DISCUSS] How should implementations use the TCK?

### ISSUE THREAD

**Issue by keilw** [eclipse/microprofile-config#72]
Looking for https://github.com/search?l=Java&p=1&q=tck&type=Repositories&utf8=%E2%9C%93 here on GitHub (only those for Java) brings 43 examples. Including at least 6 JSRs.

Pretty much all of them allow independent implementations to be tested usually without having to fork, rewrite or heavily change the TCK itself. Some updates to a POM, command line arguments or similar are usually enough. It's often enough to use the binary TCK as dependency in test kits like https://github.com/mtau11/weld-glassfish-tck-runner or https://github.com/unitsofmeasurement/unit-tck-usage (which runs against 3 different implementations in a CI server with transparent results)

At the moment the TCK module contains some implementations, but it does not seem ready to replace those with external 3rd party implementations, so the only way to test those would be to fork the TCK and modify its code which does not sound very practible even for a 1.0 milestone of the config framework.

**Comment by Emily-Jiang** [comment]
@keilw can you create a discussion on the mailing as it related to the whole microprofile rather than an specific issue on config?

**Comment by OndrejM** [comment]
I agree with Emily, it is good to discuss some cross-concern things in the mailing list.

Just a question related to config TCK:

> At the moment the TCK module contains some implementations

Would you be more specific? I thought that the TCK module is OK and contains only tests and test setup code. I was using it to test my implementation module, and I only needed to modify the configuration of the tests, because I was lazy to bundle my impl to any MP container and I added my impl into a test app.

**Comment by keilw** [comment]
In a sense yes, this is the first "genuine" API and definition here, so it enters uncharted territory, but unlike having a showcase like the config app in future an ideal TCK for everything would test not only this API but e.g. aspects of CDI, JSON or JAX-RS, too.

**Comment by keilw** [comment]
@OndrejM Both https://github.com/eclipse/microprofile-config/tree/master/tck/src/main/java/org/eclipse/microprofile/config/tck/configsources and https://github.com/eclipse/microprofile-config/tree/master/tck/src/main/java/org/eclipse/microprofile/config/tck/converters contain implementations of the API.

Take https://github.com/unitsofmeasurement/unit-tck/blob/master/src/main/java/tec/units/tck/tests/unit/UnitConversionTest.java because it also tests converters, those are retrieved by SPI elements like ServiceProvider only. The TCK does ot contain any implementing class for `UnitConverter` or other Systems Under Test.

**Comment by OndrejM** [comment]
@keilw Classes tck/configsources package and tck/converters package are part of the test, not of an implementation. They are part of the application under the test, in particular ConverterTest and CustomConfigSourceTest. Both are testing the SPI part of the API, therefore some custom implementation is necessary for testing, but they are mocks.

However, the tests are not explicit about using those classes, I intend to improve the tests so that their dependencies are evident and also the test case is more descriptive.

**Comment by keilw** [comment]
@OndrejM If they simply are component tests for the API, then this is not a TCK (which has the word "compatibility" in it, so it is meant to test various implementations)
I mentioned where JSR 363 has its TCK, those kinds of internal component tests for the API are here https://github.com/unitsofmeasurement/unit-api/tree/master/src/test/java/javax/measure/test. Where you'll find "small scale" implementing classes much like those in the "TCK" module to guarantee among other things the 93% test coverage of JSR 363.

**Comment by keilw** [comment]
@OndrejM Maven clearly separates them so no point putting them in a different repository, but at least most Eclipse projects do it anyway in a "test-plugin" artifact, e.g. 
- https://github.com/eclipse/dawnsci/tree/master/org.eclipse.dawnsci.hdf5.model
- https://github.com/eclipse/dawnsci/tree/master/org.eclipse.dawnsci.hdf5.model.test

The test is a component test regardless if you retrieve it via OSGi, the java.util.ServiceLoader (actually IMO at least those two should both be there in a proper Eclipse project) or something else. 

A TCK tests external independent implementations, that is not what these tests do right now. If they stay in one repository or Maven module, then e.g. using different Maven profiles it should be possible to call them separately.

**Comment by keilw** [comment]
BeanValidation (JSR 380) has exactly the same kinds of tests as 363 or other JSRs with all Open Source RI and TCK: https://github.com/beanvalidation/beanvalidation-api/tree/master/src
contains "API tests", component tests or whatevery you may want to call them.
while https://github.com/beanvalidation/beanvalidation-tck/tree/master/tests contains the actual TCK and its tests.

Ask @gunnarmorling if you want how he feels these different tests should be grouped and separated, but I would at least put them into a separate "test" module plus a "tck" module or keep the API tests in the standard "test" folder of the API module. Not mix them in an inseparable way in the same module.

**Comment by struberg** [comment]
+1 to @OndrejM . An e.g `DuckConverter` is just an example for a custom Converter and of course not a built-in `Converter`. This whole module is pretty much set up like we did it in the CDI TCK almost ever since.

**Comment by keilw** [comment]
@struberg @OndrejM Then where are these tests CDI got almost ever since? (and so all the others like BeanValidation, UoM, JavaMoney or JCAche) https://github.com/cdi-spec/cdi/tree/master/api/src/test/java/org/jboss/cdi/api/test

**Comment by keilw** [comment]
So if the rudimentary implementation is seen as part of the TCK, then this ticket is about missing API tests: https://github.com/eclipse/microprofile-config/issues/75

**Comment by keilw** [comment]
@Emily-Jiang @OndrejM We should stick to the main goal of this ticket beside others (like missing tests of a different kind) to answer "how do people use the TCK and test their own implementations?" 
There should be a question on the "umbrella" level about modularity and optionality (as seen in the CDI TCK a bit or more distinct the JSR 363 one) e.g. config will likely not be a mandatory component every "1.0 compatible solution" is forced to use (what if they use Archaius, DeltaSpike, Typesafe or Apache Commons Config already) so there needs to be some "profile" similar to selecting between "Full" and "Web" when running the Java EE TCK or even just that of CDI.

**Comment by struberg** [comment]
> Then where are these tests CDI got almost ever since?

@keilw was this a serious question? I thought you are a fellow CDI EG member (at least that's what the JCP page says). And you don't know that we have written about 700 test classes with close to 2000 tests?
https://github.com/cdi-spec/cdi-tck

I also don't see where we miss API tests in the microprofile-config TCK. All the APIs are clearly covered:

- For Config, ConfigProvider and ConfigBuilder https://github.com/eclipse/microprofile-config/blob/master/tck/src/main/java/org/eclipse/microprofile/config/tck/ConfigProviderTest.java
- For Converter: https://github.com/eclipse/microprofile-config/blob/master/tck/src/main/java/org/eclipse/microprofile/config/tck/ConverterTest.java
- For ConfigSource and ConfigSourceProvider https://github.com/eclipse/microprofile-config/blob/master/tck/src/main/java/org/eclipse/microprofile/config/tck/CustomConfigSourceTest.java

That covers all API classes we have right now. Of course the tests might get improved, but they do exist.

**Comment by keilw** [comment]
@struberg I am in the EC even longer than in the CDI EG having helped negotiate a workable agreement between JSRs 299 and 330 on how to build on top of each other.

I am asking why you decided to throw them into a single basket while every award winning Spec Lead (@atsticks, Antoine or myself we all won JCP Awards, Star Spec Lead or both in different categories) of the mentioned JSRs separated them?;-) If it was the correct place to put those API tests into the TCK instead of 2 separate modules, when why does every single project do it differently...?

**Comment by keilw** [comment]
Btw @struberg you keep speaking for the CDI EG with "we did this and that", but https://github.com/cdi-spec/cdi-tck/graphs/contributors shows you never wrote a single one of those 2000 tests ;-)
(there seem meager 160 lines or so in the API module, that's it) 

While others by further improving how the CDI TCK works created TCKs that offer full support of modularity and optionality in ways MicroProfile must also support if it wants finer-grained profiles and likely optional features beyond the strict "Full" or "Web" status Java EE got so far.

**Comment by struberg** [comment]
Werner, you can browse the CDI and CDITCK jira tickets and will find about 200 tickets which I either created (some with patches) or contributed to. If you browse the CDI meeting protocols then you will see that I attended almost all of them since 2009. Anyway this ticket is not about my contributions to CDI but about you claiming that microprofile-config does not have any TCK tests. Where in fact we do. And also without having to change the TCK source. I'm happy about every improvement though, so feel free to ship your patches.

**Comment by keilw** [comment]
Well I also said on other occasions like the hangouts, that pushing code is not the only way to contribute, whether it's JCP/JBoss or Eclipse ;-)
This ticket is about making the TCK useful to implementations, not about how many tests it contains. There is another one asking if a separate kind of tests should exist either "api test" or a similar term.

**Comment by gunnarmorling** [comment]
Hey there, just wanted to state that it's unclear to me, too, how the TCK is supposed to be run by providers of the API. Instructions for doing so would be great.

As an example, here are [the set-up instructions](http://docs.jboss.org/hibernate/beanvalidation/tck/1.1/reference/html_single/#configuration) for the Bean Validation TCK.

**Comment by struberg** [comment]
@gunnarmorling Yes, we should clarify this. I expect that it might change though when we like to support for more CDI features like provided in my cdi PR or Ondrejs work. In which case we might move over to Arquillian. The work has all been done, I'll pull those parts over from https://github.com/struberg/microprofile-config/tree/cdi-only/tck

**Comment by Emily-Jiang** [comment]
I have been thinking about the TCK and make the implementations running against it. First, we need to produce the instruction. By the way, do we have to use testng? Will Junit be ok?

**Comment by keilw** [comment]
I guess technically JUnit would also work, but there have been some benefits using TestNG for other TCKs (CDI, JavaMoney or UoM all do, so does BV, I trust @gunnarmorling can also say more about that)

**Comment by struberg** [comment]
@Emily-Jiang testng is easier to use for TCK like situations.
You can e.g. exclude tests via config if they turn out to be actually non portable. And you can better align them with the deployment situation for your implementation

**Comment by OndrejM** [comment]
+1 for testng, I can convert my CDI tests to testng later. I just decided to use what was easier for me.

+1 for clarification of how to run the TCK against an impl.
My view so far is that an impl provides an arquillian connector, using the TCK module as a test dependency. For Java SE tests, no arquiallian connector is needed, but we may want to turn all tests into Arquillian tests to align them and test an impl in isolated classpath - TCK tests should not be unit tests, but rather integration/system tests, therefore classpath isolation makes much sense to me.
