### ISSUE TITLE
getPropertyNames for Environment Variables

### ISSUE THREAD

**Issue by bh-tt** [eclipse/microprofile-config#736]
**Description**

Given an environment variable with the name `TEST_ABC`, what should the getPropertyNames method of the environment Config return? Is it only `TEST_ABC`, or `TEST_ABC` and `test.abc`? 

The spec is clear on how to map a property name to several different environment variables (replace non-alphanumeric with an underscore, check if that exists, if not uppercase the property name), however I did not find anything about the result of Config#getPropertyNames. 

The only [hint](https://github.com/eclipse/microprofile-config/blob/11f6443459c81b5451fcdfab38c6d3849a896bf6/api/src/main/java/org/eclipse/microprofile/config/spi/ConfigSource.java#L131) I can find is that the returned property names may be subset of the properties to be evaluated.

Of course the list of property names will grow very fast should you return all possible values of lowercasing and replacing underscores with any non-alphanumeric character (e.g. `tEST_ABC`, `TeST_ABC`, and on), so that is probably not an option.

**Comment by Emily-Jiang** [comment]
@bh-tt for your scenario, the getPropertiesNames() should return the variable name specific to your environment. It it is `TEST_ABC`, it should return that. The mapping rules is to match the property existing in other config source against the environment variables, but it does not change the property names specified in any config sources including environment variables.

**Comment by Emily-Jiang** [comment]
> @bh-tt for your scenario, the getPropertiesNames() should return the variable name specific to your environment. It it is `TEST_ABC`, it should return that. The mapping rules is to match the property existing in other config source against the environment variables, but it does not change the property names specified in any config sources including environment variables.

@bh-tt are you happy with the above response? Do you think the javadoc needs to be enhanced to say the above sentence?

**Comment by bh-tt** [comment]
I'm happy with the response, and I think anyone with the same question will be able to find this issue with your  response. Adding it to the javadoc might force implementations to change their behavior which is not necessary. Feel free to close this.

**Comment by Emily-Jiang** [comment]
Thank you @bh-tt for your response! Close this issue for now.
