### ISSUE TITLE
Missing API tests

### ISSUE THREAD

**Issue by keilw** [eclipse/microprofile-config#75]
So far there are no API or component tests (unless they're hidden in the TCK, but that should not be mixed up) in either https://github.com/eclipse/microprofile-config/tree/master/api/src/test or an equivalent module like "test" (the most common practice for Eclipse projects to have a separate "test" module, but Maven test folder would also do in this case)

See https://github.com/cdi-spec/cdi/tree/master/api/src/test/java/org/jboss/cdi/api/test
(not the TCK) and dozens of other examples. Every API that offers some form of TCK does have its own component tests first.

**Comment by struberg** [comment]
Acutally all the APIs have test coverage in the TCK.

**Comment by OndrejM** [comment]
> Acutally all the APIs have test coverage in the TCK.

Nevertheless, I'd encourage anyone to create tests in the API module to demonstrate the usage of the API. The purpose of those tests would not be to cover all scenarios (that would be the job of TCK), but to show some intended usage. Therefore it should be well commented and readable.

**Comment by keilw** [comment]
Yes, that is good and common practice by every Eclipse project. And each project has to show such good practice during the Release review by Eclipse EMO and Architecture Board.
