### ISSUE TITLE
TCK tests assume empty bean.XML is discovery mode ALL

### ISSUE THREAD

**Issue by rdebusscher** [eclipse/microprofile-config#765]
The TCK of 3.0.2 still makes use of an empty bean but assumes discovery mode ALL (the behaviour of Jakarta EE 8 and 9)

But since MP 6.0, the expected underlying version is Jakarta EE 10 and CDI 4.0 where empty beans mean discovery mode annotated.

Without  some additional tweaking within the TCK runner, the TCK tests are failing.

**Comment by Emily-Jiang** [comment]
Please see the TCK [instruction](https://github.com/eclipse/microprofile-config/blob/3.0.x/tck/README.adoc) on how to get this test to run against CDI 4.0. We discussed this at a great length but there was a concern to remove the empty beans.xml to reduce the coverage of an empty beans.xml on CDI 3.0.

**Comment by rdebusscher** [comment]
This is in the CDI 4.0 specification.

>When running in a CDI Lite environment, only the bean-discovery-mode attribute is read from the beans.xml file. This means that by default, only those types with Bean defining annotations will be considered. Deployment relying on discovery of all types will either need to include a beans.xml with bean-discovery- mode=all, or introduce bean defining annotations to beans in the deployment.

Since the TCK of MP Config 3.0.2, part of MP 6.0 and targeted to CDI Lite 4.0 (as part of Jakarta EE 10 Core) expects discovery-mode ALL to be able to be successfully executed, it violates a requirement of the CDI specification.
Therefore I cannot run the Config TCK against my runtime.

**Comment by rdebusscher** [comment]
Also this is present in the CDI spec

>Implementations that do not support CDI Full are required to ignore the content of the beans.xml file, except for the bean-discovery-mode attribute. Implementations that do not support CDI Full are required to detect presence of an archive which contains a beans.xml file that has bean-discovery- mode attribute set to all and treat it as a deployment problem.

This means that a Jakarta Core runtime, having CDI lite, must fail a deployment that has discovery mode ALL and thus is unable to run this TCK.

**Comment by Emily-Jiang** [comment]
The empty beans.xml means bean-discovery-mode=annotated in CDI 4.0. If you take a closer look at the tests, almost all CDI beans are annoated. This should not cause problems. We are talking empty beans.xml not beans.xml with discvery-mode=`all`. By the way, I am off and might not be able to reply to the subsequent messages until the new year.

**Comment by rdebusscher** [comment]
The tests that fail with the default CDI 4.0 discovery mode of annotated are ConverterTest and ConfigPropertiesMissingPropertyInjectionTest.

**Comment by Emily-Jiang** [comment]
dup of #742

**Comment by Emily-Jiang** [comment]
@rdebusscher please try this [3.1-RC1 release](https://github.com/eclipse/microprofile-config/releases/tag/3.1-RC1) to see whether your problem has been resolved.
