### ISSUE TITLE
config maven buils is broken

### ISSUE THREAD

**Issue by Emily-Jiang** [eclipse/microprofile-config#772]
Config maven build is broken for some time. @radcortez is this related to what you have merged lately. 

[INFO] Compiling 13 source files to <https://ci.eclipse.org/microprofile/job/CONFIG-maven-snapshots/ws/api/target/classes>
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for MicroProfile Config 3.1-SNAPSHOT:
[INFO]
[INFO] MicroProfile Config ................................ SUCCESS [ 10.924 s]
[INFO] MicroProfile Config API ............................ FAILURE [  8.087 s]
[INFO] MicroProfile Config TCK ............................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  20.339 s
[INFO] Finished at: 2023-03-22T07:12:41Z
[INFO] ------------------------------------------------------------------------
Waiting for Jenkins to finish collecting data
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.10.1:compile (default-compile) on project microprofile-config-api: Fatal error compiling: invalid flag: --release -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :microprofile-config-api
[JENKINS] Archiving <https://ci.eclipse.org/microprofile/job/CONFIG-maven-snapshots/ws/tck/pom.xml> to org.eclipse.microprofile.config/microprofile-config-tck/3.1-SNAPSHOT/microprofile-config-tck-3.1-SNAPSHOT.pom
[JENKINS] Archiving <https://ci.eclipse.org/microprofile/job/CONFIG-maven-snapshots/ws/api/pom.xml> to org.eclipse.microprofile.config/microprofile-config-api/3.1-SNAPSHOT/microprofile-config-api-3.1-SNAPSHOT.pom
[JENKINS] Archiving <https://ci.eclipse.org/microprofile/job/CONFIG-maven-snapshots/ws/pom.xml> to org.eclipse.microprofile.config/microprofile-config-parent/3.1-SNAPSHOT/microprofile-config-parent-3.1-SNAPSHOT.pom
channel stopped

**Comment by radcortez** [comment]
No. It requires an update to the latest parent (which I'm releasing now). Maven 3.9.x broke a few plugins, and the parent needs to update to the latest versions.

**Comment by radcortez** [comment]
Another issue is that the Jenkins build uses JDK 8, but we moved to 11, so that needs to be updated.
