### ISSUE TITLE
Support integration with Guice for SE systems: Add javax.inject.Qualifier to ConfigProperty

### ISSUE THREAD

**Issue by scr-oath** [eclipse/microprofile-config#777]
**Description**

As a:

- [X] Application user/user of the configuration itself
- [X] API user (application developer)
- [ ] SPI user (container or runtime developer)
- [ ] Specification implementer

...I need to be able to:

Create Guice bindings for fields, method or constructor parameters annotated with `@ConfigProperty`

...which enables me to:

- Create libraries that declare the required configs and defaults without providing guice modules for them
- Run (SE) applications that are configured with Guice by using the [SmallRye Config](https://smallrye.io/smallrye-config) implementation and reflection to create Guice bindings on the fly.
- Use default or write new Config Sources to integrate with other configuration file readers (typesafe.Config, internally developed Configs, etc)

This is currently blocked because Guice requires annotations to themselves be annotated with either `com.google.inject.BindingAnnotation` or `javax.inject.Qualifier`.

If the microprofile config `@ConfigProperty` annotation could add `javax.inject.Qualifier` from [javax.inject:javax.inject:1](https://central.sonatype.com/artifact/javax.inject/javax.inject/1) that would be super helpful!

This would be super easy to make the change here; I've also made a similar request to Guice library (https://github.com/google/guice/issues/1679), but I imagine that to be much harder to both implement and to adopt from all clients/libraries involved.

**Comment by Emily-Jiang** [comment]
@scr-oath MicroProfile has moved up to jakarta namespace. If you want to use javax namespace, you have to use the previous versions of MicroProfile config such as 2.x or prior.

**Comment by Emily-Jiang** [comment]
I am going to close this one based on the above comment. Please reopen if you have other concerns.
