### ISSUE TITLE
Add a CONTRIBUTING.md

### ISSUE THREAD

**Issue by gunnarmorling** [eclipse/microprofile-config#80]
There should be a CONTRIBUTING.md file describing the contribution guidelines, especially the rules for passing the CLA barrier.

It's super-frustrating to send in a carefully crafted PR and to learn after a minute it's "failed" due to the CLA stuff. I personally can take it (we require a CLA, too, but it's conveyed in a nicer fashion to contributors), but it's current way of presentation is prone to driving occasional contributors away. 

Having a CONTRIBUTING.md file (which is linked when submitting a PR) mitigates the pain at least a bit.

**Comment by keilw** [comment]
Shouldn't this rather be in a central place, it is not specific to this particular module. Either MicroProfile.io or the Wiki (that's where many Eclipse projects write about that if they care) sound better than individual readme files in different projects that each have to be maintained.

**Comment by gunnarmorling** [comment]
Having the info in a central place is a good idea. But a CONTRIBUTING.md
file in a repo is specifically handled by GitHub: it will be referenced in
the dialog for opening a PR [1]. Of course we can have a pointer from
individual CONTRIBUTING.md files to info maintained in a central place.

[1] https://github.com/blog/1184-contributing-guidelines

**Comment by Emily-Jiang** [comment]
Good idea. Maybe we should also put the code styles in the same place?

**Comment by struberg** [comment]
@gunnarmorling do you have a PR for this ticket?

**Comment by gunnarmorling** [comment]
No, nothing yet.

**Comment by Emily-Jiang** [comment]
@gunnarmorling will you be able to do PR?

**Comment by Emily-Jiang** [comment]
This is a contributing adoc now.
