### ISSUE TITLE
"ip-validation" required status check points to deprecated information

### ISSUE THREAD

**Issue by gunnarmorling** [eclipse/microprofile-config#81]
It links to https://www.eclipse.org/legal/CLA.php which says at the top:

> This page is deprecated and may contain some information that is no longer relevant or accurate.

Can we have the status check point to up-to-date information, so to not confuse potential contributors.

**Comment by Emily-Jiang** [comment]
@gunnarmorling please discuss this in the microprofile repo or bring it up in the mailinglist, as it is not direct config issue.

**Comment by gunnarmorling** [comment]
Sent a mail to the mailing list.

**Comment by Emily-Jiang** [comment]
thanks, I'll close this.
