### ISSUE TITLE
Add unwrap() methods to Config and ConfigProvider.Builder

### ISSUE THREAD

**Issue by gunnarmorling** [eclipse/microprofile-config#84]
There should be a method `<T> T unwrap(Class<T>)` on `Config` and `ConfigProvider.Builder`, allowing to access additional functionality offered by specific implementations.

**Comment by Emily-Jiang** [comment]
See more discussion on #90

**Comment by OndrejM** [comment]
I suggest discussing this across all API features - I'd like to have a unified pattern across all MP APIs to access vendor-specific features. Having `unwrap` methods only in Config and not in other features where they would also make sense is not worth it.

**Comment by Emily-Jiang** [comment]
I reactivate this as I think potentially we can use the unwrap to provide more debug messages, e.g. config key name, which source it is from etc. It is extensible as well. Thoughts?

**Comment by Emily-Jiang** [comment]
This one is on hold until we have a use case appear.

**Comment by radcortez** [comment]
I think this would be useful to add. The use case is clear. It is a safe way for the user to access the underlying implementation and use implementation specific API's, without an explicit cast that may not work.
