### ISSUE TITLE
Re-consider represenation of unconverted values as Strings

### ISSUE THREAD

**Issue by gunnarmorling** [eclipse/microprofile-config#87]
`ConfigSource#getProperties()` returns a `Map<String, String>` currently, i.e. values are passed a long as strings. Not all sources will natively work with Strings, though. E.g. from JSON files you may also read back ints or booleans.

Should we hence represent values as `Object` instead?

**Comment by struberg** [comment]
But how do you know whether a specific value was intended to be used as String, as Date, as Long or Integer?
Only the one who uses it knows what was intended.

**Comment by gunnarmorling** [comment]
> Only the one who uses it knows what was intended.

That wouldn't change. Only that `getProperties()` would return a `Map<String, Object>` and `Converter` would take `Object` as input, not `String`. Otherwise a JSON-based config source would first have to convert everything to String only to have it converted back to another type using a `Converter` right after.

**Comment by gunnarmorling** [comment]
@Emily-Jiang, @struberg, this is the issue I had in mind when talking about the config source contract. Pointers to an implementation for YAML would be great so we are sure that the interface satisfies its purpose. An example input could be this (based on one from the [Ansible docs](http://docs.ansible.com/ansible/YAMLSyntax.html)):

    ---
    # An employee record
    name: Martin D'vloper
    job: Developer
    skill: Elite
    employed: True
    age: 23
    foods:
        - Apple
        - Orange
        - Strawberry
        - Mango
    languages:
        perl: Elite
        python: Elite
        pascal: Lame
    education: |
        4 GCSEs
        3 A-Levels
        BSc in the Internet of Things
    spokenLanguages:
        - name:   English
          proficiency: 5
        - name:   French
          proficiency: 7

Would be curious to see how it works, also from a usage POV, e.g. how to retrieve the values from spokenLanguages. If that can be done with the prototypical implementations, I'd feel much more confident about the config source contract. It seems a bit painful to squeeze everything into a `Map<String, String>`, but hey, if it works :)

Or if not, we'd at least have some clarity, and could e.g. state that specific constructs of more powerful configuration formats such as nested lists in YAML or things like that are not supported as of 1.0.

Btw. also let me say that I feel sorry about not being able to contribute more code at this point and only have this kind of input to offer, but it's just not doable for me timewise.

**Comment by gunnarmorling** [comment]
Or [that one](https://www.ibm.com/support/knowledgecenter/en/SST55W_4.3.0/liaca/liaca_sample_json.html) is an interesting one, too. I'm not saying we should support every crazy corner case, but I think that's a good example for the kind of input JSON that IMHO should be usable if we are saying that providers can implement config sources based on other formats such as JSON.

**Comment by struberg** [comment]
Had a chat with @gunnarmorling yesterday. 

Yes, we might not perfectly be able to map all values and we always get a 'flat' view on the information. But otoh we avoid huge complexity and are able to always overwrite each value.

I've not played with yaml but I implemented a JSON based ConfigSource, so I can certainly explain what I did. Of course all this logic is up to the ConfigSource in question.

Consider the following JSON:
<pre>
{
    "name":"Topology1",
    "description":"This is a topology",
    "nodes": [
        {
            "name": "controller",
            "description": "This is the controller node",
            "chef_client_options": [
                "-i 3600",
                "-s 600"
            ],
            "runlist": [
                "role[ibm-os-single-controller-node]"
            ]
        },
        {
            "name": "KVM qemu compute",
            "description": "This is a KVM qemu compute node",
            "runlist": [
                "role[ibm-os-compute-node-kvm]"
            ]
        }
    ]
}
</pre>

Each object attribute name will get converted to a dot-separated package name.
This will result in the following config map:
<pre>
nodes.0.name=controller
nodes.0.description=This is the controller node
nodes.0.chef_client_options=-i 3600,-s 600
nodes.0.runlist=role[ibm-os-single-controller-node]
nodes.1.name=KVM qemu compute
nodes.1.description=This is a KVM qemu compute node
nodes.1.runlist=role[ibm-os-compute-node-kvm]
</pre>

Mapping object arrays is of course not perfect, but it's doable.
In practice I would suggest using named objects in the JSON. e.g. 
By simply using the 'name' of the array above as object name you would get the following config:
<pre>
nodes.controller.name=controller
nodes.controller.description=This is the controller node
nodes.controller.chef_client_options=-i 3600,-s 600
nodes.controller.runlist=role[ibm-os-single-controller-node]
nodes.kvmqemu.name=KVM qemu compute
nodes.kvmqemu.description=This is a KVM qemu compute node
nodes.kvmqemu.runlist=role[ibm-os-compute-node-kvm]
</pre>


</pre>

**Comment by OndrejM** [comment]
I was thinking about it yesterday and I came to the same conclusion - for basic values, it is easy to map any tree structure to a flat structure with dot-separated prefixes. Array are problematic, but the config spec doesn't support them yet. We can add support for arrays/collections later, and then it would be easy to map from JSON/YAML arrays to string values again.

**Comment by struberg** [comment]
I think it's good enough to be easy for 99% of use cases. And the remaining 1% is maybe not so elegant but would still work. Otoh this easy String/String based attempt spares us TONS of complexity we would get with a String/Object handling.

**Comment by Emily-Jiang** [comment]
# An employee record
name: Martin D'vloper
job: Developer
skill: Elite
employed: True
age: 23
foods:
    - Apple
    - Orange
    - Strawberry
    - Mango
languages:
    perl: Elite
    python: Elite
    pascal: Lame
education: |
    4 GCSEs
    3 A-Levels
    BSc in the Internet of Things
spokenLanguages:
    - name:   English
      proficiency: 5
    - name:   French
      proficiency: 7

For parsing this yml, you create the direct Java representation for this, Employee and SpokenLanguage. For spokenLanguage, it can be converted to 

spokenLanguages.0.name=English
spokenLanguages.0.proficiency=5
spokenLanguages.1.name=Frence
spokenLanguages.1.proficiency=7

**Comment by Emily-Jiang** [comment]
We demonstrated this is possible and works.
