### ISSUE TITLE
Missing contribution history

### ISSUE THREAD

**Issue by keilw** [eclipse/microprofile-config#88]
Most sources are missing a contribution history. 

Regardless of who the primary author or module owner is there should be a contribution history similar to
```
* Contributors:
 *     02/19/2015 - Rick Curtis
 *       - 458877 : Add national character support
 *     03/06/2015-2.7.0 Dalia Abo Sheasha
 *       - 461607: PropertiesUtils does not process methods with String parameters correclty
```
from EclipseLink: https://github.com/eclipse/eclipselink.runtime/blob/master/jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/config/TestPropertiesUtils.java

Note while Oracle is the Spec Lead of JPA, this particular class also says `Copyright (c) 2015 IBM Corporation. All rights reserved.` despite e.g. Oracle employees had contributed.

**Comment by struberg** [comment]
Only because others do it wrong we should do either?
Just because some people do not stop on a red ample no one should?

**Comment by keilw** [comment]
It's not done properly here, there are no files with a history of which issues were changed by whom.
Simply putting random "author" tags there because something was "inspired" by another project is not a proper contribution history. If pull requests by @OndrejM, @gunnarmorling or others were merged or an issue fixed that should be recorded.

**Comment by struberg** [comment]
Well, if you say it's needed than I gonna prepare the initial parts.

**Comment by keilw** [comment]
It's taking shape, only saw e.g. the Config class, but I assume others also get one.
What is that magic string "fb0131106481f0b9a8fd" in the first entry?

And has every single person mainly Gerhard and Ron signed the ECA? They don't have to be committers but if they are mentioned they must have signed at least that.

**Comment by struberg** [comment]
That's the commit sha1 (first 20 chars).
The full URL in that case would be
https://github.com/apache/deltaspike/commit/fb0131106481f0b9a8fdc13b9879a5482219c736

> And has every single person mainly Gerhard and Ron signed the ECA?
Yes, Ron, Gerhard and Romain all have signed the ECA.

**Comment by Emily-Jiang** [comment]
Hangout meeting minutes: Need to follow up with Eclipse board about the process.

**Comment by keilw** [comment]
Looks like it's done for `Config` and other elements in this API.
