### ISSUE TITLE
Clarify if Config instances need to be Serializable

### ISSUE THREAD

**Issue by struberg** [eclipse/microprofile-config#89]
When storing a Config instance inside a serializable class (e.g. @SessionScoped) then we would need to have the Config Serializable as well.

This is easy to implement for container managed Config instances at least. 
While the internal data (ConfigSources etc) are often not Serializable we can simply _re-attach_ to the current application Config again.

Not sure about Config instances one creates manually and does _not_ manage within the application. Those might end up not being Serializable.

**Comment by Emily-Jiang** [comment]
The unmanaged config should not be serializable. We should put this on the javadoc.

**Comment by Emily-Jiang** [comment]
MP Config hangout discussion: for @Inject config, it is guaranteed to be serialzable.

**Comment by Emily-Jiang** [comment]
After more thoughts on this, the injected config is difficult to be serializable as it has a list of config sources (default sources + auto discovered sources), which are not guaranteed to be serializable.  We need to modify the javadoc changes to say they are not serailzable even for the injected ones.

**Comment by OndrejM** [comment]
This is an implementation detail. But I think that even with dependent instances, the injected config instances can provide a custom serialization mechanism by implementing read/writeObject methods.
