### ISSUE TITLE
Add Config#unwrap() and ConfigProvider.Builder#unwrap()

### ISSUE THREAD

**Issue by OndrejM** [eclipse/microprofile-config#90]
As proposed by #85 PR.
We agreed that it is out of scope of config 1.0. We may discuss later if there is real need for it. Ideally, discuss it on a higher level, whether we'd like to have methods like these in other specifications too, so that we establish a common pattern.

**Comment by Emily-Jiang** [comment]
Joined the party late. I also had a chat with Emmanuel Burnard on this during Devoxx US. I think what @gunnarmorling suggested is to offer some freedom to explore some implementation details. There are some scenarios we might have missed but we can provide the extension for the implementation to plug in. Right? We can discuss this briefly in the next hangout. If we cannot agree, we can defer it to the next release.

**Comment by gunnarmorling** [comment]
> but we can provide the extension for the implementation to plug in.

WDYM by "extension"? The idea is the let users easily get access to advanced functionality offered by specific providers. Say a provider has a type literal class for safely obtaining instances of generic types, e.g. `List<String>`. Then a user could do this:

    List<String> stringProp = config.unwrap( GenericTypeSupport.class )
        .get( "myKey", new TypeLiteral<List<String>>{}() );

As discussed, the same could be done with static methods, but having an unwrap method right on the API makes the concept much more apparent and easily findable. We've made very good experiences with this in JPA and Bean Validation.

**Comment by Emily-Jiang** [comment]
Continue the discussion on #84 . Will reevaluate when Gunnar is on call.
