### ISSUE TITLE
Undo rogue and unsanctioned groupId "apis"

### ISSUE THREAD

**Issue by keilw** [eclipse/microprofile-config#92]
Hi,

While it was discussed that "Specs" (technical documentation, not software) could have a separate namespace (still nothing was decided) there was no decision in recent hangouts that all APIs should suddenly have the same groupId like     "org.eclipse.microprofile.apis"
Please point out in minutes like
https://docs.google.com/document/d/16v3jVkcDzVz9BVU5aGEzPVbK-a8BIx7S1gbqToVUaLs/edit#

Where this had been decided?

It's sad and disruptive (will simply delay any release of the overall MP deliverables significantly) that individuals are not able to control their urge to change something in their own way but follow what was discussed and decided. Please undo, until something for ALL projects is decided and agreed upon.

**Comment by keilw** [comment]
More significantly,  "org.eclipse.microprofile.config.tck" has config in it, "org.eclipse.microprofile.apis" has not. That makes absolutely no sense. Either both (and possibly a "spec", that's the only thing that I recall was close to a consensus about a separate top level groupId) do, or none.

**Comment by struberg** [comment]
The API is the API is the API! -> no config, just class files.

The TCK is the TCK is the TCK. -> no api, only tests, test data, test config, etc. Not needed at runtime, only to check if the implementation is spec conform.

**Comment by struberg** [comment]
Yes, the common groupId has indeed been discussed and the common understanding was that it would be good to have a single place where user can look like. @jclingan might give you more info.

**Comment by keilw** [comment]
Again this is not a "Shadow JSR" although some may still think so.

If APIs are in a single top level, so must be TCKs, there was actually a thread with quite a bit of consensus (including @OndrejM or @Emily-Jiang here) to move TCKs into a single repository: https://groups.google.com/forum/?hl=en#!topic/microprofile/P1KfdvbCNPc Whether or not it could wait till a module like config did its first release, I guess I am also flexible, but it sounds inevitable, hence the TCK should be a higher priority to get a proper groupId like "org.eclipse.microprofile.tck".

**Comment by keilw** [comment]
There's been a consensus on using the "sub-module" aka "config" by several contributors here https://groups.google.com/forum/?hl=en#!searchin/microprofile/groupid|sort:relevance/microprofile/tPoOrdSJffw/bcBZ6OUECwAJ including @OndrejM Why are their opinions brushed away?? @jclingan made a single remark not even a binding vote in another thread, so please don't consider that a decision.

**Comment by struberg** [comment]
If you confuse quite a bit. We do have distinct groupIds per project. 
But we later also agreed, that the apis should all be in a separate group.
e.g.:
https://groups.google.com/d/msg/microprofile/qOfSWcWRBDQ/ggfQL93-EAAJ

**Comment by keilw** [comment]
I think you mistake the "spec" (or later "TCK") for "api".
https://groups.google.com/d/msg/microprofile/qOfSWcWRBDQ/ggfQL93-EAAJ
Only a few e.g. @Emily-Jiang made concrete proposals e.g. have everything under 
"org.eclipse.microprofile" 
but there was never a vote, or is there a record e.g. on the "dev" mailing list? As of now that list is only used to vote on committers. So yes it should be discussed in the "umbrella" talk as I can't see anything close to a consensus or a firm vote in either of those threads.
