### ISSUE TITLE
Code Formatter plugin similar to microprofile-samples

### ISSUE THREAD

**Issue by keilw** [eclipse/microprofile-config#93]
In microprofile-samples I included the [formatter-maven-plugin](https://github.com/revelc/formatter-maven-plugin). You have to use a dedicated **formatCode** profile. This profile currently works only on the top-level pom but includes all modules that are included there (so we only need the format template once) 

The format definition in  https://github.com/eclipse/microprofile-samples/tree/master/src/format is an Eclipse code Formatter profile called "MicroProfile", ideally meant to work for all interested MicroProfile modules. It could be maintained centrally if everyone agrees on a repository. As long as e.g. that repo is always cloned, too, the file may not even have to be in a repo like "samples" or "config", but the Maven profile should be in the POMs to pick it up. It is only called using this profile. 
So far the plugin only offers a "format" goal, so no checking, that has to be done by other plugins like checkstyle, etc. It can help to automate formatting e.g. before a merge if different sources may vary in their code style or editors. Since the format definition is based on Eclipse, those who happen to use Eclipse or an Eclipse based IDE can benefit by using the same format profile also when they develop MicroProfile code.

**Comment by struberg** [comment]
Modifying the code via a plugin is an absolute IP no-go and must not be done. 
You simply cannot just reformat foreign code. 
We also already enforce a certain code style (without being too strict to unnerve people), so I see no huge benefit in such a profile.

@Emily-Jiang what do you think?

**Comment by OndrejM** [comment]
@struberg is right, we shouldn't encourage formatting of code that was not modified for other reasons. If everybody used the plugin I guess that only our code changes would be formatted, but can we rely on that? It would be great if the plugin could check git status and only modify the code that was changed since the last revision. @keilw can the plugin do that?

**Comment by keilw** [comment]
It is a Maven plugin, not a Git or GitHub plugin. 

What code style is enforced or checked? Checkstyle?

**Comment by keilw** [comment]
IC checkstyle, why is the entire rule in the POM, does that have a significant benefit over using a dedicated checkstyle file? Ideally those rules should be consistent across different subprojects. And even if the format was not applied via a plugin, it is the same that can be used in an Eclipse IDE by those using Eclipse.

A lot of large commercial clients enforce those types of rules. If not using a Maven, Ant, Gradle or similar plugins at a certain stage, it is automatically formatted by every IDE across the team. That's quite common in professional environments.

We always hear things like "The IP that's copied and pasted must not change" but there is no IP that's copied and pasted. That would be a no-go and had it happened, the Eclipse IP team would immediately flag such code and demand it to be removed. 

Well beside certain technical quality the Architecture board also checks during release reviews, I don't see that using e.g. a particular IDE or editor was enforced. The project lead of a large Top Level project told us during an Eclipse event he uses Emacs, and the colleagues who helped Hudson in a previous team also did so using either Emacs or Vi, not Eclipse. In another repo I came across a more sophisticated code checker that seems free for open source. I am not sure, if it's free for larger projects but as long as the project is Open Source here, it might be.

**Comment by Emily-Jiang** [comment]
I was thinking a formater template for eclipse IDE, where you can format your code properly especially on the new files and work with the api style check mvn plugin. I do agree that no auto formatting should be happening for no apparent reasons. This will also make the PR show up more changes than necessary, which will complicate the review process.

**Comment by struberg** [comment]
@keilw the rule is in the pom because otherwise you would need one more parent module + one more checkstyle module. The reason is that you cannot specify the checkstyle file as dependency to the maven-checkstyle-plugin in the parent pom before it got built. A classical chicken-egg issue.

@Emily-Jiang and let's not forget the additional headache when merging if files got change for no apparent reasons ;)

**Comment by Emily-Jiang** [comment]
MP config hangout on 6th April: We have checkstyle plugin and it will fail the build if the style is incorrect.
