### ISSUE TITLE
Why a redundant version in the artifactId?

### ISSUE THREAD

**Issue by keilw** [eclipse/microprofile-config#94]
Leaving the groupId aside (this has to be decided in a consistent way for all parts of upcoming releases) I noticed a redundant static version number in the artifactId `microprofile-config_1.0_api`. 
Why should a JAR be named `microprofile-config_1.0_api-1.0-SNAPSHOT.jar` or later `microprofile-config_1.0_api-1.0.jar`? That makes no sense. The version will be part of the file name anyway.

**Comment by OndrejM** [comment]
Though I understand the reasoning, I'd let @struberg explain. However, even if it would be the best approach, I wouldn't make these decisions without discussing first in the open, ideally mailing list. Please, Mark, don't make any changes like this without a previous discussion, otherwise it will get messy. Everybody needs to understand the reason and it should be documented, otherwise nobody will keep the same convention.

**Comment by struberg** [comment]
Hi!

First let me say that both are possible. By having the version in the api name itself we can ship updates without breaking Maven versioning.
There are pros and cons of this approach.

If we would keep the same artifactId for different spec versions then any maven versions:show-dependency-update (or sonar, etc) would always show you the next version once we release it. Even if you don't even want to target this spec version.

Just look at http://repo1.maven.org/maven2/org/apache/geronimo/specs/

By having the version in the jar name it is much more explicit what you got.

**Comment by keilw** [comment]
Those Geronimo artifacts are 5 years old or older. 
Whether it gets included in MicroProfile 1.1 or later, the artifacts should be consistent across different submodules, thus @OndrejM mentioned it would be good to get a consensus (I asked to decide what everyone wants as groupId, there are other threads although not a formal vote I believe discussing what should be in the artifactId, dots or hyphen, etc.)

**Comment by Emily-Jiang** [comment]
I would only put the bundle version on the filename, not mentioning two versions. 
I would suggest microprofile-config_1.0_api-1.0-SNAPSHOT.jar to be microprofile-config-api-1.0-SNAPSHOT.jar

**Comment by OndrejM** [comment]
@Emily-Jiang, this is not about the final file name - we can easily tweak it using finalName in pom.xml. The discussion is about whether to have the main version in the artifact name or not. This would be useful to separate different versions of the artifacts completely - if you just request the latest version of microprofile-config, you could get 1.0 now, 1.0.1 if we have a patch release, and 1.2 or even 2.1 much later. If we have artifacts with version in theier name, e.g. microprofile-config-1.0, you wouldn't get 1.1 or 2.X versions if you request the latest version.
Having said that, I don't see much use cases for having the version in the artifact name. I know that without it, IDEs would suggest all versions of the artifact, even if we care only about 1.0.X versions, and automated checker would complain about newer artifact versions, as @struberg explained. But that is not enough for me to complicate things and I'd stick to the pattern used also by the Java EE API artifact - having the same artifact name for different versions.

**Comment by struberg** [comment]
Whatever solution we will finally settle on (all of them have pros and cons), I really love how the community brings up/picks up ideas and discuss them in a productive way!

At the end it's about understanding the options and trying to avoid cargo cult.

**Comment by Emily-Jiang** [comment]
Thanks @OndrejM for putting me on the right track! I would suggest we follow the JavaEE api fashion as it does work and most people got used to it. e.g.
```
<!-- https://mvnrepository.com/artifact/javax.enterprise/cdi-api -->
<dependency>
    <groupId>javax.enterprise</groupId>
    <artifactId>cdi-api</artifactId>
    <version>1.2</version>
</dependency>

```
It means the artifactId carries no version info.  I do agree with @OndrejM that we should discuss on the mailing list, so that we can get all specs use the same convention. @keilw , would you like to start a conversation or want me to do it?

**Comment by OndrejM** [comment]
I've create a PR #120 to change the artifact name and group to 

```
<groupId>org.eclipse.microprofile.api</groupId>
<artifactId>microprofile-config-api</artifactId>
```

I think this is more acceptable by the majority, and also by end users. Can we agree on this?

**Comment by OndrejM** [comment]
We have a vote now in the [google group](https://groups.google.com/d/msg/microprofile/iWAimG6CtAM/rLax8myuAAAJ) to decide on common naming scheme.

**Comment by Emily-Jiang** [comment]
This is fixed.
