### ISSUE TITLE
Add missing NOTICE file

### ISSUE THREAD

**Issue by johnament** [eclipse/microprofile-config#95]
Much of the work in here is derived from Apache DeltaSpike.  While its free to reuse in source form, under the guidelines of the Apache License v2, the NOTICE file must be propagated to indicate that the source is not originally developed here at Eclipse.  Likewise, files derived from Apache DeltaSpike should not include a Copyright IBM header.

**Comment by keilw** [comment]
This feels like the 3rd or 4th clone of https://github.com/eclipse/microprofile-config/issues/73, https://github.com/eclipse/microprofile-config/issues/88 (which is already worked on) or https://github.com/eclipse/microprofile-config/issues/45.

While there is nothing wrong with a NOTICE file, many files e.g. @Emily-Jiang created were from scratch. The methods not only by returning `Optional `e.g. in the `Config `class were always different from a simple copy of either project mentioned in https://github.com/eclipse/microprofile-config/blob/master/README.adoc 

Everyone who at least provided "inspiration" is mentioned in the contribution history. A mandatory "NOTICE" file may not be wrong or forbidden but we should not duplicate effort to maintain by keeeping a) a NOTICE file, b) a Contribution history in all relevant sources and c) maybe a contributors.txt similar to what Hibernate Validator does. 

What'll be next, I guess @jhalterman requests a NOTICE file in https://github.com/Emily-Jiang/microprofile-faultTolerance-incubation saying "Please this was all copied from Failsafe"??? ;-/

**Comment by struberg** [comment]
Well, if it really was mainly taken from failsafe, then it should also get a proper NOTICE and Copyright attribution. We are not free to do whatever we like - we are bound to law still.

**Comment by johnament** [comment]
@keilw failsafe doesn't include a NOTICE file so he wouldn't be able to

https://github.com/jhalterman/failsafe

**Comment by struberg** [comment]
@johnament but if that stuff really got copied over then it imo should at least get the correct Copyright attribution. One is not free to claim own copyright for sources copied from somewhere else - we are bound to law still.

**Comment by johnament** [comment]
@struberg you're correct.  My qualm here is the NOTICE file required by the Apache License, which equally conveys copyright ownership of portions of the code.

**Comment by keilw** [comment]
Is the NOTICE file required by the Apache License or Foundation?
Those are 2 different things and Thousands of projects use Apache License but rarely any have a NOTICE file.

**Comment by keilw** [comment]
The "spin-off" by @struberg has a NOTICE file saying 
>This product includes software developed at
>The Apache Software Foundation (http://www.apache.org/).
but out of this list at least https://github.com/Netflix/archaius has no such file, but we all know it uses Apache Commons Config under the hood (and Archaius is under Apache License) so it does not seem this file is mandatory outside apache.org.

**Comment by struberg** [comment]
Werner, just look at the dates. The thing you called "spin-off" got written in June 2016 and the contains classes written in 2011. The current microprofile repo got the first commits in October 2016. We clearly miss the NOTICE file in Eclipse Microprofile-config.

You can also read the Apache License v 2.0 
https://www.apache.org/licenses/LICENSE-2.0

> If the Work includes a "NOTICE" text file as part of its distribution, then any Derivative Works that
> You distribute must include a readable copy of the attribution notices contained within 
> such NOTICE file,

If Archaius just **uses** commons-config, then no attribution is required. If they took classes from it or shade it in to their own jars then they **do** require the NOTICE file.

**Comment by johnament** [comment]
@keilw NOTICE file is explained via section 4d of the Apache License, v2.  I've copied it below

>       (d) If the Work includes a "NOTICE" text file as part of its
>           distribution, then any Derivative Works that You distribute must
>           include a readable copy of the attribution notices contained
>           within such NOTICE file, excluding those notices that do not
>           pertain to any part of the Derivative Works, in at least one
>           of the following places: within a NOTICE text file distributed
>           as part of the Derivative Works; within the Source form or
>           documentation, if provided along with the Derivative Works; or,
>           within a display generated by the Derivative Works, if and
>           wherever such third-party notices normally appear. The contents
>           of the NOTICE file are for informational purposes only and
>           do not modify the License. You may add Your own attribution
>           notices within Derivative Works that You distribute, alongside
>           or as an addendum to the NOTICE text from the Work, provided
>           that such additional attribution notices cannot be construed
>           as modifying the License.

**Comment by keilw** [comment]
I don't see a problem with a simple NOTICE file that looks pretty much like Mark's repo. 
Eclipse IDE also has a similar sentence e.g. in the platform. https://github.com/eclipse/eclipse.platform.runtime and other repositories do not contain the NOTICE file (they do have a CONTRIBUTE.md like https://github.com/eclipse/microprofile-config/issues/80 requests) so not sure, where this comes into play or if it simply refers to libraries like commons-xyz being used in a binary form. Anyway it does not seem a problem. Other than what the contribution history already tells, I don't think a broader header than e.g. @OndrejM suggested for example cases makes sense. If all other MP modules and components apply the same practice and header, it shouldn't differ from one component to another, only the legal entities of course.

**Comment by keilw** [comment]
Please note, for every piece of code someone claims it was "taken exactly as is from another project" it should not even be here in the first place according to http://www.eclipse.org/legal/EclipseLegalProcessPoster.pdf
>Re-Use of Non-Eclipse Content 

The other channels require to
>Confirm that the Contribution:
>1. Contains No Cryptography
>2. Is Developed from Scratch (without incorporating content from elsewhere) 

So if any of the pieces other than e.g. `Config` or even that are claimed to be "taken from Apache" then it will likely cause a lot of legwork for the IP team because I highly doubt anybody has filled out a Contribution Questionnaire on Committer Tools and included the IPBug reference under which the original approval was granted.... Nor that anything exists in IPZilla on those yet.

**Comment by keilw** [comment]
Btw. if anybody thinks Eclipse Foundation was picky on that, I am sure DeviceMap wasn't the only Apache Project where its mentors prevented proper (Maven) usage of the W3C DDR Simple API
(see https://svn.apache.org/viewvc/devicemap/trunk/clients/w3c-ddr/simpleddr/NOTICE?view=markup) because some or all Java code did not have any headers explicitly stating both the W3C Document AND Software licenses applie to that API.
https://www.w3.org/TR/DDR-Simple-API/javadoc/ only links to the document license, but the "Copyright" link has a summary of both, but that wasn't enough.

**Comment by johnament** [comment]
This issue is completed.

**Comment by keilw** [comment]
Thanks for closing it. Glad I was able to give a reminder. The NOTICE will help IP and legal folks to make their way through the code. Without prior contribution questionaire or IPZilla, I don't think anything will be thrown out, but it might take a while...

**Comment by johnament** [comment]
@keilw your note on the IP provenance is a valid one, however its not really for discussion on this github issue.  Its probably a good conversation for microprofile-dev or the google group, otherwise it seems the ticket is being hijacked.

**Comment by keilw** [comment]
@johnament As this and a few similar tickets made the claim that at least some files were taken "AS IS" from DeltaSpike or similar projects it's just a gentle reminder that it'll cause the "parallel IP" review to take longer before any release is possible, but the mailing list has at least one or two threads where I mentioned April for an umbrella 1.1 release is highly unlikely. Untill the legal folks give their Go there is not going to be a release even a Milestone one I assume.

**Comment by johnament** [comment]
@keilw this is what the ticket says:

> derived from Apache DeltaSpike

Not taken "AS IS"

**Comment by keilw** [comment]
Hopefully that's the case everywhere. I can pretty much say Config must have been written from scratch by @Emily-Jiang even if there was "inspiration" or advice based on those, but 
>Is Developed from Scratch (without incorporating content from elsewhere)

means even if a few lines look like they were copied from "project X" it'll undergo a very tedious review and cross-checking. And believe me I already got enough questions from them e.g. on code generated by projects under a different license etc.

**Comment by keilw** [comment]
Anyway I put a pointer to the Slides in the right thread dedicated to "not take anything from other projects" I think this is the best place on the list.
